### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by farag2** [FilipePS/Traduzir-paginas-web#1]
The first issue: the word does not fit in.
![1](https://user-images.githubusercontent.com/10544660/86733311-c476a480-c039-11ea-9573-c752f33c1336.png)

The second issue: recently I've translated the all extension into Russian but I didn't find "reset" word to translate
![2](https://user-images.githubusercontent.com/10544660/86733626-06074f80-c03a-11ea-90ec-c86867a06d7f.png)

**Comment by FilipePS** [comment]
The problem has been fixed in these commits:
https://github.com/FilipePS/Traduzir-paginas-web/commit/a02ff00b11b55b2adae954a8b584016f710f5265
https://github.com/FilipePS/Traduzir-paginas-web/commit/3294206a4511f819b1ef3a42a5b3748b7f9a2804

**Comment by farag2** [comment]
Please approve changes made by me: https://crowdin.com/project/translate-web-pages/ru
