### ISSUE TITLE
Correct Italian Localization

### ISSUE THREAD

**Issue by giuscond** [FilipePS/Traduzir-paginas-web#10]
Hi,
I love this work. I tried to correct the Italian localization. I appreciate if you can include it in the new versione.

[it.zip](https://github.com/FilipePS/Traduzir-paginas-web/files/5040983/it.zip)

**Comment by FilipePS** [comment]
136/5000
I will update the translations of the next version.
You can also translate through Crowdin hhttps://crowdin.com/project/translate-web-pages/it#
