### ISSUE TITLE
[Feature request] add option Always translate this site from three dot menu

### ISSUE THREAD

**Issue by KenFangidae** [FilipePS/Traduzir-paginas-web#100]
could you please add the option "always translate this site" from the three dot menu?

**Comment by FilipePS** [comment]
Isn't this the second option that appears in this menu?

**Comment by KenFangidae** [comment]
> Isn't this the second option that appears in this menu?

i mean from the three dot popup

**Comment by FilipePS** [comment]
Are you using the extension on your phone?
