### ISSUE TITLE
Problem with Chinese to English translation

### ISSUE THREAD

**Issue by MuhFadjrin** [FilipePS/Traduzir-paginas-web#101]
when trying to translate a whole web page the result of the translation is undefined. like in this page [https://trxs.cc/tongren/4613/1.html](url)
![image](https://user-images.githubusercontent.com/13918743/110238967-09f7c280-7f77-11eb-8db5-e8a8d2f66830.png)

**Comment by FilipePS** [comment]
Bug fixed
https://github.com/FilipePS/Traduzir-paginas-web/commit/39e8050c23c48ea424d377c4471997c4875343bb
