### ISSUE TITLE
"undefined" instead of <a../> content at Wikipedia pages

### ISSUE THREAD

**Issue by parius** [FilipePS/Traduzir-paginas-web#102]
Page example: https://de.wikipedia.org/wiki/Karpfenteiche_(Berlin-Buch)
Translation direction: German -> English

**Original**:
Der Abfluss erfolgt über eine <a href="/wiki/Schleuse" title="Schleuse">Schleuse</a> in den <a href="/wiki/Lietzengraben" title="Lietzengraben">Lietzengraben</a>, der zur <a href="/wiki/Panke" title="Panke">Panke</a> führt.

**Result**:
The discharge takes place via a sluice into the undefined undefined undefined undefined.

**Comment by FilipePS** [comment]
This problem has already been solved, update the extension.
#101
