### ISSUE TITLE
[Feature request] add option to keep original text

### ISSUE THREAD

**Issue by djedu28** [FilipePS/Traduzir-paginas-web#105]
![image](https://user-images.githubusercontent.com/43933482/110259739-0e78a700-7f88-11eb-9560-fe3f9799514d.png)

In the old version there was a button to activate / deactivate the translation momentarily on that page, the new version has this feature but it is not so intuitive,

I want a more direct button for this function just like in the old version.

In the current version you have to select the language repeated in the list, one of which would be the mode with the original text

![image](https://user-images.githubusercontent.com/43933482/110259854-81821d80-7f88-11eb-850b-4c222b68df03.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
translated using google, and below the original text (because i know google fails)

[Solicitação de recurso] adicionar opção para  manter o texto original

na antiga vesão tinha um botão de ativar/desativar a traduçao momentaneamente naquela pagina, a nova vesão possui esse recurso mas não é tão intuitivo, 

Desejo um botão mais direto para essa função assim como na versão antiga.

Na versão atual tem de selecionar a linguagem repetida na lista, uma delas seria o modo com o texto original

**Comment by FilipePS** [comment]
O primeiro botão é sempre o idioma original da pagina e serve unicamente para restaurar a pagina.
Os outros 3 são para traduzir, e aparece um botão repetido porque pode ser da sua intensão traduzir para ele. Mesmo que a extensão detectou que a pagina esta no seu idioma, é possivel que partes da pagina ainda estejam em outro idioma.

**Comment by gulluwing** [comment]
> 
> 
> O primeiro botão é sempre o idioma original da pagina e serve unicamente para restaurar a pagina.
> Os outros 3 são para traduzir, e aparece um botão repetido porque pode ser da sua intensão traduzir para ele. Mesmo que a extensão detectou que a pagina esta no seu idioma, é possivel que partes da pagina ainda estejam em outro idioma.

I'm agree with ha djedu28. you have worsened the addon, it is confusing. among other things, why put target language 1 and target language 2? even more confusion. why make these changes? it was so good and

**Comment by djedu28** [comment]
> 
> 
> O primeiro botão é sempre o idioma original da pagina e servem unicamente para restaurar uma pagina.
> Os outros 3 são para traduzir, e aparece um botão repetido porque pode ser da sua intensão traduzir para ele. Mesmo que uma extensão detectou que a pagina esta no seu idioma, é possivel que partes da pagina ainda estejam em outro idioma.


Now that you have explained, I can better understand the new layout.

It is very useful what you thought of making it possible to translate the language even though the automatic identified it is already there.

how about replacing the button of the original language with a text that references the "keep original text" or leave it in another color

**Comment by FilipePS** [comment]
I'll think of a way to keep these buttons and make their functions more intuitive

**Comment by FilipePS** [comment]
Install version 8.1 that has just been released. And send me feedback.

**Comment by djedu28** [comment]
> 
> 
> Install version 8.1 that has just been released. And send me feedback.

I really liked the new features, thank you very much.

now it has a better interface, with more controls and customization.
