### ISSUE TITLE
"undefined" error when translate from english to simplied chinese

### ISSUE THREAD

**Issue by wccmcd** [FilipePS/Traduzir-paginas-web#107]
right after the latest update yesterday, I got "undefined" for some webpage. like this one: https://www.healthline.com 
firefox version:87.0b7
![111](https://user-images.githubusercontent.com/80241330/110282164-f8ff8d80-8018-11eb-9cb3-18a61942a576.png)

**Comment by haiwx** [comment]
I can reproduce it in Firefox Nightly

**Comment by wccmcd** [comment]
> 
> 
> I can reproduce it in Firefox Nightly

Thank you. I look forward to seeing it.

**Comment by FilipePS** [comment]
Can you tell me if this problem stopped happening after version 8.0.4?

**Comment by wccmcd** [comment]
> 
> 
> Can you tell me if this problem stopped happening after version 8.0.4?

Unfortunately , it's happening on version 8.0.4, which is the version I'm using now.

![4](https://user-images.githubusercontent.com/80241330/110415409-c747fe80-80cc-11eb-845d-1e86dec86058.png)

**Comment by FilipePS** [comment]
As I mentioned in issue #113 , this problem has been solved.
