### ISSUE TITLE
"Never Translate these Languages" still transfers on hover

### ISSUE THREAD

**Issue by mkeroppi** [FilipePS/Traduzir-paginas-web#108]
"Never Translate these Languages" still transfers on hover

**Comment by FilipePS** [comment]
Selecting a language to never translate, only sites with that language will not be translated. Sites with other languages continued to show this button.

**Comment by mkeroppi** [comment]
What I mean is selecting a language to never translate still translate that language on "mouse hover".

**Comment by FilipePS** [comment]
In my tests it seems to be working. If you can provide a link to a website that presents this problem it would help me to find the problem.

**Comment by mkeroppi** [comment]
I've set never translate for "english", "chinese (simplified)" and "chinese (traditional)"

This page is detected as language "unknown" and translates on hover on all texts regardless of actual language of text
https://www.youtube.com/watch?v=oJTjKBsVIZ0&t=44s

This page is detected as language "chinese" and translates on hover on all texts regardless of actual language of text
https://news.rthk.hk/rthk/ch/component/k2/1579489-20210309.htm

This page is detected as language "english" and does not translate on hover regardless of actual language of text
https://www.youtube.com/watch?v=FzSCrFdrgV4

**Comment by FilipePS** [comment]
Because privacy issues translate when hovering is disabled by default in version 8.1 onwards, so this already solves this problem.
