### ISSUE TITLE
Do not enable translation on hover by default

### ISSUE THREAD

**Issue by Atemu** [FilipePS/Traduzir-paginas-web#109]
It is a huge privacy breach. A translator addon that depends on external services should *never* transfer site content without the user *explicitly* asking for it.  
The risk of accidental activation on private information that the user does not want to share with Google or Yandex is very high here and what's even worse: The user wouldn't even know that it happened.  
I'm pretty proficient when it comes to IT and it took me quite a while to figure out what it even is and then deduce what that means for my privacy. I don't think less tech-savy users would be able to do that.

It's a cool feature, no question, but it should NOT be on by default because of the reasons highlighted above.  
A button to enable this mode of translation instead of full page translation might be a better way of exposing it to the user.

**Comment by FilipePS** [comment]
Thanks for the feedback. I will do this in the next version

**Comment by Atemu** [comment]
Thank you!

Please consider privacy issues like this in the when adding new features in the future :)

**Comment by nathancahill** [comment]
This needs to be done now. Extension is disabled until this is fixed.

**Comment by FilipePS** [comment]
Version 8.1 has already been released with this and other fixes
