### ISSUE TITLE
Option to always translate doesn't show on some sites

### ISSUE THREAD

**Issue by DuckOfDuckness** [FilipePS/Traduzir-paginas-web#11]
Example of one such website: http://cafe.daum.net/Dreamcatcher7
![image](https://user-images.githubusercontent.com/1951003/89709067-f4340780-d96b-11ea-9c0b-cf32d6bcbb39.png)

_Originally posted by @DuckOfDuckness in https://github.com/FilipePS/Traduzir-paginas-web/issues/6#issuecomment-670919290_

**Comment by FilipePS** [comment]
All the content on this site is in an "iframe". I don't know why they did it.
Language detection is based only on the main page document. It is possible to detect the language of iframes but I don't intend to do that.
Iframes should be used for content outside the site, not as main content.

**Comment by DuckOfDuckness** [comment]
Well that's super annoying, but definitely not your fault.
Would it be possible to add an advanced option to manually tell the extension what language a site is in as a workaround?

**Comment by FilipePS** [comment]
Instead of specifying the language of the page, do you think it's best to do this?
#13

**Comment by DuckOfDuckness** [comment]
If that can work on this site even with its weird iframe set-up, I guess that might be a more elegant solution. Manually clicking the translate button does translate from the correct language.

**Comment by FilipePS** [comment]
Is your goal just to show the correct language, or do you want the page to be translated automatically?

**Comment by DuckOfDuckness** [comment]
I would like the page to be translated automatically.
