### ISSUE TITLE
it doesn't work correctly

### ISSUE THREAD

**Issue by gulluwing** [FilipePS/Traduzir-paginas-web#110]
see the screenshot below and you can see that it doesn't work fine, to see the original page I had to refresh the page. I used this wonderfull addons for 2 months translating hundreds sites every day and it works perfectly, now is a disaster, I can no longer trust the translation.
you have worsened a perfect addon, it is confusing. And it doesn't work, before when I pressed on "original" the page returned in the original language: now it doesn't. among other things, why put target language 1 and target language 2? even more confusion. why make these changes? it was so good and
![ScreenShot2](https://user-images.githubusercontent.com/80253520/110319340-0a439c80-800f-11eb-8050-5d64bf401d16.jpg)

**Comment by FilipePS** [comment]
The first button is always to restore the page, the others to translate. I'll think of a way to make this more intuitive.

**Comment by gulluwing** [comment]
> 
> 
> Il primo pulsante è sempre per ripristinare la pagina, gli altri per tradurre. Penserò a un modo per renderlo più intuitivo.

I know it but after I pushed it I had to refresh the page to see the oiginal language. You don't want to understand that before it worked fine

**Comment by FilipePS** [comment]
Install version 8.1 that has just been released. And send me feedback.

**Comment by Piulinux** [comment]
8.1.1: The title will not be restored when you click on Original.

**Comment by Piulinux** [comment]
Sorry for bothering again, but when you translate **some** English Wikipedia pages into German, the (HTML) title remains untranslated (while Wikipedia's title on the site gets translated).
Example of a page whose HTML title gets translated: [Free love](https://en.wikipedia.org/wiki/Free_love)
Example of a page whose HTML title doesn't get translated: [Love](https://en.wikipedia.org/wiki/Love)

Doesn't happen when you translate the same page into French or on when you translate on other websites.

**Comment by FilipePS** [comment]
> 
> 
> Sorry for bothering again, but when you translate **some** English Wikipedia pages into German, the (HTML) title remains untranslated (while Wikipedia's title on the site gets translated).
> Example of a page whose HTML title gets translated: [Free love](https://en.wikipedia.org/wiki/Free_love)
> Example of a page whose HTML title doesn't get translated: [Love](https://en.wikipedia.org/wiki/Love)
> 
> Doesn't happen when you translate the same page into French or on when you translate on other websites.

This type of problem has always occurred, on some websites, when it is translated into certain languages.
This occurs when texts from different languages are mixed in the same request for translation services.
I still haven't found a solution.

And please only comment on issues that are strictly related to it. Otherwise, create a [new issue](https://github.com/FilipePS/Traduzir-paginas-web/issues/new).
