### ISSUE TITLE
translation is displayed twice

### ISSUE THREAD

**Issue by peach-lasagna** [FilipePS/Traduzir-paginas-web#111]
![изображение](https://user-images.githubusercontent.com/59787538/110342466-012dec00-805e-11eb-9efb-e7dea0ac46c6.png)
https://vimhelp.org/usr_41.txt.html#ftplugin

**Comment by FilipePS** [comment]
Does this appear when trying to translate the selected text?
or simply while moving the mouse

**Comment by FilipePS** [comment]
I can not reproduce the problem. Did it happen just once, or are you able to generate this problem again?
