### ISSUE TITLE
Restore the user interface.

### ISSUE THREAD

**Issue by yuguamax** [FilipePS/Traduzir-paginas-web#112]
I now have to set three languages to translate, but I want to reduce it to just one.
How can I do it like before?
Is it possible to change it back?

**Comment by FilipePS** [comment]
I will think of a way to keep these buttons, while making it intuitive as before.

**Comment by wccmcd** [comment]
> 
> 
> I will think of a way to keep these buttons, while making it intuitive as before.

Thank you Filipe, I have to agree that the eariler version with just one option for target language was a simplier and better interface.
Anyways, this is the best addon I've ever seen, well done!

**Comment by nathancahill** [comment]
The previous version was so much better. Now it's showing popups everywhere before even enabling it. The first language says "Unknown". Can't tell what the icon is suppose to do, it toggles something? Really miss the simplicity of the past version.

**Comment by FilipePS** [comment]
Install version 8.1 that has just been released. And send me feedback.

**Comment by mgeorge-adit** [comment]
I only translate webpages to one language, English. Could you put an option to hide the two extra buttons corresponding to "Target Language 2" and "Target Language 3".

**Comment by FilipePS** [comment]
I just released a new version that allows you to hide parts of the popup
