### ISSUE TITLE
Pô Filipe, o negócio estragou na última atualização rsrs

### ISSUE THREAD

**Issue by vassilyzaitsev** [FilipePS/Traduzir-paginas-web#114]
Eu praticamente só usava sua extensão para o rutracker.org... mas agora, além de ela não traduzir esse site russo, me parece que não consegue identificar o idioma como antes, traduz automaticamente outros sites que não há necessidade... bem estranho.. Antes funcionava perfeitamente.

**Comment by vassilyzaitsev** [comment]
Correção: O Rutracker voltou a ser traduzido automaticamente. Contudo, alguns sites aparentam estar sendo traduzidos mesmo configurando para não traduzir... Como um vídeo no YouTube que abri que quando deixo o mouse sobre algum texto por um certo tempo aparece aquele popup do tradutor... 
![image](https://user-images.githubusercontent.com/35409978/110524274-09bb0c80-80c8-11eb-9633-51939727e0f4.png)

**Comment by FilipePS** [comment]
Ainda está enfretando problemas?
