### ISSUE TITLE
The function of checkbox does not match the changelog.

### ISSUE THREAD

**Issue by haiwx** [FilipePS/Traduzir-paginas-web#115]
According to the changelog, one of checkbox function is "translate the page automatically".

But it is "Always translate from［language］" in 8.1 actually.

**Comment by FilipePS** [comment]
It seems to me to be right.  When you read the changelog, what did you think it was about?

**Comment by haiwx** [comment]
@FilipePS I think it is "Always translate current website（domain）".

**Comment by FilipePS** [comment]
I fixed the changelog. And in the next version there will be this checkbox that you mentioned, in addition to others.
