### ISSUE TITLE
Translate while hovering

### ISSUE THREAD

**Issue by Piulinux** [FilipePS/Traduzir-paginas-web#116]
I really like this feature but I get weary when I have to add each site.
Could you please add the possibility to **switch between "Show translated text when hovering on these sites"** (where you have to add every site on which you want to use translate while hovering) **and "Disable hovering for these sites"** (where you just have to add on which sites you want to disable the feature)?

**Comment by Piulinux** [comment]
Further, could you add regex for all website and languages lists?

**Comment by FilipePS** [comment]
I will not put an option to activate by default on all sites. But I can think of adding an option to activate in specific languages (example: on all Russian sites)

**Comment by FilipePS** [comment]
An option to translate when hovering on sites with specific languages has already been added. This will avoid having to activate on each site.

**Comment by Piulinux** [comment]
The option to add a site with all its sub-sites with "*.example.org" or via regular expression ("^(.*\.)?example\.org$"), would be nice.
