### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by SergeRomanov** [FilipePS/Traduzir-paginas-web#119]
1. When you hover the mouse over the text, its translation appears. Make the settings for the size of this window. 
2. Make it possible to translate the text when it is highlighted. Two implementation options: the translation takes place immediately and an icon appears when you click on it, a window with the translation appears. 
3. The window with the text translation appears after selecting it by simultaneously pressing Shift or Ctrl or Alt (the key is set in the settings by clicking on it). 
4. In the latest version, we made 3 translation languages. But I only use one language, the others get in the way. Make boxes with checkboxes in the settings so that you can select the desired number of languages. 
5. Error in the plugin. The context menu does not always correctly determine whether the site is in the original language or translated. For example, I see that the site is in English, but the context menu says "Restore original".

**Comment by SergeRomanov** [comment]
1 - Attached a screenshot. It shows the work of your plugin and the "Simple Translate" plugin. You need to make the window wider for your plugin. I also use the "Dark Reader" plugin for Firefox to make a dark theme. Your plugin's text is very bright. This greatly strains the eyes. The "Simple Translate" plugin has the same brightness as the main text.
![11](https://user-images.githubusercontent.com/80398480/110662223-5a209000-81d6-11eb-8cda-188dc806d24d.png)
2 - Ok
3 - I don't use Ublock.

**Comment by FilipePS** [comment]
I'm closing this issue. If you have any more problems, please create a new issue.
