### ISSUE TITLE
Page often not translated

### ISSUE THREAD

**Issue by ewelinawilkosz** [FilipePS/Traduzir-paginas-web#120]
It started a few days ago, about the time I noticed the change in the interface

One of the pages I always translate is live update of coronavirus news, from Swedish to English - the page is refreshed automatically and often new posts are not translated. That wasn't a problem with older version

Also quite often the language of the page can't be determined so it doesn't run the translation. But when I access the page in a few mintes all is good - I have never seen that issue before.

**Comment by FilipePS** [comment]
If you can give me the link to this site, this helps to correct the problem.

**Comment by ewelinawilkosz** [comment]
https://www.svt.se/nyheter/inrikes/senaste-nytt-om-coronaviruset Is the one with live updates 
It happens with subpages of svt.se that it randomly doesn’t recognize the language 
I also had noticed trouble at blocket.se

**Comment by FilipePS** [comment]
Can you tell me if this problem has stopped happening?

**Comment by vmavra** [comment]
> 
> Can you tell me if this problem has stopped happening?
I tested it and it works.
