### ISSUE TITLE
console error: 'Could not establish connection. Receiving end does not exist.'

### ISSUE THREAD

**Issue by atomGit** [FilipePS/Traduzir-paginas-web#121]
the browser console reports this error multiple times - this may be benign, i don't know

the source of the error is in background.js...

`chrome.tabs.sendMessage(activeInfo.tabId, {action: "getMainFramePageLanguageState"}, {frameId: 0}, pageLanguageState => {`

i also saw this error mentioned in issue #16 

FF 86
TWP 8.1.1
linux

**Comment by FilipePS** [comment]
The ".tabs.sendMessage" function sends a message to a content script that is running on a specific tab, if it does not have a content script running or it is not processing messages with ".runtime.onMessage.addListener" this error appears. It is not exactly a bug, and it does not impact the functioning of the extension. And can be hidden  https://github.com/FilipePS/Traduzir-paginas-web/commit/4d5e783f021bf95d9ea81170940a2f3e369ca8e0
