### ISSUE TITLE
 可不可以在所有非目标语言的文本，悬停显示译文。 尤其很多时候，我们不需要将整个网页都翻译成为目标语言，只希望自己看不懂的文本，能够悬停显示译文。自己能够做一个参考。目前的扩展逻辑是想要悬停显示译文，必须一个网页一个网页的添加才可以。这个操作逻辑不太合理。

### ISSUE THREAD

**Issue by kethoven** [FilipePS/Traduzir-paginas-web#123]
可不可以在所有非目标语言的文本，悬停显示译文。
尤其很多时候，我们不需要将整个网页都翻译成为目标语言，只希望自己看不懂的文本，能够悬停显示译文。自己能够做一个参考。目前的扩展逻辑是想要悬停显示译文，必须一个网页一个网页的添加才可以。这个操作逻辑不太合理。

**Comment by haiwx** [comment]
Translation：

Add options to 'Show translated text when hovering' for all non-target language page.

**Comment by FilipePS** [comment]
In all languages I do not intend to add. However, it was already added the option "Show translation when hovering on sites in *", where * is the language of the page. With this feature all sites with this language will be translated when hovering.
