### ISSUE TITLE
Doesnt translate to other english (English>Portuguese) in double-click

### ISSUE THREAD

**Issue by CodingNix** [FilipePS/Traduzir-paginas-web#124]
Hi, i use this add for a long time but after the lasts actualizations i cant translate english texts to Portuguese without translate all the page. This was a very useful function.

**Comment by CodingNix** [comment]
"Fixed": U need to put all the 3 languages the same.

**Comment by FilipePS** [comment]
Are you talking about translating the selected text or translating when hovering?

**Comment by FilipePS** [comment]
> 
> 
> "Fixed": U need to put all the 3 languages the same.

If the 3 target languages are different, does the button appear in the latest version of the extension?
