### ISSUE TITLE
The color of the add-on icon if the page is translated.

### ISSUE THREAD

**Issue by oleg-sgh** [FilipePS/Traduzir-paginas-web#127]
Здравствуйте.
Значок в адресной строке меняет цвет, если страница переведена.
Можно сделать, чтобы сам значок дополнения тоже менял цвет, когда страница переведена?
-------------
Google Translate:
Hello.
The icon in the address bar changes color if the page is translated.
Can you make the add-on icon itself change color when the page is translated?
-----------
Add 15.03.21
Yandex translation does not work.

**Comment by FilipePS** [comment]
I fix this problem with Yandex.
About the icon, are you talking about the icon on the toolbar?

**Comment by oleg-sgh** [comment]
> About the icon, are you talking about the icon on the toolbar?
------------------
Yes.

**Comment by Vingolf** [comment]
> I fix this problem with Yandex.

 @FilipePS consider to add [deepl](https://www.deepl.com/translator) as a translation service, as suggested in your [reviews](https://addons.mozilla.org/de/firefox/addon/traduzir-paginas-web/reviews/1654619/)

**Comment by Vingolf** [comment]
> Здравствуйте.
> Значок в адресной строке меняет цвет, если страница переведена.
> Можно сделать, чтобы сам значок дополнения тоже менял цвет, когда страница переведена?

Deepl translation (English (GB))
**Can I make** the add-on icon itself change **colour** when the page is translated as well?

(I want to mention, that there are some differences in spelling and grammar between google and deepl)

Consider the case when a site is translated automatically  into my native language (as some support sites are).
If I use the addon to translate the site back to english, has the page been translated or not?

**Comment by FilipePS** [comment]
> consider to add deepl as a translation service, as suggested in your reviews
There is a small difficulty in adding Deepl.
Deepl does not support text in HTML format, this greatly impairs the quality of the page translation. Install the _Page translator_  extension, it translates using google but ignores HTML formatting.


> Consider the case when a site is translated automatically into my native language (as some support sites are).
> If I use the addon to translate the site back to english, has the page been translated or not?

When you click on "Original" the texts on the page are restored, no translation is done.
