### ISSUE TITLE
Feature Request: "Traslate this [Whole Domain] or [exact URL/Page] to [Language] on every visit? [ ]"

### ISSUE THREAD

**Issue by TeddAndersen** [FilipePS/Traduzir-paginas-web#13]
Feature request:

"Traslate this [Whole Domain] or [exact URL/Page] to [Language] on every
visit? [ ]"
(Domain or exact URL to a given language)

Example if i wanted www.strangesite.xyz to be traslated to NORWEGAIN at
every visit to that page/domain regardles of current encoding ? And
leave other pages with same language original and untranslated...

This way it can be "Set and Forget" config for that
url/page/domain...regadles of what the site reports as it's language.

Can make it more usefull for some... like me :) as i visit many sites in
lets say Japan... but like to select withch pages to translate... not
just ALL JAPANESE PAGES... Somtimes it part of the design of the page one
might want to see in it's original form :)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/11983f3edd6b4ac5c00c3aaea52aaf77ff43098f

**Comment by TeddAndersen** [comment]
Okey.... Think you misunderstod this... but i tried :)

An option to translate based on the specific site or exacte url only.....

If site = www.sitename.net { translate every page on www.sitename.net to LANGUAGE }
if url == www.othersite.org/page/somewhere/index.htm { translate this url only to LANGUAGE and leave rest of site UNtranslated }

You got an option to "Never translate this site"... What i was thinking of was kind "ALWAYS translate this ite" or "Always translate this url" 

As not all sites declare the language so its detectable... but nevermind :)

**Comment by TeddAndersen** [comment]
The logic could be somting like this...

Visit a site,
detect the current sitename and url,
look site/url up in a list the user have added sites and url's to translate,
if found translate site to given language... ?

An option for the user to add current site or complete url to list...

... will download and look at your code.... :)

**Comment by TeddAndersen** [comment]
Nevermind you have it..... i dident see the last submit :)

Sorry and good job.....Tip inncomming :)
