### ISSUE TITLE
Bing Translation Engine & Keyboard Shortcuts

### ISSUE THREAD

**Issue by dtantono** [FilipePS/Traduzir-paginas-web#130]
Hi
I find this addon is quite good. But, I have few remarks and problems:
1. I saw we can pick yandex or Google translation engine for this addon. Is it possible to add Bing engine as well?
2. I try the current keyboard shortcut Alt + T. but, the shortcut does not work. Is it a bug?
3. Is there any possibility for the user to customise the keyboard shortcut for full webpage translation?
Please advise

**Comment by FilipePS** [comment]
>     1. I saw we can pick yandex or Google translation engine for this addon. Is it possible to add Bing engine as well?

For page translation only Google or Yandex. However, in the future I plan on adding more translation services for text translation.

>     2. I try the current keyboard shortcut Alt + T. but, the shortcut does not work. Is it a bug?
>     3. Is there any possibility for the user to customise the keyboard shortcut for full webpage translation?

This is incompatible with some extension you have installed.
To resolve, follow these steps:
1 - Access the firefox addon manager *about:addons*.
2 - Click on the settings gear.
3 - Click on *Manage extension shortcuts*.
4 - Solve the conflict of keyboard shortcuts.

**Comment by dtantono** [comment]
Hi
I use Firefox Windows 10 and the solution works. But, the default setting Alt +T does not work and I have to change the keyboard shortcut manually.  So, I hope the problem will be resolved soon

**Comment by FilipePS** [comment]
> I saw we can pick yandex or Google translation engine for this addon. Is it possible to add Bing engine as well?

Bing Translator has been implemented as a text-only translation service. It will be available in the next version of the extension.

> I try the current keyboard shortcut Alt + T. but, the shortcut does not work. Is it a bug?

This issue is related to keyboard layout.

> Is there any possibility for the user to customise the keyboard shortcut for full webpage translation?

This option has already been added

**Comment by dtantono** [comment]
Hi, I saw Bing is available for Text Translation Service. Is it possible for page translation service as well?
