### ISSUE TITLE
Colour change icon indicator doesn't work in any theme other than default theme

### ISSUE THREAD

**Issue by AndreiMiculita** [FilipePS/Traduzir-paginas-web#134]
The color change (from #88) unfortunately only works with the default theme. Nothing happens in the light and dark themes, for example.

To reproduce, translate a page, click
![image](https://user-images.githubusercontent.com/6352172/112553248-6efb4700-8dc4-11eb-98a9-4ae50556a04c.png)
then "Customize toolbar...", click "Themes" at the bottom and select any theme other than the default theme.

**Comment by FilipePS** [comment]
The problem with changing the color of the icon when using themes is that the blue color may not match certain themes.
For example a red theme and the blue icon would look strange. In blue themes, perhaps the icon may disappear.
So I turned this on for the default theme only.

I'm still not sure how best to activate this on all themes.

**Comment by AndreiMiculita** [comment]
I understand why you're hesitant to do that. 

If it helps, other indicators (such as the examples gave in #88) don't depend on the theme. In particular, the "Reader mode" indicator, which I assume is implemented by Mozilla themselves, always uses the same shade of blue (#45a1ff), no matter the theme. As well as the bookmark star. So as of now, I don't think there's a way to use a color defined by the theme.

Here's an example with a random theme:
![image](https://user-images.githubusercontent.com/6352172/112559908-4417ef80-8dd2-11eb-9915-960f55eb6bef.png)
And also the "Downloads" button:
![image](https://user-images.githubusercontent.com/6352172/112560111-c0aace00-8dd2-11eb-94a6-702eaf505e82.png)

**Comment by FilipePS** [comment]
What is the name of this theme?
Was the icon supposed to be yellow?

**Comment by AndreiMiculita** [comment]
It's just a [random theme](https://addons.mozilla.org/en-US/firefox/addon/joyful-jungle-team/) I picked to show that the blue color does not depend on the theme.

This also works with any other theme (e.g. Light, Dark, Alpenglow - which you see in about:welcome). These icons always show up as blue. So it was not supposed to be yellow.

**Comment by FilipePS** [comment]
I set the color to _#45a1ff_ regardless of theme

**Comment by candrapersada** [comment]
why the translate icon uses the letter G? 
![gambar](https://user-images.githubusercontent.com/36833664/114267624-05677380-9a27-11eb-8db2-036e87576056.png)

**Comment by FilipePS** [comment]
> why the translate icon uses the letter G? 
> ![gambar](https://user-images.githubusercontent.com/36833664/114267624-05677380-9a27-11eb-8db2-036e87576056.png)
> 

It’s simply a Google Translate icon

**Comment by candrapersada** [comment]
will the letter G be replaced in the future? #130

**Comment by FilipePS** [comment]
> will the letter G be replaced in the future? #130

I don't see much reason to use an icon with another letter.  Did you ask that with the intention of suggesting bing as a translation service?

**Comment by candrapersada** [comment]
> For page translation only Google or Yandex. However, in the future I plan on adding more translation services for text translation.

what I mean is to replace the letter G because in the future there is a plan on adding more translation services for text translation.
![image](https://user-images.githubusercontent.com/36833664/114283631-e099ed00-9a74-11eb-952a-f111e2e5e835.png)
![image](https://user-images.githubusercontent.com/36833664/114283645-f6a7ad80-9a74-11eb-9f76-f2b32c7ed1e0.png)
![image](https://user-images.githubusercontent.com/36833664/114283678-1d65e400-9a75-11eb-9dd1-4238689b1cc8.png)
