### ISSUE TITLE
Number translation error

### ISSUE THREAD

**Issue by laszlodrgero** [FilipePS/Traduzir-paginas-web#135]
**Number translation error:**

[https://www.headphonesty.com/2020/08/review-mangird-tea/](url)

translated:

![2021-03-27_053821](https://user-images.githubusercontent.com/70061393/112710290-350f6b00-8ec0-11eb-8e39-6f77e710ff3e.jpg)

Original: 

![2021-03-27_053748](https://user-images.githubusercontent.com/70061393/112710291-36409800-8ec0-11eb-8af9-57f0413f4fc0.jpg)

**Comment by FilipePS** [comment]
What is your target language?

**Comment by laszlodrgero** [comment]
Hungarian

**Comment by FilipePS** [comment]
If you copy and paste this text into the Google translator you will see that the problem is repeated.
It’s a problem with Google’s translation, I don’t think I can solve it.

**Comment by laszlodrgero** [comment]
Thank you for answer.
