### ISSUE TITLE
Translate selected text on addons.mozilla.org

### ISSUE THREAD

**Issue by FilipePS** [FilipePS/Traduzir-paginas-web#136]
I want to emphasize that the addon of @FilipePS is very helpful and it improves with every update.👍

When I became aware of this issue (# 104), I had to translate the text, 
since I do not understand portuguese. I did this with your addon for sure. 😃

> avaliação antiga :
> https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/reviews/1647596/

Following this link to addons.mozilla.org the addon does not work anymore. 
I am aware that this is a restriction of the firefox api.

My solution to translate the text was to copy the text from addons.mozilla.org
 and paste it into a window on deepl.com.

I wonder if the restrictions for addons allow translating a text in a popup window or in the sidebar? 🤔

_Originalmente postado por @Vingolf em https://github.com/FilipePS/Traduzir-paginas-web/issues/104#issuecomment-808798697_

**Comment by FilipePS** [comment]
@Vingolf I've seen an addon do something like that.
I do not intend to have the selected text open in a new tab.
But there is certainly a way to make the popup in the address bar appear with the translation result.
I plan to implement this soon.

Is there really a problem with translating on Google docs?
I did some tests and didn't notice this problem.

**Comment by oleg-sgh** [comment]
> Translate selected text on addons.mozilla.org

about:config
privacy.resistFingerprinting.block_mozAddonManager;true
extensions.webextensions.restrictedDomains;""

**Comment by Vingolf** [comment]
> But there is certainly a way to make the popup in the address bar appear with the translation result.
> I plan to implement this soon.

O.k. 🤓
> Is there really a problem with translating on Google docs?
> I did some tests and didn't notice this problem.

I can neither confirm nor deny problems with translating on Google docs.
I referred to the language of the issue (# 104) not to the issue itself 🙄

**Comment by FilipePS** [comment]
This feature is already implemented in [version 8.9](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v8.9)
