### ISSUE TITLE
What do the three target languages of the new version mean

### ISSUE THREAD

**Issue by mithew** [FilipePS/Traduzir-paginas-web#137]
Generally, only one target language is needed, and the redundant one cannot be deleted, which affects the daily use

**Comment by FilipePS** [comment]
Using the "More" and "Less" buttons you can control the amount of things that appear on the interface.
And with the button ![btn](https://user-images.githubusercontent.com/54990796/112777816-7e270280-9019-11eb-9e93-9c1bed684ad2.png) you can use the old interface.
