### ISSUE TITLE
March 31st pop-up translation not working anymore

### ISSUE THREAD

**Issue by t00gee** [FilipePS/Traduzir-paginas-web#138]
Since the yesterday update when I select a word in a page and I press 'translate selected text' the pop-up opened in the Address Bar is not displayed correctly: it does not keep the dark mode, does not show the translation and it shows different languages from the ones that I selected in the settings. 
![sshot-2](https://user-images.githubusercontent.com/81743043/113264397-36cb9b00-92d3-11eb-9e96-fe6cc04d7a1c.png)

**Comment by Noodles-321** [comment]
Exactly the same problem. Even the same displayed UI.🤣
![Snipaste_2021-04-01_23-28-24](https://user-images.githubusercontent.com/37469405/113317624-1edf3000-9342-11eb-86aa-b17c74f392c5.png)

**Comment by XI64** [comment]
Exact issue here as well.

**Comment by FilipePS** [comment]
This is a problem that occurred with everyone who uses dark mode. And it has already been resolved.

The reason for the translation of the selected text to be done by the popup in the address bar, is to allow the translation of the selected text when using reading mode, or on sites like "addons.mozilla.org" where there are several limitations .
