### ISSUE TITLE
Show translated text when hovering over sites with all languages and all sites

### ISSUE THREAD

**Issue by candrapersada** [FilipePS/Traduzir-paginas-web#139]
how to activate. Show translated text when hovering over sites with all languages and all sites?
![gambar](https://user-images.githubusercontent.com/36833664/113547590-6a326080-9618-11eb-9861-660dc44f67e6.png)
![gambar](https://user-images.githubusercontent.com/36833664/113547642-88985c00-9618-11eb-980b-de696d687afa.png)

**Comment by FilipePS** [comment]
There is currently no way to do this, and I don't intend to add this.

When I launched this feature, it was enabled by default on all sites. So I was alerted to the privacy issues that this creates.

You do not need to manually add languages or sites to this list, in the translate popup there is a checkbox to activate this for the site you are visiting.

**Comment by candrapersada** [comment]
> You do not need to manually add languages or sites to this list, in the translate popup there is a checkbox to activate this for the site you are visiting.

but in ![btn](https://user-images.githubusercontent.com/54990796/112777816-7e270280-9019-11eb-9e93-9c1bed684ad2.png) the old interface there was no checkbox to enable this for the sites you visit.
![image](https://user-images.githubusercontent.com/36833664/113631852-46146500-9694-11eb-8ded-fdcc5126bacd.png)

**Comment by FilipePS** [comment]
Currently using the old popup you have these options.
