### ISSUE TITLE
How to prevent translation of <title>?

### ISSUE THREAD

**Issue by azu** [FilipePS/Traduzir-paginas-web#147]
I want to prevent translation for `<title>`  element.
But, this extension always translates `<title>`'s text content.

Env:

- Firefox 88.0 
- Extension version: 8.9.3
- Language: Japanese

Reproduce Steps:

1. Install this extension
2. Visit https://github.com/FilipePS/Traduzir-paginas-web/issues
2. Click popup icon
3. Select translation language

As a result, this extension translated `<title>`.

![image](https://user-images.githubusercontent.com/19714/116494886-c2d5e000-a8dc-11eb-93ad-ff326a81543f.png)

`tranlate` attribute and `notranslate` class that is under the document.body seems to works.
https://output.jsbin.com/pitelunayo
But, `<title translate="no">` does not work.

![image](https://user-images.githubusercontent.com/19714/116495129-47c0f980-a8dd-11eb-80dc-6ed84f174a37.png)

Context:

Sharing features like Twitter button refers to `document.title`.
I do not want to share the translated title.

**Comment by azu** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/blob/b78f87ad0b9568e85335f247ad5e55418062e284/contentScript/pageTranslator.js#L356-L366

`translatePageTitle` seems that does not check `translate` attribute.

I've added the following checks and It works as expected.

```diff
    function translatePageTitle() {
+       const title = document.querySelector("title");
+       if(title && (
+          title.classList.contains("notranslate") ||
+          title.getAttribute("translate") === "no"
+      )){
            return;
        }
        if (document.title.trim().length < 1) return;
        originalPageTitle = document.title

        backgroundTranslateSingleText(currentPageTranslatorService, currentTargetLanguage, originalPageTitle)
            .then(result => {
                if (result) {
                    document.title = result
                }
            })
    }
```

**Comment by FilipePS** [comment]
In addition to translating the text of html elements, the extension also translates some attributes such as:

- placeholder
- alt
- title
- and _value_ if the element is an _input_ with type _submit_

Do you think it is important to do this check before translating these attributes as well?

**Comment by FilipePS** [comment]
[Version 9.0](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.0) has already been released with these features

**Comment by azu** [comment]
Thanks!
