### ISSUE TITLE
Settings - Languages

### ISSUE THREAD

**Issue by 1LUC1D4710N** [FilipePS/Traduzir-paginas-web#149]
Why do you have three options?

Why can't it by only two?
1: From: Detect language.
2: To: Translate to.......

It would be so
![Screenshot_20210502-212039](https://user-images.githubusercontent.com/7138247/116823317-6a2c6e80-ab8c-11eb-8904-6970f350f5d1.png)
 much easier. I hate the fact that it does not comprehend to what you want it translate it to. It suddenly shows something else!!!!

**Comment by FilipePS** [comment]
Some people speak more than 1 language and like to have a quick way to translate into other languages.

I don't understand, why not just ignore the other buttons?
Or use the "Less" to hide parts of the interface.

> It would be do much easier. I hate the fact that it does not comprehend to what you want it translate it to. It suddenly shows something else!!!!

What do you mean what is happening?

**Comment by 1LUC1D4710N** [comment]
I get some people use more than one language, but again, it would just be easier to only have 'From' and 'To' hence two settings that would do every time, and not showing the alternatives. I always have to correct it and besides I don't find anything about your suggestion of 'less'.

**Comment by 1LUC1D4710N** [comment]
Just an thought for improvement? That way you don't have to correct it all the time 🤓👍🏼😜📲

**Comment by FilipePS** [comment]
You use the extension only on your cell phone right?
This "Less" button only appears on the desktop.

I checked the mobile version and discovered a bug that prevented changing the target language via the popup. https://github.com/FilipePS/Translate-paginas-web/commit/76f6d172978010bad4e428932aa89f96eda1db28

**Comment by 1LUC1D4710N** [comment]
Yes, the extension is on cell phone.

I did notice on Desktop the language bars/tabs have options and here it stays on the chosen one.

-But not on the cell phone extension. It does not show up or remember the chosen setting.
![Uploading IMG_20210502_215924~2.jpg…]()

**Comment by FilipePS** [comment]
The bug in which the target language preference is not saved has already been resolved. Do you have any more problems?

**Comment by 1LUC1D4710N** [comment]
Hi,

Yes, I think I have noticed update on desktop recently.

So, here we are. I removed and added the extension on mobile.
I learned new translation text DeepL is added, nice! Spotted that myself
couple of months ago.
So, that is set to that.

I see configuration/settings: 'storage' now? I don't think I saw that
before?

Basically, it is translating into the first languages setting and can
switch back to original, now.
Without ever have to correct it.

But like you said, option to use 'More'/'Less' expansion is not visible on
mobile edition but visible on desktop edition.

Final answer, yes, it is working. Just have to manual change it if you need
different language by three for settings 'change languages'.

**Comment by FilipePS** [comment]
On the mobile 3 target languages are used to translate selected text.
Among those 3 target language options, to translate the page on the cell phone, the first one will be used.
Remembering that you don't need to access the settings to change the target language, just click on "Change Languages".
