### ISSUE TITLE
[Feature Request] Add dark mode option

### ISSUE THREAD

**Issue by Bulogan** [FilipePS/Traduzir-paginas-web#15]
Really good extension and it only need dark mode to be perfect.
![image](https://user-images.githubusercontent.com/69257763/89729876-5aa04f00-da6c-11ea-83ce-5ff23677666b.png)

**Comment by atomGit** [comment]
how does one enable the dark theme in 7.1?

if it's supposed to be automatically enabled based on the browser theme, that's not working for me

**Comment by FilipePS** [comment]
Are you using Firefox Mobile? I still haven't done a dark theme for Popup mobile yet.
If you are using Firefox Desktop, the dark theme is activated by changing a setting in windows 10 that enables the dark theme for apps. I don't know if Firefox has any settings on that.

**Comment by atomGit** [comment]
i use Firefox desktop on Linux, but regardless, i believe there's an API so that an add-on can know whether the user has enabled the dark UI theme - this may help you to be more consistent across platforms instead of relying on a Windows setting

**Comment by FilipePS** [comment]
The only thing I basically did is this.
`@media (prefers-color-scheme: dark) {
 // styles for dark mode here
}`
So when the browser is in dark mode the extension should also be due to this property of CSS.

**Comment by atomGit** [comment]
hmmm - well, for whatever reason, the styles aren't loading for me - this is no big deal so if you want to ignore this that's totally fine with me

**Comment by FilipePS** [comment]
I'm going to add an option to switch the dark mode manually.
