### ISSUE TITLE
Some questions about privacy

### ISSUE THREAD

**Issue by LWiiiiii** [FilipePS/Traduzir-paginas-web#152]
The Google Translate webpage on chrome will detect that the webpage is in English on the device side, and then let me click Translate to English. If I do not click, it will not be sent to the server for translation. Is this extension also based on this mechanism? I hope to send the text to Google for translation after I choose to click Translate to English. And if I use this extension on Vivaldi, it should be the same mechanism, right? Otherwise, privacy will be a problem. Thanks again for your expansion!

**Comment by FilipePS** [comment]
The detection of the text language is done using this function [i18n.detecLanguage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage)
This function works offline and is not supported by Firefox mobile.

So in desktop browsers, detection has always been done offline.

In Firefox Mobile before version 8.0 of the extension, small pieces of text from the page were sent to the Google translator. This was described in the extension's privacy policy.
As of version 8.0, in Firefox mobile, I decided to use only the "lang" attribute of the "html" tag on the page. Several sites erroneously define this attribute, which makes the extension request to translate on the wrong sites.

Then texts will only be sent to servers when:

- You translate selected text
- You enable translation when hovering (basically if you hold the mouse cursor for just over 1 second on a part of the page, the text will be sent)
- As you click to translate the page (texts will be sent as you scroll through the page, note that hidden texts can also be sent) 
- If you set to always translate this site, or always translate this language, when you access a page, it may be that the extension starts sending the texts. There is a chance that the extension will incorrectly detect the language of the page, and translate a page that is a language that you would not like to translate.

**Comment by LWiiiiii** [comment]
thanks a lot
