### ISSUE TITLE
Some feature requests (translate after page navigation, translate entire page, improve UI localization)

### ISSUE THREAD

**Issue by AlCooo** [FilipePS/Traduzir-paginas-web#157]
[Translate even after moving pages]
I hate having to press the translate button again after navigating to another page (clicking a link, being redirected, etc.).
It would be nice to have an option to keep it translated even if the user navigates to another page.

[Translate the entire page]
The current behavior of "translate only what the user is looking at" requires the user to wait for translation each time they scroll. Also, I think it's a stressful behavior that the layout changes each time the user scrolls.
Therefore, it would be nice to have the option to translate the entire page, not just the visible range.

[Improve UI localization]
The order of words is different in some languages ​​such as Japanese. Therefore, there are some parts of the UI of this extension that cannot be localized naturally.
For example, the "Translate to LANGUAGE" button is naturally translated as "LANGUAGEに翻訳" in Japanese (LANGUAGE comes first). However, the current extension localization can only change "Translate to". I translated it as "以下に翻訳: LANGUAGE" ("Translate to this language: LANGUAGE"), but this is not a natural expression.
Being able to change the order of the words when localizing will result in a more natural UI translation.

**Comment by FilipePS** [comment]
- Imagine that you are accessing *de.wikipedia.org*, then you click on a link to another domain like *youtube.com*. Do you think that youtube should be translated, or just links from the same domain that you had translated?
- This behavior allows that when you click to translate you see the translation more quickly, translating the whole page at once takes longer. This is because translating the page all at once creates a certain overhead for translation services. So I don't have a feature like that in mind.
But I can think of maybe increasing the "borders", basically if you are reading and scrolling the page, the extension translates some text that are down, so when you scroll and get to them, these texts have already been translated.
- I will think of the best way to do this yet.

**Comment by AlCooo** [comment]
- I don't know exactly because I haven't actually used it, but I think it's better not to keep the translation in another domain (in this case, don't translate YouTube).
However, the appropriate behavior may vary depending on the use case, so I think it's ideal to be able to select it as an option.

- I think it's a good idea to increase the borders. However, even so, it is inevitable that users will encounter latency and layout changes when scrolling rapidly or scrolling upwards.
If the only disadvantage of translating the entire page is slowdown, I would suggest creating an option for those who value scrolling comfort and layout stability over the initial translation speed.
Also, I sometimes encounter a problem that a part of the page is not translated. This happens randomly and can be fixed by reloading, so I'm not sure why, but I suspect this may be related to behavior of translating only what the user is looking at.

- Most software will use placeholders in such cases. (Example: Localization of AdGuard, hosted on Crowdin.)

**Comment by FilipePS** [comment]
> [Improve UI localization]

It has already been implemented, check the crowdin.

**Comment by AlCooo** [comment]
Thank you!
I submitted a translation.

**Comment by FilipePS** [comment]
> [Translate even after moving pages]

This feature will be in the next version. You will need to activate it manually in the settings.

> [Translate the entire page]

Maybe in the future. I will close this issue, if you still want this resource, create a new issue with this request only.

**Comment by AlCooo** [comment]
> This feature will be in the next version. You will need to activate it manually in the settings.

Thank you for implementing it!
However, when I test it, sometimes it doesn't work. This is my environment.
Add-on version: latest source code (commit ea4fa50)
Browser: Firefox Nightly 91.0a1 (2021-06-26) Clean profile, no other add-ons

I can reproduce the bug with the following steps:
1. Open https://mcforge.readthedocs.io/en/latest/
2. Translate the page.
3. In the menu on the left, click "Style Guide" to go to that page. This page will be translated automatically.
4. Expand "Getting started" in the left menu and go to "Home" in it.
5. When "Home" is loaded, the page is not translated automatically.

> Maybe in the future. I will close this issue, if you still want this resource, create a new issue with this request only.

understood.

**Comment by FilipePS** [comment]
Bug fixed https://github.com/FilipePS/Traduzir-paginas-web/commit/e149a780c126629f2e7845f9d5fef0829585a539

**Comment by AlCooo** [comment]
The latest version works fine. Thank you!

**Comment by FilipePS** [comment]
As of version 9.2, the `webNavigation` permission is optional. So if you use the `Automatically translate when clicking on a link that takes you to the same domain as the current site` option, enable it again.

**Comment by AlCooo** [comment]
understood.
Thank you for ensuring that the extension uses the minimum permissions.
