### ISSUE TITLE
Problems with Translate Web Pages Add-on

### ISSUE THREAD

**Issue by SamTheDoggie** [FilipePS/Traduzir-paginas-web#16]
Mac OS 10.15; Firefox 79, Translate Web Pages ver 6.8

1.  Options-->Automatically translate these languages

How do I add a language?  When I click the downward arrow, I see only
"You have not added any languages to this list."  No list of languages appears.

2.  Context menu just takes me to
<translate.google.com...> and nothing gets translated.  Also, "Show the
option to translate the page in the context menu" is on "No," but the
option still appears.

3.  I select Yandex, but the add-on still uses Google (Google is OK, I just wanted to compare results).

Thank you.

**Comment by FilipePS** [comment]
1 - When you open the site, click on the extension popup, check the box "Always translate from [LANG]" and click on translate. This language is automatically translated and will appear in this list. If you are using a mobile device, you will not be able to use this feature.

2 - The button in the context menu is just a shortcut to basically click "Translate" in the popup. I can't imagine how the Google Translate page can be opened. Aren't you confusing it with the "Open in google translator" button?

3 - After changing the translation engine, the page must be reloaded. You can change the translation engine by clicking on the Google Translate icon in the popup as well.

Finally are you using the latest version of the extension? reinstall the extension and see if any problems prevail.

**Comment by SamTheDoggie** [comment]
On 8/9/20 12:40 PM, FilipePS wrote:
> 1 - When you open the site, click on the extension popup, check the box 
> "Always translate from [LANG]" and click on translate. This language is 
> automatically translated and will appear in this list.

I'm not sure what you mean by "popup."  I go to a foreign language web 
site.  Then, I click on the extension icon in the upper-right of the 
Toolbar.  Then I choose Options.  I do not see "Always translate from 
[LANG]."  Please see Screen Shot-1

If I choose "Translate" from the Toolbar icon, the site is properly 
translated.

> 2 - The button in the context menu is just a shortcut to basically click 
> "Translate" in the popup. I can't imagine how the Google Translate page 
> can be opened. Aren't you confusing it with the "Open in google 
> translator" button?

Please see Screen Shot-2, then -3.  They show what happens when I use 
the Contextual Menu.  I haven't chosen  "Open in google translator," but 
I end up is at some strange Google site.  Nothing happens beyond that.

> Finally are you using the latest version of the extension? reinstall the 
> extension and see if any problems prevail.

I'm using ver 6.8.  I removed and re-installed, but no change.

Sorry to be a problem.
Thank you.

**Comment by FilipePS** [comment]
Could you provide screenshots or a video?

**Comment by SamTheDoggie** [comment]
![Screen Shot-1](https://user-images.githubusercontent.com/69423910/89738691-9aedd600-da48-11ea-8089-01e179a8c0e6.png)
![Screen Shot-2](https://user-images.githubusercontent.com/69423910/89738693-9cb79980-da48-11ea-9d7e-0cf00e98f7ad.png)
![Screen Shot-3](https://user-images.githubusercontent.com/69423910/89738697-9f19f380-da48-11ea-9fdf-0d253d9974de.png)

**Comment by FilipePS** [comment]
This button you clicked on the Context Menu does not belong to my extension. You can see by the icon that is different.
I'm finding it strange that some texts are not appearing in the extension's popup.
Perhaps the Mac version of Firefox has incompatibilities.
I don't have a Mac to test what's going on but maybe you can help me.
Go to "about: debugging", click "This Firefox", find my "Translate Web Pages" extension and click "Inspect".
Open the "Console" tab, now click the button for my extension on the toolbar.
Show me what are all the error messages that will appear.

**Comment by FilipePS** [comment]
And another thing, this google translator site will only work if you disable the NoScript extension.

**Comment by SamTheDoggie** [comment]
Well, that's weird.  I don't know where that Translate This Page came from..

OK, here is the Console Output:

Uncaught TypeError: options is null
    fetchServices moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/services.js:72
    <anonymous> moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/services.js:198
services.js:72:12
Uncaught TypeError: options is null
    <anonymous> moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/background.js:295
background.js:295:22
localStorage is null background.js:90
unreachable code after return statement
ext_managment.js:469:4
unreachable code after return statement
ext_managment.js:490:4
unreachable code after return statement
2 ext_managment.js:509:4
Uncaught Error: Invalid storage engine: null
    setStorageEngine moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:909
    Visitor moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:886
    <anonymous> moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:1142
background.js:909:10
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). background.js:3759:15
Uncaught (in promise) TypeError: localStorage is null
    [20]</< moz-extension://00287bad-e3cc-b948-957d-9b29e0d3d078/public/js/background.js:16770
background.js:16770:3
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Uncaught (in promise) Error: Content script already unregistered undefined
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Uncaught (in promise) Error: Content script already unregistered undefined
Uncaught (in promise) Error: Content script already unregistered undefined
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 5 global.min.js:9378
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1399
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Unchecked lastError value: Error: sender.tab is undefined dnt.js:52
TypeError: can't convert undefined to object shared.js:52:185
Unchecked lastError value: Error: sender.tab is undefined fingerprinting.js:331
sendRemoveListener on closed conduit CanvasBlocker@kkapsner.de.274877907841 ConduitsChild.jsm:108
Promise resolved after context unloaded
settings.js:442
TypeError: context.contentWindow is null
ExtensionContent.jsm:612:28
TypeError: can't access dead object
2
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. popup.js:205
sendRemoveListener on closed conduit CanvasBlocker@kkapsner.de.274877907863 ConduitsChild.jsm:108
TypeError: can't convert undefined to object shared.js:52:185
Promise rejected after context unloaded: 
fingerprinting.js:331
Promise rejected after context unloaded: 
Messages.js:67
Promise rejected after context unloaded: 
dnt.js:52
Promise resolved after context unloaded
settings.js:442
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 397 popup.js:197
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378

**Comment by SamTheDoggie** [comment]
I discovered from where that other contextual menu item came from.  I also have installed "Simple Translate."  It's designed to be used for selected text, not entire web pages.  But, oddly, it installs a "Translate This Page" option.

**Comment by FilipePS** [comment]
I think you chose the wrong extension. I tried this url.
about:devtools-toolbox?type=extension&id=%7B036a55b4-5e72-4d05-a06c-cba2dfcc134a%7D

**Comment by SamTheDoggie** [comment]
Now I'm really confused.  Did I send the wrong Console output?

**Comment by FilipePS** [comment]
I think this output is from the CanvasBlocker extension.

**Comment by SamTheDoggie** [comment]
This is what I used

Extension ID
    {036a55b4-5e72-4d05-a06c-cba2dfcc134a}
Internal UUID
    40aecb98-c061-0842-af6f-85fca7f460ab
Manifest URL
    moz-extension://40aecb98-c061-0842-af6f-85fca7f460ab/manifest.json

I deleted the Console content and deleted Canvas Blocker.  Now I get:

TypeError: PrecompiledScript.executeInGlobal: Argument 1 is not an object. 6 ExtensionContent.jsm:567:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. popup.js:205
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. popup.js:197
TypeError: can't convert undefined to object shared.js:52:185
Promise rejected after context unloaded: 
Messages.js:67
Promise rejected after context unloaded: 
fingerprinting.js:331
Promise rejected after context unloaded: 
dnt.js:52
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 254 popup.js:197

​

**Comment by FilipePS** [comment]
Which language is your Firefox in?

**Comment by SamTheDoggie** [comment]
English.

⁣Get BlueMail for Android ​

**Comment by FilipePS** [comment]
Open this urls (about:devtools-toolbox?type=extension&id=%7B036a55b4-5e72-4d05-a06c-cba2dfcc134a%7D). Go to the console tab and let me know the error messages.

**Comment by SamTheDoggie** [comment]
I don't think any of this applies to your extension:

Uncaught TypeError: options is null
    fetchServices moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/services.js:72
    <anonymous> moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/services.js:198
services.js:72:12
Uncaught TypeError: options is null
    <anonymous> moz-extension://360e1871-3932-e54e-9c30-8b42bcd26bb9/scripts/background.js:295
background.js:295:22
unreachable code after return statement
ext_managment.js:469:4
unreachable code after return statement
ext_managment.js:490:4
unreachable code after return statement
ext_managment.js:509:4
localStorage is null background.js:90
unreachable code after return statement
ext_managment.js:509:4
Uncaught Error: Invalid storage engine: null
    setStorageEngine moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:909
    Visitor moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:886
    <anonymous> moz-extension://cf4303cb-be80-944a-b6b7-fe0ef5c384e1/js/background.js:1142
background.js:909:10
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). background.js:3759:15
Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Uncaught (in promise) TypeError: localStorage is null
    [20]</< moz-extension://00287bad-e3cc-b948-957d-9b29e0d3d078/public/js/background.js:16770
background.js:16770:3
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10393/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10394/. global.min.js:9378:5530
Firefox can’t establish a connection to the server at ws://127.0.0.1:10395/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

**Comment by SamTheDoggie** [comment]
I think you fixed it.  I found ver 7.0.

Thank you. I will donate.

**Comment by FilipePS** [comment]
I still don't understand this error.  I believe the problem is with your computer.  More than 2,000 people use the extension on Mac Os every day and have not reported a problem.
Has your Firefox been downloaded directly from the official website?  Did you change any settings in "about: config"?

**Comment by SamTheDoggie** [comment]
I always download Firefox by selecting "About Firefox" in the top menu.  It either reports that FF is up-to-date or it immediately updates.  I assume the update comes directly from Mozilla, but I have no way of knowing for certain.

I did change something with about:config:
Enable Redirect Tracking Protection in Firefox
https://www.ghacks.net/2020/08/06/how-to-enable-redirect-tracking-in-firefox/

Possible source of the error?

**Comment by FilipePS** [comment]
Follow these steps:

![img1](https://user-images.githubusercontent.com/54990796/90022850-687eeb80-dc89-11ea-939d-178cacfaa827.png)
![img2](https://user-images.githubusercontent.com/54990796/90022852-69178200-dc89-11ea-93b0-6cf5c027574a.png)
![img3](https://user-images.githubusercontent.com/54990796/90022848-67e65500-dc89-11ea-9267-ec4e055a4d20.png)
![img4](https://user-images.githubusercontent.com/54990796/90022842-661c9180-dc89-11ea-9ccc-307bf9924256.png)
![img5](https://user-images.githubusercontent.com/54990796/90022839-64eb6480-dc89-11ea-9ffe-bd00096df124.png)

And execute this command too and tell me the exit.
`browser.i18n.getUILanguage()`

![img6](https://user-images.githubusercontent.com/54990796/90023351-096da680-dc8a-11ea-81e4-feb42fd6a14a.png)

**Comment by FilipePS** [comment]
Follow these steps:

![img1](https://user-images.githubusercontent.com/54990796/90024026-ce1fa780-dc8a-11ea-977f-25d55c6e6ff9.png)
![img2](https://user-images.githubusercontent.com/54990796/90024017-ccee7a80-dc8a-11ea-9585-5b804d140947.png)
![img3](https://user-images.githubusercontent.com/54990796/90024014-cc55e400-dc8a-11ea-8150-a15975deb070.png)
![img4](https://user-images.githubusercontent.com/54990796/90024005-ca8c2080-dc8a-11ea-94d4-56c94948d359.png)
![img5](https://user-images.githubusercontent.com/54990796/90024004-c9f38a00-dc8a-11ea-89a4-5e1ca683fcd5.png)

And also run this command, and show me the output.
`browser.i18n.getUILanguage()`

![img6](https://user-images.githubusercontent.com/54990796/90023999-c8c25d00-dc8a-11ea-88ef-f1f8da3d1dcc.png)

**Comment by SamTheDoggie** [comment]
Hi,
I'm a little short on time at the moment.  I'll get to it soon.  I'm not sure what you mean by "run" this command.  Just enter it in the Console log?  Also, is this in response to the Redirect Tracking Protection?

**Comment by FilipePS** [comment]
The images show what you have to do.
And that setting does not affect the addon.

**Comment by SamTheDoggie** [comment]
Well, I'm sorry, I don't understand any of this (I am not a developer).  I tried pasting in the command "browser.i18n.getUILanguage()" and this was the result:

 "Scam Warning: Take care when pasting things you don’t understand. This could allow attackers to steal your identity or take control of your computer. Please type ‘allow pasting’ below (no need to press enter) to allow pasting.

Also, I'm still getting "Firefox can’t establish a connection to the server at ws://127.0.0.1:10391/. global.min.js:9378:5530
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. global.min.js:9378
Firefox can’t establish a connection to the server at ws://127.0.0.1:10392/.

**Comment by FilipePS** [comment]
Do other addons also have problems?  I suggest that you uninstall Firefox and install it again.

**Comment by SamTheDoggie** [comment]
I do not know whether other extensions have problems.  Most are just supposed to work in the background (block ads, for example).

Are you suggesting that I re-install only the application (doable), or that I remove both the application and my profile and start over (not doable; too much effort that probably will have no effect).

**Comment by FilipePS** [comment]
Do you still use the extension? Could you pass an email address to a private message?

**Comment by SamTheDoggie** [comment]
Sorry, I do not know what you mean by "Could you pass an email address to a private message?"  I have used the extension (now ver 7.1) only one or two times in the preceding three weeks.  I've checked it now as well.  It appears to function properly.  I'm using FF ver 80, Mac OS 10.15.

Thank you.

**Comment by FilipePS** [comment]
So the problem is gone?

**Comment by SamTheDoggie** [comment]
Yes, apparently the problem is gone.
