### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by mooms06** [FilipePS/Traduzir-paginas-web#161]
Hi, thank you for this extension

I would like to know if the history of the visited pages is systematically sent to Google, or only if we click on the translation button ?
How the automatic translation (if some language is detected) works ?

**Comment by FilipePS** [comment]
I think that answers your questions. https://github.com/FilipePS/Traduzir-paginas-web/issues/152

**Comment by mooms06** [comment]
Yes, thanks.
