### ISSUE TITLE
Keeps translating websites I explicetly marked as do not translate

### ISSUE THREAD

**Issue by pva** [FilipePS/Traduzir-paginas-web#162]
I've configured website as do not translate, but for some reason, this is the only site that extension forcibly translates whenever I switch to a tab with it. I've noticed similar reports in reviews, so probably this issue will be easy to reproduce.

**Comment by FilipePS** [comment]
Full page translation or translation when hovering?

**Comment by pva** [comment]
I found the reason for this behavior! Actually, the extension sets hotkey on Alt+1, and this is a hotkey to switch tabs in firefox. It's better to choose some different hotkeys for translation.

**Comment by FilipePS** [comment]
Depending on the browser language and keyboard layout, Firefox can define shortcut keys for specific users.
The `Alt + 1` hotkey is not used in my Firefox.
