### ISSUE TITLE
text wrapped by a tag like <b> make unnatural tranlation

### ISSUE THREAD

**Issue by azu** [FilipePS/Traduzir-paginas-web#163]
Example:
https://output.jsbin.com/pajorahagi/1

```html
<p>Simple Translate is created by <b>FilipePS</b></p>
<p>Simple Translate is created by FilipePS</p>
```

## Google Translation: English → Japanese

URL: https://translate.google.com/translate?sl=en&tl=ja&u=https://output.jsbin.com/vamezovite

Request:

```json
{
	"q": [
		"<a i=0>Simple Translate is created by </a><a i=1>FilipePS</a>",
		"Simple Translate is created by FilipePS"
	]
}
```
![image](https://user-images.githubusercontent.com/19714/118567853-81d13d00-b7b1-11eb-9960-aed93a51fa3e.png)
Response:

```json
[
	"<a i=1>SimpleTranslateはFilipePS</a><a i=0>によって作成され</a><a i=1>ます</a>",
	"SimpleTranslateはFilipePSによって作成されます"
]
```
![image](https://user-images.githubusercontent.com/19714/118569616-3de03700-b7b5-11eb-9ed2-6ea13fd60f8d.png)

Result:
![image](https://user-images.githubusercontent.com/19714/118567859-83026a00-b7b1-11eb-85c3-5256de9c91b8.png)

 it is a natural result, but the styling is buggy.

```
SimpleTranslateはFilipePSによって作成されます

SimpleTranslateはFilipePSによって作成されます
```

## Traduzir-paginas-web(Google Translation): English → Japanese

Request([sourceArray](https://github.com/FilipePS/Traduzir-paginas-web/blob/f3a4956a1aa96b7a9124864158a5200827694521/background/translationService.js#L386) value):

```js
[ "<pre><a i=0>Simple Translate is created by </a><a i=1>FilipePS</a></pre>", "<pre>Simple Translate is created by FilipePS</pre>" ]
```

Response([responseJson](https://github.com/FilipePS/Traduzir-paginas-web/blob/0cfe8de780d042f9556a3fce8ac4636eea5d6b8d/background/translationService.js#L241) value):

```json
[ "<pre><a i=1>SimpleTranslateはFilipePS</a><a i=0>によって作成され</a><a i=1>ます</a></pre>", "<pre>SimpleTranslateはFilipePSによって作成されます</pre>" ]
```

Result:

```
によって作成され SimpleTranslateはFilipePS ます // <= it is unnatural result

SimpleTranslateはFilipePSによって作成されます
```

Traduzir-paginas-web sort the result to `<a i=0><a i=1><a i=1>`. It make unnatural result.

`<pre><a i=1>SimpleTranslateはFilipePS</a><a i=0>によって作成され</a><a i=1>ます</a></pre>` look like natural in Japanese.

---

Google Translation and Traduzir-paginas-web have the same request and response but make different results.
Probably, some language like Japanese has a different order of grammar, so mapping translated text to original node make unnatural result.

https://github.com/FilipePS/Traduzir-paginas-web/blob/d89a4585d98d02260011b57a0cef962a9069f218/contentScript/pageTranslator.js#L309-L321

**Comment by Takwah** [comment]
same here.
original:
<img width="307" alt="CleanShot 2021-06-20 at 17 07 43@2x" src="https://user-images.githubusercontent.com/24718328/122668510-fe10d300-d1ea-11eb-98a8-8d09819f21c5.png">
Translate Web Pages:
<img width="338" alt="CleanShot 2021-06-20 at 17 11 01@2x" src="https://user-images.githubusercontent.com/24718328/122668535-20a2ec00-d1eb-11eb-9a23-f51a18f3f7b6.png">
Google Translate(Correct):
<img width="424" alt="CleanShot 2021-06-20 at 17 13 38@2x" src="https://user-images.githubusercontent.com/24718328/122668568-547e1180-d1eb-11eb-9a28-38b30cf69947.png">
