### ISSUE TITLE
Keyboard Shortcut for Full Webpage Translation is not working

### ISSUE THREAD

**Issue by dtantono** [FilipePS/Traduzir-paginas-web#166]
Hi
I use brave browser and usually I use alt + T as usual for full webpage translation. But, when I download the new source code to update the extension manually. The shortcut is gone. Is it a bug?
![2021-05-22_11-10](https://user-images.githubusercontent.com/29157187/119211622-4a82c900-baee-11eb-92c4-49a1fb3957f3.png)

**Comment by FilipePS** [comment]
I don't know which browser you are using, most certainly it isn't Firefox.
For browsers other than Firefox, this page for changing shortcut keys will not work. Use the browser's native feature to change the extension's shortcut keys.

**Comment by dtantono** [comment]
Hi, I use Microsoft Edge/Google Chrome and I use This extension (version 8.9.3) default keyboard shortcut (Alt +T). This shortcut always works properly. But, when I want to update this extension by following the instruction on the first page. This shortcut does not worked. Below is the screenshot for version 8.9.3 and what do you think?
<img width="906" alt="Screenshot_2021-05-25_22-23-21" src="https://user-images.githubusercontent.com/29157187/119505863-57324600-bda8-11eb-82bf-04805032fd37.png">

**Comment by FilipePS** [comment]
Change shortcut keys by this URL `edge://extensions/shortcuts`

**Comment by dtantono** [comment]
Yeah, you are right the Firefox version have an option to translate webpage. But, the crx one does not have it. Can you fix this discrepancy?
![2021-07-15_08-05](https://user-images.githubusercontent.com/29157187/125704081-061685c4-68e3-47f7-a184-89236eeb95f0.png)
![2021-07-15_08-06](https://user-images.githubusercontent.com/29157187/125704089-967c1a3f-5203-4d12-887b-3021a38fc731.png)

**Comment by FilipePS** [comment]
Simply set a shortcut key for `Switch between the translated and the original page`.

**Comment by dtantono** [comment]
I try to set a specific shortcut like ctrl + alt + t on the menu Switch between the translated and the original page via chrome-extension://bolggfoncklhniejomgplkjcllmnonbh/options/options.html#hotkeys or brave://extensions/shortcuts. But, it does not work. Is it a bug?

**Comment by FilipePS** [comment]
Chromium-based browsers do not support `Ctrl+Alt`

**Comment by dtantono** [comment]
I tried with the combination of Alt + T or ALT + C or at least ALT with one word combination. But, it does not work. What do you think?

**Comment by FilipePS** [comment]
Do you click on the pencil icon to be able to edit the shortcut key?

**Comment by dtantono** [comment]
Yeah, it works. But, I am curious why the menu on the crx file is different with firefox counterpart?

**Comment by FilipePS** [comment]
> 
> 
> Yeah, it works. But, I am curious why the menu on the crx file is different with firefox counterpart?

I did not understand what you said

**Comment by dtantono** [comment]
I mean the UI for Firefox and chrome is totally different
<img width="668" alt="Screenshot_2021-07-18_08-57-10" src="https://user-images.githubusercontent.com/29157187/126051835-e0ad9bdd-9015-4cdb-b5c7-07b4de9dc7df.png">
<img width="664" alt="Screenshot_2021-07-18_08-57-04" src="https://user-images.githubusercontent.com/29157187/126051837-f4c6fc7f-e4e8-4627-ad8f-d5ed8062f9cc.png">

**Comment by FilipePS** [comment]
Chromium-based browsers only allow up to 3 shortcut keys.
