### ISSUE TITLE
Translation in reader mode doesn't work

### ISSUE THREAD

**Issue by LuigiImVector** [FilipePS/Traduzir-paginas-web#169]
I've noticed that when I switch to reader mode, none of the extension's components works anymore, neither the full translation or the partial translation of a paragraph by hovering the mouse over it.

![2021-05-26-19-48-23](https://user-images.githubusercontent.com/59611597/119707635-a7b6ab80-be5b-11eb-8825-05336d5dd36a.gif)

**Comment by FilipePS** [comment]
Extensions don't have access to pages in read mode, so these features don't work.
Alternatively you can translate the page before entering read mode.
If you want to translate the selected text use the button in the context menu.
Maybe in the future I'll add an internal read mode to the extension. This way it would be possible to translate.
