### ISSUE TITLE
还是把图标放回到地址栏里吧

### ISSUE THREAD

**Issue by aunsen** [FilipePS/Traduzir-paginas-web#17]
而且现在github页面也不能翻译了

**Comment by Jacosci** [comment]
+1 For moving the button back to URL bar. IMO it's aesthetically better and just feels natural to use for those who are used to Chrome translate feature.

**Comment by FilipePS** [comment]
Is the addon not translating GitHub? for me it is translating normally.
And I'm going to put it back in the address bar. However, the icon on the toolbar will continue. Firefox does not allow extensions to hide icons from the toolbar.
The reason now to have an icon in the toolbar is to add a feature requested a long time ago for Firefox Mobile. The icon in the toolbar will show the option "Translate this site" in the Firefox Mobile menu.
Although in the next version it will have 2 icons, in the address bar and toolbar. You can manually hide them.

**Comment by FilipePS** [comment]
The button on the toolbar also makes the extension more compatible with other browsers.

**Comment by Jacosci** [comment]
> 
> 
> The button on the toolbar also makes the extension more compatible with other browsers.

I understand that Chromium based browsers don't allow extension's icon/button to be placed inside URL bar. But take a look at "Reddit Enhancement Suite" extension for example. Its "Subreddit Style" button is placed inside URL bar on Firefox while on Chromium browsers it uses toolbar button.

All in all, it's off course up to you to chose the best approach. It's nothing major and people can live with it either way. But I'd be happy if you consider this suggestion.

By the way, Github translate also works here. I've just tested in portable and standard install of FF but couldn't reproduce OP's issue.

**Comment by FilipePS** [comment]
> 
> 
> > The button on the toolbar also makes the extension more compatible with other browsers.
> 
> I understand that Chromium based browsers don't allow extension's icon/button to be placed inside URL bar. But take a look at "Reddit Enhancement Suite" extension for example. Its "Subreddit Style" button is placed inside URL bar on Firefox while on Chromium browsers it uses toolbar button.
> 
> All in all, it's off course up to you to chose the best approach. It's nothing major and people can live with it either way. But I'd be happy if you consider this suggestion.
> 
> I understand that Chromium based browsers don't allow extension's icon/button to be placed inside URL bar. But take a look at "Reddit Enhancement Suite" extension for example. Its "Subreddit Style" button is placed inside URL bar on Firefox while on Chromium browsers it uses toolbar button.

This is because this extension has a version for each browser.
If I were to do this in my extension I would have to separate the desktop version from the mobile version, which would be bad to create 2 pages for the same extension.
More like I said, although it will have 2 buttons, Firefox allows you to manually hide them.
