### ISSUE TITLE
Bypass Paywalls Clean and Translate Web Pages do not work together

### ISSUE THREAD

**Issue by Takwah** [FilipePS/Traduzir-paginas-web#171]
I am running these two plugins on Firefox Nightly for Android.

I tried Iceraven Browser and the same thing happened.

Test page: https://www.wired.com
Device: Pixel 2
System: Android 11

**Comment by FilipePS** [comment]
This conflict was with extensions that change the browser's userAgent. It was fixed in this [commit](https://github.com/FilipePS/Traduzir-paginas-web/commit/1930e5fe96ea10b620db4dbcbaa822767fbb6c08) and the fixes will be in the next version.
