### ISSUE TITLE
Chromium zip file

### ISSUE THREAD

**Issue by alfus5** [FilipePS/Traduzir-paginas-web#174]
Hey @FilipePS there the zip file of Traduzir Paginas Web for chromium browsers.
Please upload it for directly download
[Traduzir-paginas-web-master.zip](https://github.com/FilipePS/Traduzir-paginas-web/files/6604171/Traduzir-paginas-web-master.zip)

**Comment by FilipePS** [comment]
When I release the next version, I will put a direct download link. I will also put more details on how to install the extension.
