### ISSUE TITLE
You cannot select Google etc. from the menu, you have to go into deep settings and put Google again

### ISSUE THREAD

**Issue by Zivers88** [FilipePS/Traduzir-paginas-web#176]
Когда выбираешь DeepL потом нельзя выбрать гугл и пр. из меню, приходится лезть в глубокие настройки и ставить снова гугл
When you choose DeepL, then if u want to choose another translator you cannot select Google etc. from the menu, you have to go into deep settings and put Google again

**Comment by FilipePS** [comment]
When you translate with DeepL for the first time a new tab will open. Keep this tab open and the next texts you translate will be done without having to switch tabs. And you can change the translation service.

**Comment by FilipePS** [comment]
Problem fixed, wait for the next version to be released.
