### ISSUE TITLE
The add-on does not work on support.mozilla.org

### ISSUE THREAD

**Issue by Korb** [FilipePS/Traduzir-paginas-web#177]
Switching the language of web pages does not work either when using the button in the address bar, or when using hot keys. On other sites, this problem was not noticed.

Translate Web Pages 9.0.4 (17 May 2021)
Mozilla Firefox 90.0b6 (64-bit)
Microsoft Windows 10.0.19042.1055

**Comment by FilipePS** [comment]
There are some sites that no extensions are allowed to access. And this is one of them.

Try using the "Open in google translator" option, or try to translate the selected text using the context menu button (right click)
