### ISSUE TITLE
Switch context menu button to "Show original" when it is opened on a translated page 

### ISSUE THREAD

**Issue by Atemu** [FilipePS/Traduzir-paginas-web#18]
Offering to translate the page on a page that is already translated doesn't make sense (might even be confusing from a UX perspective) and being able to switch back from the context menu would be convenient.

**Comment by FilipePS** [comment]
The intention is to translate the page again if any text is created dynamically that the extension has not translated automatically.
Do you think it is better to appear to show the original text when the page is already translated?

**Comment by Atemu** [comment]
Oh interesting, didn't think of that, how common is it?

If the button was swapped based on translation state, you could still achieve the same thing (turn it off and then on again) but it would be less convenient if you had to do it often.

**Comment by FilipePS** [comment]
A while ago it was quite common, because it had no algorithm to translate new elements.  This algorithm currently exists but it is not 100%.  I don't know how often, but I haven't had any complaints about it either.

**Comment by FilipePS** [comment]
As far as I know these internal translators that come in some browsers do not translate elements created dynamically

**Comment by Atemu** [comment]
Working great, thank you!
