### ISSUE TITLE
Automatic translation doesn't work in private mode

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [FilipePS/Traduzir-paginas-web#180]
Thank you for your extension. I've got a problem when using it: website automatic translation (e.g. by pressing `Always translate this site`) feature doesn't work in private mode in Firefox.

**Comment by FilipePS** [comment]
This is on purpose, it is one of the measures aimed at increasing privacy.

**Comment by WPMGPRoSToTeMa** [comment]
@FilipePS may I create a PR that will add an option that switches this behavior?

**Comment by FilipePS** [comment]
> may I create a PR that will add an option that switches this behavior?

Everyone can create a pull request, this does not guarantee that it will be accepted.

**Comment by WPMGPRoSToTeMa** [comment]
> 
> 
> Everyone can create a pull request, this does not guarantee that it will be accepted.

I mean will you be okay to accept a PR with an option like that?

**Comment by FilipePS** [comment]
> I mean will you be okay to accept a PR with an option like that?

Would accept.
