### ISSUE TITLE
Problem with using left Alt

### ISSUE THREAD

**Issue by Sebek05** [FilipePS/Traduzir-paginas-web#182]
The left Alt is used in conjunction with the numeric keypad to enter ASCII codes. Using from your extension prevents you from entering ASCII codes because you are using the shortcut "left Alt + 1 or 2 or 3" to change the translation language.

**Comment by FilipePS** [comment]
Your keyboard does not have the `AltGr` key

**Comment by Sebek05** [comment]
No

**Comment by FilipePS** [comment]
I changed the default shortcut keys.
Remembering that in the settings there is an option to change the shortcut keys.
