### ISSUE TITLE
Feature request: an option to hide the button on selected text

### ISSUE THREAD

**Issue by dangh** [FilipePS/Traduzir-paginas-web#194]
Can we have an option to hide it? I select text a lot in my daily work flow and this extension offer to translate everything even when it doesn't make sense (md5 hash for example).

If you are open to it, I can submit a PR with some guidance. I'm not familiar with Firefox extension.

Cheers

**Comment by FilipePS** [comment]
This option has been added a long time ago.
In the translation settings look for "Show button to translate selected text".
In the popup that opens when clicking the address bar button or the toolbar button, you will also find an option to quickly enable/disable this feature.

**Comment by dangh** [comment]
Ah thank you. I was looking at the context menu setting where there are similar options :D
