### ISSUE TITLE
[SOLVED} Extension is no longer working in other browsers. 

### ISSUE THREAD

**Issue by serial02** [FilipePS/Traduzir-paginas-web#197]
Hello 

This extension is only working on firefox. There are two previous versions working on all non XPI browsers.

**Comment by FilipePS** [comment]
Check version 9.1

**Comment by serial02** [comment]
> Check version 9.1

With this new version the problem has been solved and all browsers are working their translator.

Thank you so much! 

![Capturar_select-area_20210630095952](https://user-images.githubusercontent.com/32621790/123965014-6cdbf200-d98a-11eb-86b4-5f5c07477d42.png)
