### ISSUE TITLE
Activate from page actions

### ISSUE THREAD

**Issue by neekt** [FilipePS/Traduzir-paginas-web#20]
I just noticed that the icon in the page actions drop-down in the address bar is gone with the latest update. I really liked having it there, rather than cluttering the toolbar or overflow menu.

So basically, this is just a request to have an option to return it to there.

Thanks for maintaining this great extension.

**Comment by FilipePS** [comment]
In the last version you will see the button appears in both the address bar and the toolbar.  You can hide one of them manually.

**Comment by neekt** [comment]
Okay, so I removed the button from the toolbar (right-click > 'Remove from Toolbar'), and it did indeed appear again in the page actions menu. This worked even with the button removed from the actual address bar. Problem solved, was just a little unclear what had happened.
