### ISSUE TITLE
Pages are not translated addons.mozilla.org

### ISSUE THREAD

**Issue by SWatB-com** [FilipePS/Traduzir-paginas-web#201]
Pages are not translated addons.mozilla.org
What could be the problem?

**Comment by FilipePS** [comment]
Firefox blocks extensions from accessing some domains like **addons.mozilla.org**.
Alternatively you can translate the selected text using the button in the context menu, or use the `Open in Google Translator` option.

**Comment by SWatB-com** [comment]
Is there a way to get around a hacking lock, or changing the hidden browser settings?

**Comment by FilipePS** [comment]
There is an advanced setting called `extensions.webextensions.restrictedDomains` that controls this. But I don't recommend changing anything.

**Comment by SWatB-com** [comment]
God's blessing will be, always.
