### ISSUE TITLE
Cursor Translate Icon

### ISSUE THREAD

**Issue by burkebrunson** [FilipePS/Traduzir-paginas-web#203]
I see no option available in the "Manage Extenion" page to remove the Translate icon that appears at the cursor whenever text is highlighted. I would prefer to have an option to be able to remove that cursor and simply use the button in the address bar, as necessary. Can you please make this a toggle option for those like me who wish to remove this icon?

**Comment by FilipePS** [comment]
When you open the address bar popup, by clicking the 3-dot button, you have the option of not showing this button to translate the selected text.
And when accessing the extensions settings, there are several categories of settings, the option to hide that button is in the "translation" category.

**Comment by burkebrunson** [comment]
OK. I've fixed my issue now. However, I want to point out a context issue with the wording of "When you open...." The option you are referring to could just as easily apply to the button in the address bar instead of the button at the cursor. So, if I don't know which one it is when I read it, that isn't optimal. I would also consider changing that wording on the extension settings page, too. Also, the ability to find that option in extension settings is somewhat buried; I would consider possibly separating these types of operation settings into their own category/tab.

Thank you for your help. Take care.

**Comment by FilipePS** [comment]
With your answer, I was in doubt if you understood what I said. See these images.
![img1](https://user-images.githubusercontent.com/54990796/124156659-44c5bf00-da6e-11eb-93a2-bbb0f093402a.png)
![img2](https://user-images.githubusercontent.com/54990796/124156667-45f6ec00-da6e-11eb-9350-7f6f566ddd87.png)

**Comment by burkebrunson** [comment]
> OK. I've fixed my issue now.

Yes, I totally understood what you said, as indicated in the first sentence of my response to you.

However, I am also thinking the same - that, based on your response to me, that you don't understand what I am trying to say....

In any case, thanks and take care.
