### ISSUE TITLE
How to remove it(see the video)?

### ISSUE THREAD

**Issue by vitalii2011** [FilipePS/Traduzir-paginas-web#205]
https://drive.google.com/file/d/1lGwh5fc45HsqZTr-DLRICEoVG6id8T4t/view?usp=sharing 
- I wouldn't have noticed and it wouldn't have bothered me if it hadn't been for the "twitching" when the scroll bar appeared.
- It's the same on Google Translate.

**Comment by FilipePS** [comment]
Problem fixed, wait for the next version to be released.
