### ISSUE TITLE
“Show original”function often fails.

### ISSUE THREAD

**Issue by minshifu** [FilipePS/Traduzir-paginas-web#206]
This is a great addon but the “Show original”function often fails. Many parts of the page fail to return to the original language after I hit the "Show original" button.  Sometimes the "Always translate" function also fails,because some parts of the page can not be translated automatically . Could you pls fix them, especially the first problem? Thank you!

**Comment by FilipePS** [comment]
Can you provide links to sites with these problems?

**Comment by minshifu** [comment]
Hi, I think I find out the reason why.   I use the following highlight addon https://addons.mozilla.org/zh-CN/firefox/addon/highlightthis/?src=search  which highlights some key words on a webpage. For your addon, my target language is English. When I browse  a non-English webpage, it will be automatically translated into English version by your addon. At the same time some key words will be matched and highlighted by the above highlight addon. Then when I want to check the original language version and hit the "Show Original" button, the paragraphs with key words highlighted will not return to the original language version as shown by the picture below.  However, both your addon and the highlight addon are important for me. I really want to use them at the same time. Could you kindly check the problem and find a fix? Thank you so much! Best regards!

This is the test webpage  https://www.antaranews.com/berita/2258410/syarief-hasan-pemerintah-perlu-evaluasi-kebijakan-penanganan-pandemi

**Key words are highlighted after webpage is translated into English version.**

![图片](https://user-images.githubusercontent.com/5119952/125148356-407f5d00-e164-11eb-874d-a2b2c3c04854.png)

**After "Show Original" button is hit, the paragraphs with key words highlighted fail to return to the original language version.**

![图片](https://user-images.githubusercontent.com/5119952/125148383-745a8280-e164-11eb-82b4-4cb6a3effd58.png)

**Comment by minshifu** [comment]
Hi, I figure out a solution. Could you make the original text panel keep showing or at least showing for longer time as shown by the picture below ? Thank you!

![image](https://user-images.githubusercontent.com/5119952/125151013-bb517380-e176-11eb-8020-f0eabbda1672.png)
