### ISSUE TITLE
Please ...add "translate.google.cn" translation engine?

### ISSUE THREAD

**Issue by loyingEcu** [FilipePS/Traduzir-paginas-web#21]
Hello,

Because China cannot access translate.google.com

translate.google.cn is the address that Google can visit in China. I wonder if this interface can be added?

please

**Comment by FilipePS** [comment]
Test this extension to see if it works.
Just download the file and then open it with firefox.
https://filebin.net/wuhxrajerxawvpqv

**Comment by loyingEcu** [comment]
> 
> 
> 测试此扩展以查看是否有效。
> 只需下载文件，然后使用Firefox打开即可。
> https://filebin.net/wuhxrajerxawvpqv

Thank you I tried it and it didn't work

**Comment by FilipePS** [comment]
Open the Google Translate website, press "F12" to open the developer tools panel. Click on the "Network" tab. Type something to be translated. Several requests will appear, let me know the urls of those requests.

**Comment by loyingEcu** [comment]
> 
> 
> Open the Google Translate website, press "F12" to open the developer tools panel. Click on the "Network" tab. Type something to be translated. Several requests will appear, let me know the urls of those requests.


https://clients1.google.com/complete/search?q=hello&client=translate-web&ds=translate&hl=en&requiredfields=tl%3Azh-CN&callback=_callbacks____pkdql7vj8


https://translate.google.cn/translate_a/single?client=webapp&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=sos&dt=ss&dt=t&otf=1&pc=1&ssel=3&tsel=6&xid=45662847&kc=2&tk=326533.147082&q=hello


https://translate.google.cn/gen204?ilog=orig&client=webapp&cpy=0&clk=1&sel=0&ctx=0

https://translate.google.cn/gen204?client=webapp&lexicon=dt=cm,sl=en,tl=zh-CN,hl=zh-CN,q=hello,e=show,mbd=ne,mmd=ne,mex=e,cm=ne

**Comment by FilipePS** [comment]
Download this other extension and see if it works.
https://filebin.net/wuhxrajerxawvpqv

**Comment by loyingEcu** [comment]
> 
> 
> Download this other extension and see if it works.
> https://filebin.net/wuhxrajerxawvpqv

Sorry, it still doesn't work

**Comment by FilipePS** [comment]
Do you know any proxy or vpn from Mainland China, which allows me to see what's going on?

**Comment by loyingEcu** [comment]
> 
> 
> Do you know any proxy or vpn from Mainland China, which allows me to see what's going on?

I'm sorry I can't find it, but I tried to solve it with version 7.1
contentScript_google.js

ranslate.google.com/translate_a/element.js → translate.google.cn/translate_a/element.js

**Comment by FilipePS** [comment]
Install version 6.7
https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/versions/?src=search

**Comment by loyingEcu** [comment]
> 
> 
> Install version 6.7
> https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/versions/?src=search

No, I can only do it after using a VPN

**Comment by FilipePS** [comment]
Install version 6.7 and in the settings change "Use the new translation algorithm" from "Yes (recommended)" to "No (use widgets)".

**Comment by FilipePS** [comment]
Does Yandex translation work normally?

**Comment by loyingEcu** [comment]
> 
> 
> Does Yandex translation work normally?

Yes, Yandex translation works normally

**Comment by FilipePS** [comment]
Do you still use the extension? Could you pass an email address to a private message?

**Comment by linsui** [comment]
Here is a proxy to China. https://www.transocks.com/ 
And [Saladict](https://github.com/crimx/ext-saladict) is using following request which is accessible in China directly:

```
https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&sl=auto&tl=zh-CN&q=Do%20you%20still%20use%20the%20extension%3F%20Could%20you%20pass%20an%20email%20address%20to%20a%20private%20message%3F
```

See https://github.com/crimx/ext-saladict/search?q=translate.googleapis.com&unscoped_q=translate.googleapis.com

**Comment by FilipePS** [comment]
I tried to use this program and it didn't work.
And this translation url is for text only, the addon needs to translate into HTML format.

**Comment by FilipePS** [comment]
I did some tests and just can't understand. Sometimes wikipedia worked, sometimes it didn't.
The widgets also worked on one site, but did not work on another.
This government censorship algorithm to be somewhat random at times.
The only thing I can do is to leave Yandex as the default translation engine for the Chinese.

**Comment by ghcsd** [comment]
> 
> 
> I did some tests and just can't understand. Sometimes wikipedia worked, sometimes it didn't.
> The widgets also worked on one site, but did not work on another.
> This government censorship algorithm to be somewhat random at times.
> The only thing I can do is to leave Yandex as the default translation engine for the Chinese.

I can confirm that simply replacing the `translate.google.com` domain with `translate.google.cn` in the following code can work in China.
https://github.com/FilipePS/Traduzir-paginas-web/blob/03ee27e7aea49236412a319dc9d01def83b27492/background.js#L163
