### ISSUE TITLE
Blue color changed in Firefox Proton, not matching icon anymore

### ISSUE THREAD

**Issue by AndreiMiculita** [FilipePS/Traduzir-paginas-web#212]
Related to #134 
![Screenshot from 2021-07-04 16-13-15](https://user-images.githubusercontent.com/6352172/124388337-c4f45a80-dce2-11eb-9c9d-2b945cb14a34.png)
The new color is rgb(0, 221, 255) - in hex format 0x00DDFF

**Comment by FilipePS** [comment]
Firefox has several factors to define the color of that icon.
If the theme you are using sets `colors.icons_attention`, Firefox will use this color.
If the theme doesn't set this color, Firefox will use one of these colors.
`RGB(0, 221, 255)`
`RGB(0, 97, 244)`
I haven't figured out the exact criteria for him to choose one of these 2 colors.
So for now I'm going to leave the icon as it is now.
