### ISSUE TITLE
Bing Translator problem

### ISSUE THREAD

**Issue by CaganAgabey** [FilipePS/Traduzir-paginas-web#219]
Hi, idk if it's not a permanent bug but Bing Translator doesn't work in extension now, works well in their website

**Comment by FilipePS** [comment]
I have tested it now and it seems to be working.
What language are you translating into?

**Comment by CaganAgabey** [comment]
Turkish
It stucks like this, I also restarted firefox, reinstalled the addon
![image](https://user-images.githubusercontent.com/57146234/125145258-4441be00-e129-11eb-926c-78b74b33c5d1.png)

**Comment by userdeadinterface** [comment]
I'm also having this problem when translating from [Any Language, Mainly English] to Icelandic using Bing. Bing Translate in Icelandic is way better than Google Translate so having Bing Translator working would be great.

**Comment by userdeadinterface** [comment]
This has been patched in the new update. Bing now works with Firefox.

**Comment by FilipePS** [comment]
It took 1 year for me to release a version with this problem fixed :(
