### ISSUE TITLE
Brave Setup

### ISSUE THREAD

**Issue by EmirLogas** [FilipePS/Traduzir-paginas-web#220]
![image](https://user-images.githubusercontent.com/76751818/125163317-46d9fd00-e195-11eb-8f02-08c9c5318827.png)
![image](https://user-images.githubusercontent.com/76751818/125163329-55c0af80-e195-11eb-89e5-03c98b6497e6.png)
2 Issue for setup at Brave.

**Comment by FilipePS** [comment]
These errors do not affect the functionality of the extension.
