### ISSUE TITLE
Missing Keyboard Shortcut for Full Webpage Translation

### ISSUE THREAD

**Issue by dtantono** [FilipePS/Traduzir-paginas-web#221]
Hi
I saw that in the recent release especially on the crx file the keyboard shortcut for full webpage translation is gone. Is it a bug?

**Comment by FilipePS** [comment]
I believe this topic is related to this other #166 .
If for any reason a hotkey doesn't work, try changing it.
In Firefox, just access the extension's settings.
In chromium based browsers, change the hotkeys by one of these links.
`chrome://extensions/shortcuts`
`edge://extensions/shortcuts`
`brave://extensions/shortcuts`
