### ISSUE TITLE
Transalor issue - Too quick?

### ISSUE THREAD

**Issue by Eagleizer** [FilipePS/Traduzir-paginas-web#224]
Try to navigate around on this site, while having Translate from Thai to English:

https://shopee.co.th/search?keyword=firefox

I always have to go back to Original and then Translate again for it to work. 
It's like the Translator is too quick to trigger the translation, translating the 
page before it's loaded. 

So after doing the Original->Translate again, the page seems  translated, but:

When scrolling down the page, there will be text that is not translated 
because it was not loaded when doing the Original->Translate (I guess). 

Maybe the Translate could be re-triggered when scrolling, if it is already in 
a translated state? 

Cheers :)

**Comment by nnolex** [comment]
I have the same problem on many sites. Until recently, the extension translated content that was dynamically loaded on pages, but now it doesn't. This can be seen on sites with dynamically loaded news feeds or, for example, inoreader, where I could switch through the feeds and they translated almost instantly. Now I have to switch languages or translation provider for the new content to translate. I don't know what caused it, I use Firefox.

**Comment by Eagleizer** [comment]
> 
> 
> I have the same problem on many sites. Until recently, the extension translated content that was dynamically loaded on pages, but now it doesn't. This can be seen on sites with dynamically loaded news feeds or, for example, inoreader, where I could switch through the feeds and they translated almost instantly. Now I have to switch languages or translation provider for the new content to translate. I don't know what caused it, I use Firefox.

Thanks for sharing! 

For now, I have made a workaround that works quite well (You can use Macros to assign it to a key on your keyboard): 

Since I already have a mouse with lots of buttons (G600), assigning key press for Translate makes sense.
The shortcut for turning translation ON/OFF is CTRL+ALT+T. You can of course press this, but for me, since I have 
my keyboard behind a steering wheel that is permanently mounted to my desk, assigning this to a key or a 
button is a lot more convenient. You can also change the shortcut from CTRL+ALT+T to something else, but 
unfortunately it **HAS** to start with CTRL+ALT, which makes the option quite useless if you are going to press that 
on your keyboard anyway. 

To make a MACRO, just Google it. To add it as a button on your mouse (if you have extra buttons), read the 
instructions for your mouse, or try YouTube .

When using this workaround, the best thing to do is to remove the translate for the language you are 
translating from. Go to the extensions settings page, and delete it (Turning it OFF does not work). 

Hopefully there will be a fix for this soon, but binding the shortcut to a key or button is way better than 
clicking around with your mouse. When scrolling, revealing un-translated text, just hit the key or button twice. 
I already tried to let the software on my mouse to double on 1 click, but then you are lost when it gets 
stuck in un-translated state. I also just realized that it is quite convenient to have to button there, 
as I can change quickly if I have a friend who needs to read the original text, which happens often.

Still:
The auto translate when scrolling seems to be dependent on what site I'm on, but Shopee do have this 
problem. All sites have the problem where it seems to translate too quick when entering a new page.

Cheers :)

**Comment by FilipePS** [comment]
In version 9.2 this feature was disabled by default for new installs.
In the next version this feature will be active again by default.
