### ISSUE TITLE
"Automatically translate when clicking on a link that takes you to the same domain as the current site" doesn't work

### ISSUE THREAD

**Issue by mystiquewolf** [FilipePS/Traduzir-paginas-web#229]
I have enabled the feature "Automatically translate when clicking on a link that takes you to the same domain as the current site" but when i visit a link in the same domain the page is not translated automatically.
Firefox 90.0
Translate pages 9.2

**Comment by FilipePS** [comment]
To reproduce the issue, I need a link to a website with this issue.

**Comment by mystiquewolf** [comment]
For example this one - https://www.policia.es/_es/tupolicia_conocenos.php
But seems to be on each site.

**Comment by FilipePS** [comment]
I have tested it and it is working correctly.
Are you sure you really activated this feature?
When you activate a new permission is requested, have you activated this permission?

**Comment by mystiquewolf** [comment]
Yes, i have enabled it. Please see the screencast here: https://youtu.be/4xHbQg1_hkA

**Comment by mystiquewolf** [comment]
Sorry, wrong OBS source. New video is here: https://youtu.be/kYYbPFf2z4Q

**Comment by mystiquewolf** [comment]
Sorry, i'm new to OBS recorder. Seems it records only Firefox window and not its popups. So when i change the language from Spanish to English you can't see it in the popup, but you can see that the page content translates.

**Comment by mystiquewolf** [comment]
I can confirm that after disabling and enabling the option again i've been asked to enable additional permission. Once i did this it started working. Thanks!
