### ISSUE TITLE
The page cannot be translated. Uses 100% RAM (use Huge 32 GB RAM !!!) and Crash

### ISSUE THREAD

**Issue by M4K1N3R0** [FilipePS/Traduzir-paginas-web#233]
The page cannot be translated. Uses 100% RAM (use Huge 32 GB RAM !!!) 
Website:
https://proza.ru/2018/01/01/1686

https://proza.ru/2017/06/28/845

Translate:
Russian => Polish

**Comment by FilipePS** [comment]
I've made some fixes so this issue doesn't occur when opening the website. However if you try to translate the site (or the extension is settings to translate automatically), this problem will occur.
Probably the fix that will allow to translate this site will be in version 9.4

**Comment by FilipePS** [comment]
This problem has finally been fixed. 
These commits are part of the solution:
https://github.com/FilipePS/Traduzir-paginas-web/commit/29280a882e06a1635e5d9aa09cf84eed509ac144, https://github.com/FilipePS/Traduzir-paginas-web/commit/6f0218bafe560897df939e895fc5410972bdc609, https://github.com/FilipePS/Traduzir-paginas-web/commit/28c4071de64fe3485ae9b240272a113146d6469c and https://github.com/FilipePS/Traduzir-paginas-web/commit/6670e2a6619866a82a65cceac9fdef2138399d94

Wait for the release of version 9.4.
