### ISSUE TITLE
9.1 > 9.2 - Loss of Live Updates

### ISSUE THREAD

**Issue by CodexUK** [FilipePS/Traduzir-paginas-web#235]
Firstly, thanks for the extension!

However I noticed that in the update from v9.1 to v9.2 the extension no longer updates in real time on firefox.
I primarily use this when watching streams on twitch.tv and the previous version would update the live chat in real time, so each new message in the chat would be translated after a few seconds.
Unfortunately since the update this no longer happens and the page has to be manually translated each time.

Not sure if the original real time updates were intentional or not, but it was handy for me at least.

I've currently reverted back to using v9.1, but just wanted to mention it in case it is something that can be restored in future updates.

**Comment by FilipePS** [comment]
Check version 9.3

**Comment by CodexUK** [comment]
Looks to be working great, thanks :D
