### ISSUE TITLE
Add the ability to translate selected text

### ISSUE THREAD

**Issue by popov895** [FilipePS/Traduzir-paginas-web#24]
It'd be great to have the ability to translate the selected text, same as in the official [Google Translate extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb) for Google Chrome.

**Comment by FilipePS** [comment]
There are several addons for Firefox that do this.
Is there a feature of this chrome extension that the others for Firefox don't have?

**Comment by popov895** [comment]
I think no. But it would be great to have all these features in one extension.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/eb53ecb8223fb742eabf400e333af50924d7b461
