### ISSUE TITLE
Can not restore translation When "Do not sort the google translate results" is enabled

### ISSUE THREAD

**Issue by azu** [FilipePS/Traduzir-paginas-web#240]
I can not restore translation When "Do not sort the google translate results" option is enabled.

Reproduce Steps.

1. Visit any website. e.g. https://aws.amazon.com/jp/blogs/aws/heads-up-aws-support-for-internet-explorer-11-is-ending/
2. Translate to "Japanese"
3. Restore to original language

Some text still be japanese.

https://user-images.githubusercontent.com/19714/127586872-2ac65319-b0be-4613-ab6e-9e0cd8c8131f.mp4

## Expected

Restore all texts to original language

## Actual

Can not restore some texts

**Comment by FilipePS** [comment]
Bug fixed

**Comment by azu** [comment]
Thanks!
