### ISSUE TITLE
Translation in PDF reader

### ISSUE THREAD

**Issue by waggstoun** [FilipePS/Traduzir-paginas-web#241]
Is it possible to implement the function of translating the selected text into a PDF reader?

**Comment by alfus5** [comment]
pdf files are protected by browser by default

**Comment by waggstoun** [comment]
I convert to HTML format, but the file size increases dramatically.

**Comment by FilipePS** [comment]
To translate a pdf it is necessary to convert it to html. I've tested mozilla's pdf.js which runs directly in the browser but it doesn't meet the specific needs for translation.
I tested several other software and the only one that converts in the ideal way to allow translation is Poppler. However, it doesn't run directly in the browser.
I'm thinking about the possibility of renting a vps to run this software and convert the pdfs in the cloud. Or maybe release a separate software to integrate with my extension.

**Comment by waggstoun** [comment]
I would do this as an additional paid service. Architecturally, I see it as a service network to use the budget efficiently. And also for adaptive scaling in relation to demand and providing quality service. In this way, I would stay within this project, while developing it in relation to the needs of the audience.
