### ISSUE TITLE
Оne-click translation on the icon

### ISSUE THREAD

**Issue by Ved-un** [FilipePS/Traduzir-paginas-web#244]
Can you add at least an optional function - one-click translation on the icon in the address bar?
It's so tired of double-clicking that I've been looking for an alternative to this addon for a long time (

**Comment by waggstoun** [comment]
Maybe set up hotkeys? Quite convenient, although some people do not like it.

**Comment by FilipePS** [comment]
I implemented this feature. You can enable it by setting **Translate the page by clicking once on the button in the address bar. (To see the popup, right-click)** in the **others** category. Wait for the next version to be released.

**Comment by Ved-un** [comment]
> I implemented this feature. You can enable it by setting...

Oooh! Thank you so much!

**Comment by Ved-un** [comment]
> Maybe set up hotkeys? ...

I am in a prone position and therefore cannot control the keyboard.
