### ISSUE TITLE
Unable to translate the page while scrolling down or up very fast

### ISSUE THREAD

**Issue by nbpl6** [FilipePS/Traduzir-paginas-web#245]
the page wont translate after i scroll down or up very fast or not, im getting annoyed from that ;-;

**Comment by FilipePS** [comment]
I have tested it and it seems to be working.

This issue happens on which sites?
What translation service are you using?
What language are you translating into?

**Comment by nbpl6** [comment]
Sorry, it was fixed now. I'm probably sure it's my internet being slow causing of this issue. Apologies for wasting your time.
