### ISSUE TITLE
Make the UI more Firefox-like

### ISSUE THREAD

**Issue by popov895** [FilipePS/Traduzir-paginas-web#25]
Currently, the UI of the extension is a widget with buttons. But it would be great if the user interface looked more native to Firefox and was a menu, as you can see in the screenshot. Also, the icons should be monochrome.

![Screenshot_20200816_164716](https://user-images.githubusercontent.com/24252473/90336002-9a71b400-dfe1-11ea-96bf-a8f2203170a2.png)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/b61e8cab1e5981789ad875169889aa60f051f5de
