### ISSUE TITLE
The translating pop-up hide elements of web pages on mobile

### ISSUE THREAD

**Issue by alfus5** [FilipePS/Traduzir-paginas-web#252]
The TPW extension hides a part of the web page which can be very (very) annoying when you have to redo it several times

In the example below the pop-up hides the "next" button
![Video_20210815_122056](https://user-images.githubusercontent.com/63202698/129478574-8ef793d6-7e80-4023-a3d3-49343081cd35.gif)

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
