### ISSUE TITLE
Translator causes Browser to crash unexpectedly

### ISSUE THREAD

**Issue by M4K1N3R0** [FilipePS/Traduzir-paginas-web#254]
Translator causes Browser to crash unexpectedly, no matter which pages are translated.
it happens randomly, even whenever i try to start Firefox.
The add-on also causes problems without translation, all the time randomly, e.g. 4 times a day 

**crash_log**
`
AdapterDeviceID: 0x1c82
AdapterDriverVersion: 30.0.14.7141
AdapterSubsysID: 00000000
AdapterVendorID: 0x10de
Add-ons: %7Be29fff07-5ec5-4417-9933-2a72f5569d91%7D:2.0,%7B036a55b4-5e72-4d05-a06c-cba2dfcc134a%7D:9.3,%7B88664789-f91e-40e1-adb9-e4e9a8c48867%7D:0.5.0,tab-counter-plus%40Loirooriol:3.4,%7B0d28e91e-0540-46e0-9f78-84bcdb32567c%7D:1.2.2,languagetool-webextension%40languagetool.org:4.1.0,helper%40savefrom.net:9.31,reset-search-defaults%40mozilla.com:2.1.0,addons-search-detection%40mozilla.com:1.0.1,screenshots%40mozilla.org:39.0.1,webcompat%40mozilla.org:24.2.0,formautofill%40mozilla.org:1.0.1,doh-rollout%40mozilla.org:2.0.0,pictureinpicture%40mozilla.org:1.0.0,google%40search.mozilla.org:1.1,allegro-pl%40search.mozilla.org:1.1,ddg%40search.mozilla.org:1.1,pwn-pl%40search.mozilla.org:1.0,wikipedia%40search.mozilla.org:1.1,wolnelektury-pl%40search.mozilla.org:1.0,amazondotcom%40search.mozilla.org:1.3,bing%40search.mozilla.org:1.3
AvailablePageFile: 6144000
AvailablePhysicalMemory: 11749289984
AvailableVirtualMemory: 8793368895488
BreakpadReserveAddress: 80150528
BreakpadReserveSize: 83886080
BuildID: 20210804193234
CPUMicrocodeVersion: 0x19
ContentSandboxCapable: 1
ContentSandboxLevel: 6
ContentSandboxWin32kState: Win32k Lockdown disabled -- Operating system not supported
CrashTime: 1629186180
DOMIPCEnabled: 1
EMCheckCompatibility: true
FramePoisonBase: 9223372036600889344
FramePoisonSize: 65536
GPUProcessLaunchCount: 1
GPUProcessStatus: Running
InstallTime: 1629013271
JSOutOfMemory: Reported
LauncherProcessState: 0
ModuleSignatureInfo: {"Apple Inc.":["mdnsNSP.dll"],"ESET, spol. s r.o.":["eOppMonitor.dll","eplgFirefox.dll"],"Microsoft Corporation":["ucrtbase.dll","api-ms-win-crt-multibyte-l1-1-0.dll","api-ms-win-crt-utility-l1-1-0.dll","api-ms-win-crt-environment-l1-1-0.dll","api-ms-win-crt-filesystem-l1-1-0.dll","api-ms-win-crt-time-l1-1-0.dll","api-ms-win-crt-math-l1-1-0.dll","api-ms-win-crt-locale-l1-1-0.dll","api-ms-win-crt-convert-l1-1-0.dll","api-ms-win-crt-stdio-l1-1-0.dll","api-ms-win-crt-heap-l1-1-0.dll","api-ms-win-crt-string-l1-1-0.dll","api-ms-win-core-synch-l1-2-0.dll","msvcp140.dll","api-ms-win-core-file-l2-1-0.dll","api-ms-win-core-timezone-l1-1-0.dll","api-ms-win-core-file-l1-2-0.dll","api-ms-win-core-processthreads-l1-1-1.dll","api-ms-win-core-localization-l1-2-0.dll","api-ms-win-crt-runtime-l1-1-0.dll","VCRUNTIME140.dll"],"Microsoft Windows":["ntdll.dll","psapi.dll","d2d1.dll","Wpc.dll","wsock32.dll","dxgi.dll","wshbth.dll","winrnr.dll","pnrpnsp.dll","NapiNSP.dll","npmproxy.dll","netprofm.dll","winmm.dll","dbghelp.dll","dwmapi.dll","uxtheme.dll","propsys.dll","MMDevAPI.dll","WSHTCPIP.DLL","ntmarta.dll","powrprof.dll","samcli.dll","netutils.dll","wtsapi32.dll","IPHLPAPI.DLL","avrt.dll","version.dll","gpapi.dll","winsta.dll","rsaenh.dll","mswsock.dll","bcryptprimitives.dll","wevtapi.dll","apphelp.dll","RpcRtRemote.dll","msasn1.dll","profapi.dll","cfgmgr32.dll","devobj.dll","ws2_32.dll","msvcrt.dll","clbcatq.dll","setupapi.dll","imm32.dll","shlwapi.dll","imagehlp.dll","sechost.dll"],"Mozilla Corporation":["firefox.exe","xul.dll","osclientcerts.dll","nssckbi.dll","freebl3.dll","softokn3.dll","nss3.dll","lgpllibs.dll","mozglue.dll"]}
MozCrashReason: MOZ_CRASH()
Notes: 
FP(D00-L1000-W00001000-T000) DWrite? DWrite+ WR? WR+ OMTP? OMTP- 
OOMAllocationSize: 8192
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 1951069
StartupCrash: 0
StartupTime: 1629186178
SystemMemoryUsePercentage: 45
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20210804193234","version":"91.0","vendor":"Mozilla","displayVersion":"91.0","platformVersion":"91.0","xpcomAbi":"x86_64-msvc","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":20417,"virtualMaxMB":8388608,"cpu":{"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Windows_NT","version":"6.1","locale":"pl-PL","servicePackMajor":1,"servicePackMinor":0,"windowsBuildNumber":7601},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":false,"DWriteEnabled":true,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":false,"adapters":[{"description":"NVIDIA GeForce GTX 1050 Ti","vendorID":"0x10de","deviceID":"0x1c82","subsysID":"00000000","RAM":4096,"driver":"nvd3dumx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um","driverVendor":null,"driverVersion":"30.0.14.7141","driverDate":"7-12-2021","GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080,"refreshRate":165,"pseudoDisplay":false}],"features":{"compositor":"none","hwCompositing":{"status":"available"},"gpuProcess":{"status":"available"},"wrQualified":{"status":"available"},"webrender":{"status":"available"},"wrCompositor":{"status":"unavailable:FEATURE_FAILURE_DCOMP_NOT_WIN10"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"unused"},"omtp":{"status":"disabled:FEATURE_FAILURE_DISABLED"},"d3d11":{"status":"available","version":0,"warp":false,"textureSharing":false,"blocklisted":false},"d2d":{"status":"available","version":"1.1"}}},"appleModelId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":false,"telemetryEnabled":false,"locale":"en-US","intl":{},"update":{"channel":"release","enabled":true},"userPrefs":{"app.shield.optoutstudies.enabled":false,"browser.cache.disk.capacity":163840,"browser.shell.checkDefaultBrowser":false,"browser.search.region":"PL","browser.search.widget.inNavBar":true,"browser.startup.page":3,"browser.urlbar.showSearchSuggestionsFirst":false,"devtools.chrome.enabled":true,"dom.max_script_run_time":20,"privacy.donottrackheader.enabled":true,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":6,"contentWin32kLockdownState":3},"launcherProcessState":0,"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":null},"profile":{}}
TelemetrySessionId: 0c952103-2b2a-4b5a-b7fb-dc9bae536ae1
ThreadIdNameMapping: 16980:"IPC I/O Parent",5884:"Timer",17720:"Link Monitor #1",2888:"Socket Thread",19924:"Permission",2936:"JS Watchdog",13376:"TaskController Thread #2",19296:"TaskController Thread #1",21236:"TaskController Thread #3",11056:"TaskController Thread #0",19052:"Cache2 I/O",19644:"Cookie",13528:"Untrusted Modules",15872:"StreamTrans #4",16480:"BackgroundThreadPool #2",13320:"IPDL Background",12296:"QuotaManager IO",16448:"IndexedDB #1",13908:"Worker Launcher",17308:"VsyncIOThread",9240:"IPC Launch",14084:"SoftwareVsyncThread",10688:"Compositor",20436:"ImageIO",19800:"DOM Worker",11392:"IndexedDB #2",14968:"StreamTrans #6",15688:"StreamTrans #10",2968:"TRR Background",19940:"StreamTrans #11",17600:"StreamTrans #14",
Throttleable: 1
TotalPageFile: 38586982400
TotalPhysicalMemory: 21409058816
TotalVirtualMemory: 8796092891136
UptimeTS: 9.124216439
Vendor: Mozilla
Version: 91.0
Winsock_LSP: MSAFD TCP/IP [TCP/IP] : 2 : 2 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD TCP/IP [UDP/IP] : 2 : 2 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD TCP/IP [RAW/IP] : 2 : 2 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD TCP/IP [TCP/IPv6] : 2 : 23 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD TCP/IP [UDP/IPv6] : 2 : 23 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD TCP/IP [RAW/IPv6] : 2 : 23 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 Dostawca usług RSVP TCPv6 : 2 : 23 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 Dostawca usług RSVP TCP : 2 : 2 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 Dostawca usług RSVP UDPv6 : 2 : 23 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 Dostawca usług RSVP UDP : 2 : 2 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 MSAFD RfComm [Bluetooth] : 2 : 32 : 1 : 3 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.`

**Comment by FilipePS** [comment]
When you open Firefox, do any websites open with it?

How long have you been using the extension?

How long has this problem started to occur? Can you tell if it was right after an update?

What language do you translate the page into?

**Comment by M4K1N3R0** [comment]
Today the error occurred again, most often when starting Firefox. I think this error occurs when I updated to version 9.3

**Comment by M4K1N3R0** [comment]
The extension slows down Firefox, so maybe unexpected crashes from here?
This message is built directly into Firefox and warns you about add-ons that slow Firefox down. 
Html File Size: 121 KB
See: 
https://i.postimg.cc/x8hT0P1B/Screen-Shot-08-24-21-at-11-05-AM.png

**Comment by FilipePS** [comment]
I realized now that you had already created this other topic about this problem. https://github.com/FilipePS/Traduzir-paginas-web/issues/233
Version 9.4 will be released later this month.

**Comment by M4K1N3R0** [comment]
Chrome will translate this site https://proza.ru/2020/06/01/1981, but only up to a certain text limit. It cannot translate, for example, a few hundred KB of a file to a few or more megabytes. I don't know what the translation text limit is? Perhaps 10,000 characters. 

This page https://translate.yandex.com/translate   translates the page quickly, but is still not very accurate as there are not many translations of Russian words in the dictionary.
https://proza.ru/2020/06/01/1981


And here's the other curiosity.
The slowdown also seems to be happening on google.pl 
https://postimg.cc/GB5jZvdV

**Comment by FilipePS** [comment]
On that page with millions of characters separated by <br> tags I know why the extension crashed.
But google homepage is a surprise to me.

What are your device settings?
cpu, ram, hd, etc...
Or simply the model name if it's a notebook.

Another likely cause is the translation cache, maybe it's too big and your device has difficulty reading it.

**Comment by M4K1N3R0** [comment]
4x3.5 GHz intel processor PHYSICAL RAM 20 GB. Virtual Memory
(pagefile.sys) C: \ 4GB + D: \ 12GB
2000GB SSD


wt., 31 sie 2021 o 00:04 FilipePS ***@***.***> napisał(a):
