### ISSUE TITLE
Android Firefox size of extension bar

### ISSUE THREAD

**Issue by lamyergeier** [FilipePS/Traduzir-paginas-web#257]
In Firefox on Android, the extension Band appears sometimes small while sometimes large as follows

![Screenshot_20210822-122408_Firefox Nightly](https://user-images.githubusercontent.com/42092626/130351870-c41be8d3-ad5d-4308-807a-e1272ed0c715.jpg)
![Screenshot_20210822-122415_Firefox Nightly](https://user-images.githubusercontent.com/42092626/130351873-b014766e-9965-48f1-aec8-38e81bf07794.jpg)

I like the small one, is there any settings in which we can specify the size of bar we would want it to be.

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
