### ISSUE TITLE
Google translate: If you fail to get the TKK, it will not retry

### ISSUE THREAD

**Issue by EYHN** [FilipePS/Traduzir-paginas-web#26]
I noticed that sometimes Google Translate not work, and it will work again after restarting the browser.

Debugging found that the background script failed to fetch the Google translation TKK. (when the network is unavailable)
Automatically update the TKK setting after 30 minutes, i must manually restart the browser to refresh TKK.

https://github.com/FilipePS/Traduzir-paginas-web/blob/master/background.js#L121-L132

I think that when the background script fails to fetch the TKK, it should retry until it succeeds.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/2e0dcf50f04ef44516d66fd6692270188dabb26c
