### ISSUE TITLE
Extension not working for Opera Browser v80.0.4157.0

### ISSUE THREAD

**Issue by droidmenow** [FilipePS/Traduzir-paginas-web#261]
1. Extension tested using:

- **Browser**: Opera (Developer Edition), 
- **Browser Version**: 80.0.4157.0
- **System**: Windows 10 64-bit
- **Extension version**: [https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.3](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.3)

2. Default options were used for extension, with only the following changed:
**Automatically translate these languages** --> set to **Russian**

3. Tested using website [https://yandex.com/news](https://yandex.com/news)
Expected result: Automatically translates from Russian to English
Actual result: No Translation performed

### Stack Trace

```
No webNavigation permission
Context
_generated_background_page.html
Stack Trace
background/background.js:561 (disableTranslationOnClickingALink)
background/background.js:570 (anonymous function)
lib/config.js:71 (anonymous function)
lib/config.js:71 (twpConfig.set)
background/background.js:583 (anonymous function)

Unchecked runtime.lastError: Cannot determine language
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)
Nothing to see here, move along.

```

**Comment by FilipePS** [comment]
When calling the function `chrome.tabs.detectLanguage` this error `Unchecked runtime.lastError: Cannot determine language` is returned. This doesn't stop the extension from translating the sites, it just doesn't allow detection of the site's language. This issue should be resolved by opera developers.

What made that site not be translated was another reason. Opera blocks extensions from accessing search sites such as _google.com_, _yandex.com_, _duckduckgo.com_, etc...
To solve this problem, open the extension manager in `opera://extensions` and enable the `allow to access to search pages results` option in the **Translate Web Pages** extension.
