### ISSUE TITLE
[FEEDBACK/REQUEST] Can someone please make a version/option that uses Lingva instead of Google Translate.

### ISSUE THREAD

**Issue by urajsingh** [FilipePS/Traduzir-paginas-web#269]
Lingva.ml is basically Google Translate without tracking. It works the same way. It also has a Public API.

Would be really nice if someone/author could make another version of this or an option to use Google Translate/Lingva.

Cheers to everyone and I apologize if its in the wrong section. Didn't know how to send some requests. :)

**Comment by FilipePS** [comment]
Here are all the answers as to why Lingva will not be added. https://github.com/FilipePS/Traduzir-paginas-web/issues/262
