### ISSUE TITLE
Firefox mobile not working

### ISSUE THREAD

**Issue by fily1212** [FilipePS/Traduzir-paginas-web#27]
With the last update of Firefox mobile, this plug in is not compatible and it is deactivate by Firefox. I hope you will extend the compatibility to have again this fantastic plug in on mobile

Thank you!

**Comment by FilipePS** [comment]
It's not my fault.  Mozilla is preventing the installation of any and all extensions other than those 9 recommended extensions.  They haven't even added a way for developers to test whether their extensions are compatible.  The only thing left to do is install an old version of Firefox or wait until they allow you to install more extensions.

**Comment by fily1212** [comment]
thank you for the fast reply! Do you know which is the last compatible firefox version? Maybe could be a good idea to write the name of this version in the firefox addon page or here in github in the readme. 
Hope firefox will allow fast!

**Comment by reyis4402** [comment]
It works fine thanks :) Much better than Chrom.
![Screenshot_20200826-132631_Iceweasel](https://user-images.githubusercontent.com/60405617/91292871-ce966300-e79f-11ea-9f7a-f564dd255c90.png)

**Comment by fily1212** [comment]
Hello! In which version? For me doesn't work.

**Comment by reyis4402** [comment]
https://github.com/interfect/fenix/releases

**Comment by rodrigoswz** [comment]
This is almost perfect, there is a bug and some things that can be optimized for mobile:

- Don't works on "custom tabs" (open Twitter > click on a link > try translate the page)
- There are two items in the extension menu with the same name and icon.
- When selecting a text and clicking the translator floating button, the translation window is displayed at the top of the screen

Anyway, this extension is incredible on both my phone and my computer. Thank you very much @FilipePS !
