### ISSUE TITLE
When using .crx file, I get 'CRX_HEADER_INVALID'

### ISSUE THREAD

**Issue by nicolaasjan** [FilipePS/Traduzir-paginas-web#274]
Version 9.4.1

So it doesn't install.

And when loading unpacked, I get error:
![screenshot1](https://user-images.githubusercontent.com/14093220/132042589-6fc809f9-4940-4acb-bee8-707f8f286a5e.png)

**Comment by nicolaasjan** [comment]
And when I make a .crx again of that unpacked extension, it installs without error.

**Comment by nicolaasjan** [comment]
Never mind, it seems new .crx was uploaded. 
Now it installs fine.

**Comment by FilipePS** [comment]
That error message is normal to appear, and does not affect the extension. After this issue I realized that the link in readme.md was wrong and corrected it.
