### ISSUE TITLE
[Feature request] Translating additional page elements 

### ISSUE THREAD

**Issue by tirphana** [FilipePS/Traduzir-paginas-web#275]
Is there a way to make it so your addon translates webpage elements that get inserted dynamically? The most popular examples of which would probably include youtube video descriptions (which get translated if you initiate page translation while only a small part of it is showing, but not otherwise) and wikipedia article popups (the ones that open on mouseover while reading a wiki page in a target language, because as of now, even though one translates the wiki page, those popups still appear in English).

**Comment by waggstoun** [comment]
This feature already exists:
![image](https://user-images.githubusercontent.com/39465679/132104305-e174aa84-f308-4df3-bd18-ec36aa8773e2.png)

**Comment by tirphana** [comment]
I'm an idiot, no idea why I had it set to off, thanks. Closing this.
