### ISSUE TITLE
trailing texts is missing when "Do not sort the google translate results" is enabled

### ISSUE THREAD

**Issue by azu** [FilipePS/Traduzir-paginas-web#280]
I noticed that this webextention only show first paragraph when "Do not sort the google translate results" is enabled.

## Problem

It show first paragraph that is translated, but rest paragraphs is missing.

Example page: https://github.blog/2021-09-09-analysis-developer-security-researcher-interactions-vulnerability-disclosure/

Original:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/19714/132775130-e335b0c0-154e-423b-9b84-61677c993d45.png">

> Continue exploration. We’ll be talking to security researchers about their experiences interacting with maintainers in the vulnerability disclosure process. This will help us gain a fuller understanding of stakeholders’ experiences in the process. Additionally, we asked preliminary questions during this study about how security is depicted through visuals and potential alternative imagery. We will further explore alternative descriptors and language that the Security Lab and the broader security research community can leverage as a way to attract developers.

Translated:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/19714/132775203-a6ab1814-4ab8-48f7-ba06-81ae9176a68a.png">

> Continúe la exploración. Hablaremos con los investigadores de seguridad sobre sus experiencias al interactuar con los mantenedores en el proceso de divulgación de vulnerabilidades. 

📝 This issue is occured when "Do not sort the google translate results" is enabled.

**Comment by FilipePS** [comment]
In the screenshot, it looks like everything has been translated.
I tested it and the entire site was translated.
Try clearing the translation cache.

**Comment by azu** [comment]
Thanks.

I've cleared the cache and get correct result.

**Comment by azu** [comment]
I missed that enable the option.

> Continue exploration. We’ll be talking to security researchers about their experiences interacting with maintainers in the vulnerability disclosure process. 

The above text is translated, but following texts is missed.

> This will help us gain a fuller understanding of stakeholders’ experiences in the process. Additionally, we asked preliminary questions during this study about how security is depicted through visuals and potential alternative imagery. We will further explore alternative descriptors and language that the Security Lab and the broader security research community can leverage as a way to attract developers.

This result was not changed by clearing the cache.

**Comment by azu** [comment]
I've created minimal reproduce example.

https://output.jsbin.com/lokicosesu

```
This is <a href="https://example.com">link</a>. Next line is disapper.
```

to be

```
Este es el enlace . 
```

**Comment by FilipePS** [comment]
This minimal page to reproduce helped a lot.

Bug fixed in this commit: https://github.com/FilipePS/Traduzir-paginas-web/commit/3bbc78b57a7f36d8083cccefb8755025d20bdf4d

**Comment by azu** [comment]
Thanks!
