### ISSUE TITLE
Youtube auto-translate + set default subtitle language Add-on

### ISSUE THREAD

**Issue by Maneeha1234SL** [FilipePS/Traduzir-paginas-web#289]
Hi, every time I watch a video in different languages ​​on YouTube, I have to press the CC button and then go to the translation options and select my language, which is very boring for those who spend a long time watching YouTube videos in different languages, It would be nice if this extension could be developed to enable sooooo i's + to automatically set the default auto-translate language

**Comment by FilipePS** [comment]
This is beyond the scope of this extension.
Try looking for another extension that does this.
