### ISSUE TITLE
Cause the site to crash

### ISSUE THREAD

**Issue by beifang721** [FilipePS/Traduzir-paginas-web#292]
@azu @flodolo @haiwx @VasaMM @spkprs 
![微信图片_20210929205341](https://user-images.githubusercontent.com/19699178/135272509-c70fe8c3-1b5f-4750-bbdd-a3a989f20c1c.png)
![微信图片_20210929205425](https://user-images.githubusercontent.com/19699178/135272516-f74e71c4-df74-4f25-9bc2-4625e72a2e49.png)

**Comment by flodolo** [comment]
Please don't ping random people, I'm not a developer for this add-on.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/issues/292
