### ISSUE TITLE
errors in chrome extension page

### ISSUE THREAD

**Issue by tortino** [FilipePS/Traduzir-paginas-web#294]
Hello,  have installed your extension v9.4.1 by using the "loading unpacked extension" method.
In the chrome extension management page I see an "errors" button for your extension, and clicking on it I see:

background/background.js:711 (disableTranslationOnClickingALink)
background/background.js:720 (funzione anonima)
lib/config.js:82 (funzione anonima)
lib/config.js:82 (twpConfig.set)
background/background.js:737 (funzione anonima)

Does these errors affect the functionality of your extension?
Thanks.

**Comment by FilipePS** [comment]
These errors do not affect anything, in the next version it will be hidden.
