### ISSUE TITLE
Cannot See Youtube Video Titles

### ISSUE THREAD

**Issue by tryfresh** [FilipePS/Traduzir-paginas-web#295]
![Screenshot 2021-10-05 at 11-24-28 YouTube](https://user-images.githubusercontent.com/59331917/135950554-4caefe46-4ea0-4526-9c5e-b411655cd960.png)
When I open YouTube and click the YouTube logo for the first time, the title always doesn't pop up.

![Screenshot 2021-10-05 at 11-32-35 【The Legend of Zelda BOTW】Remember Mumei #holoCouncil - YouTube](https://user-images.githubusercontent.com/59331917/135951218-34c2f3da-59f3-4cb0-839b-4141b024ac9f.png)
![Screenshot 2021-10-05 at 11-47-58 붕괴3rd '번개의 율자' TVC 영상 공개 - YouTube](https://user-images.githubusercontent.com/59331917/135952374-705143d8-9282-4c1c-8a44-ef0bfec8ec72.png)
In addition, there is a bug that sometimes the word "subscribe" on the subscribe button disappears and the number after like or dislike is not visible at the same time.
This usually happens when watching a YouTube live broadcast and clicking another video.

![Screenshot 2021-10-05 at 11-38-43 Rendermax Channel Rewind 2020 - GMV - Compilation - Happy New Year D - YouTube](https://user-images.githubusercontent.com/59331917/135951673-a9774183-07b8-486a-9b88-855150ba02c1.png)
And I want this English to be translated automatically. It's been half a year since I said this. 

There are a lot of bugs besides this, but it is the most inconvenient to not see the title and the like/dislike ratio.
It's not a crash with other extensions.
And I didn't sort the Google Translate results.
Thank you for always making great extensions.

**Comment by FilipePS** [comment]
So I think I can close this issue.
