### ISSUE TITLE
On auto-scroll sites, newly loaded parts are not translated

### ISSUE THREAD

**Issue by AlCooo** [FilipePS/Traduzir-paginas-web#3]
On auto-scroll sites (eg YouTube comments or Twitter), newly loaded parts are not translated.
![translate](https://user-images.githubusercontent.com/68498972/87872463-c5bdaf00-c9f3-11ea-8a2e-7c6b84f4f166.png)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/c70f5b3c0e42e641da82fc7e6161a470a048a335
