### ISSUE TITLE
"Release notes" page pops up at inappropriate times

### ISSUE THREAD

**Issue by AndreiMiculita** [FilipePS/Traduzir-paginas-web#30]
Sometimes [this page](https://filipeps.github.io/Traduzir-paginas-web/release_notes/) opens in a new tab while I am browsing (not necessarily while anything is being translated). Not sure if it's because of a recent update, but it opens quite a long time after the browser was started. You might want to open it right when the browser starts because it's a bit intrusive the way it is right now.

Using Firefox 80.0 on Linux Mint 20. It also happened in the previous version of Firefox.

**Comment by FilipePS** [comment]
This page opens when the extension is updated.

**Comment by AndreiMiculita** [comment]
Hey, sorry for the late reply.

I suppose the extension is being updated while I am browsing, and that's why it's interrupting me. I have "Update Add-ons automatically" turned on, so that's probably why. I'm pretty sure it's the default setting, so I think a setting like: "Don't show release notes after updating" for this extension would be useful.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/bf8d251f377b90c6913f501211d8800c810e1556
