### ISSUE TITLE
Translation does not work

### ISSUE THREAD

**Issue by ahmetcadirci25** [FilipePS/Traduzir-paginas-web#303]
Hi,

Version 9.4.1 text translation does not work. Is there a problem?

![Ekran görüntüsü 2021-10-16 120229](https://user-images.githubusercontent.com/9280397/137581594-efdedd9b-95a1-495a-9431-8895e829200c.png)

**Comment by FilipePS** [comment]
I think this issue was created after Bing stopped working entirely in the extension. If so, it has already been fixed in this commit [""](https://github.com/FilipePS/Traduzir-paginas-web/commit/77f104f32ac3f8f9eb28c6cc28d87ba7f562691b), and the fix will be in the next version.
