### ISSUE TITLE
Firefox Mobile

### ISSUE THREAD

**Issue by felipefacundes** [FilipePS/Traduzir-paginas-web#31]
Support the new firefox mobile 79.0.5?

**Comment by FilipePS** [comment]
It is not the extension that is not compatible with the new Firefox.  It is the new firefox that is not compatible with other extensions.  Currently the new Firefox supports only 9 extensions.

**Comment by B0pol** [comment]
It is available in Iceweasel mobile:
https://github.com/interfect/fenix

**Comment by felipefacundes** [comment]
thanks B0pol
