### ISSUE TITLE
PDF translation only translates to Portuguese (not a target language for me)

### ISSUE THREAD

**Issue by Sannoso** [FilipePS/Traduzir-paginas-web#312]
I try to translate a Finnish pdf to English:
https://www.vahvike.fi/sites/default/files/perussivu-pdf/Selkoteksti_7.pdf
When that is opened in Firefox 94.0 (64-bit) (up to date) and I click on the translate button, this message appears:
Select a service to do this conversion
I click on translate.googleusercontent.com
and a new page will open with a HTML version, but then translated to Portuguese. Which isn't my target language and has never been before.
https://translate.googleusercontent.com/translate_f

Great tool BTW. If you want more contributors perhaps add a textfile explaining how to get started on contributing.

**Comment by CaganAgabey** [comment]
Google automatically tries to translate the document every time. Try Translate Web Pages service or translate via the extension again.

**Comment by Sannoso** [comment]
I don't know what you mean by this.

"Google automatically tries to translate the document every time."
I find it likely that there is a setting somewhere that hardcodes the target language to portugese, because the owner of this repo is a portugese speaker and translates everything to portugese to test it probably.
I don't know what google translate automatically translating things has to do with this?

"Try Translate Web Pages service"
The Translate Web Pages service gives me: "Internal server error" .

"Translate via the extension again"
Trying to get a translation from the extension again gives me the exact same results. A internal server error for the translatewebpages.org option and a portugese translation if I choose the "https://translate.googleusercontent.com/" option.

**Comment by FilipePS** [comment]
> "Try Translate Web Pages service" The Translate Web Pages service gives me: "Internal server error" .
> 

Do you still have this internal error on the server?
Could you send me the link to this PDF document?

**Comment by Sannoso** [comment]
https://www.vahvike.fi/sites/default/files/perussivu-pdf/Selkoteksti_7.pdf

**Comment by Sannoso** [comment]
It does this too for other pdfs. Are you able to recreate the situation?

**Comment by CaganAgabey** [comment]
@FilipePS looks like the problem is with the TWP website, not with the extension. I can recreate it too but in just some pdfs.

**Comment by Sannoso** [comment]
The other bug still remains. The translate.googleusercontent.com/ option translates into Portugese instead of English (my target language). Can you also recreate that? Or should that be fixable on my side? Will reinstalling the plugin and/or is there some settings files that I can delete from somewhere to setup things again?

**Comment by FilipePS** [comment]
Try again

**Comment by CaganAgabey** [comment]
It works flawlessly for me now

**Comment by Sannoso** [comment]
Nice. The translatewebpages.org option works flawless for me now.
The google.translate option still translates to portugese though.

**Comment by CaganAgabey** [comment]
> The other bug still remains. The translate.googleusercontent.com/ option translates into Portugese instead of English (my target language). Can you also recreate that? Or should that be fixable on my side? Will reinstalling the plugin and/or is there some settings files that I can delete from somewhere to setup things again?

I think we can't do anything about this. Google's document conversion system forces the document to translate to the API request's language. You can use Translate Web Pages or translate the document output again with the extension.

**Comment by FilipePS** [comment]
Bug fixed

**Comment by Sannoso** [comment]
From the file  Traduzir-paginas-web/popup/popup-translate-document.html 
    <form action="https://translate.googleusercontent.com/translate_f" method="POST" target="_blank" enctype="multipart/form-data" id="form_google" style="display: none;">
        <input type="text" name="hl" value="pt-BR">
        <input type="text" name="ie" value="UTF-8">
        <input type="text" name="js" value="y">
        <input type="text" name="prev" value="_t">
        <input type="text" name="sl" value="auto">
        <input type="text" name="tl" value="pt">
        <input type="file" name="file">
        <input type="submit" value="Submit">
    </form>
line 75.
        <input type="text" name="tl" value="pt">
Shouldn't here the target language be change from value "pt" to the target language set in the settings?
