### ISSUE TITLE
Machine translation no longer works in Edge

### ISSUE THREAD

**Issue by boromyr** [FilipePS/Traduzir-paginas-web#315]
Hi, the machine translation no longer works with the Edge version "Version 97.0.1060.2 (Official Build) dev (64 bit)",
while still functioning in 95.0.1020.44. In particular, the "Always translate from..." button is no longer available in version 97.
In 95:
![image](https://user-images.githubusercontent.com/52782032/140613237-293773c2-c538-4eeb-8bdc-81f7c3af387a.png)
In 97:
![image](https://user-images.githubusercontent.com/52782032/140613452-bfb4d161-97b3-48f6-be16-43b7aa42d2a3.png)

Control tests performed:
- restore extension settings and complete reinstallation;
- testing in Edge 95 in first configuration, no other extensions active;
- Test in Edge 97, new profile, no other extensions active;
OS: Windows 11

**Comment by CaganAgabey** [comment]
Thanks for reporting this issue.

**Comment by FilipePS** [comment]
This seems to be the same as what happened with the opera. An issue related to language detection API.
This is likely to be happening with all chromium based browsers.

**Comment by boromyr** [comment]
Okay, thanks. In the meantime, I fixed the problem by reverting to the stable version of Edge 96. So the issue will probably recur with updates 97 and later?
