### ISSUE TITLE
always translate this site list for Firefox android

### ISSUE THREAD

**Issue by samlux04** [FilipePS/Traduzir-paginas-web#318]
Since Mozilla don't allow language detection on mobile, so always translate page don't work either. Can we have a list of website to always translate instead?
For example ncode.syosetu.com
Thanks.

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
