### ISSUE TITLE
Add "copy" translation button

### ISSUE THREAD

**Issue by aha999** [FilipePS/Traduzir-paginas-web#319]
It would be very useful if we could copy the entire translated text with one button, instead of having to select it all and then press copy in a system context menu.

**Comment by CaganAgabey** [comment]
To the translation pop-up menu?

**Comment by aha999** [comment]
> To the translation pop-up menu?

yes, somewhere here would be nice:
![image](https://user-images.githubusercontent.com/50620416/142277485-b1de636d-5367-438a-ac7c-326983a8e902.png)

**Comment by CaganAgabey** [comment]
I sent a pull request that revamps this menu, added a copy button too
