### ISSUE TITLE
[Mobile] the translate bar is too small sometimes

### ISSUE THREAD

**Issue by B0pol** [FilipePS/Traduzir-paginas-web#32]
Using [Iceweasel mobile](https://github.com/interfect/fenix), spelling liberation version.

On https://mozilla.github.io/standards-positions/ , it follows the page width, not the device width, therefore it's too small & you must unzoom or you won't see it.

<img src="https://i.ibb.co/fCvBK0G/Screenshot-20200903-105808-Iceweasel.png" width="300">

**Comment by FilipePS** [comment]
I've known you since always. But I still haven't found a solution.

**Comment by FilipePS** [comment]
Extension has always had this problem and I never found a solution.
It is a problem related to page scaling on mobile devices.
