### ISSUE TITLE
Extension Only Translates To The First Target Language

### ISSUE THREAD

**Issue by ganon69** [FilipePS/Traduzir-paginas-web#321]
I've noticed recently that the extension is translating only to the first target language on the list. The others are being ignored. Pls advise. Thx.

**Comment by CaganAgabey** [comment]
Other target languages are used in text translation. Anyway, you can use the "Change languages" menu (press three dots in the extension popup and you'll see it) to change page translation language without entering to extension settings.

**Comment by ganon69** [comment]
Ok, thx. Will you ever include other target languages for page translation...? That would be great.


________________________________

**Comment by CaganAgabey** [comment]
Also, I just noticed this, you can see other target languages if you press More in the new interface.

**Comment by ganon69** [comment]
Yes, that's right. This is really the best translation extension I've seen so far for Android👍


________________________________
