### ISSUE TITLE
Unable to copy translated text from the site https://outlook.live.com/mail/

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#328]
For clarity, I will show you a picture taken from my mail https://outlook.live.com/mail/
![Screenshot_2](https://user-images.githubusercontent.com/17863616/143495056-443096a2-4be4-477f-91b9-602bd0ac2df5.png)
   I did not notice this bug on other sites.

**Comment by CaganAgabey** [comment]
The new version of the pop-up (not yet released) will completely revamp this pop-up, with a copy button. This copy button will work everywhere.
