### ISSUE TITLE
Suggestion to make a hotkey for inserting translated text

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#329]
A suggestion to make a hotkey (for example Ctrl + Q) or button to insert translated text instead of typed text. It would be convenient to press a hotkey to replace the original text. That would be fantastically handy!
![Screenshot_3](https://user-images.githubusercontent.com/17863616/143497174-8bb955e7-2eea-400c-92e3-b6988ee34c95.png)
.

**Comment by VladimirCo** [comment]
Missing this killer-feature, it is sooooo handy.
 Is this feature ever implemented? 🙏

**Comment by FilipePS** [comment]
I feel like I already responded to an issue like this.

1 - If the translated text is not to appear in a popup, why not use the page translation directly?
2 - Would you like to make an edit to the text or do you just want the mouse to be translated?

Depending on the answer it can be tricky to implement something like this.

**Comment by VladimirCo** [comment]
I see you didn't understand me at all.
   The idea is to make possibility to translate the text you write, using the button where the arrows in the screenshot are indicated. 
   Why is this needed?  Imagine that you are texting with a Frenchman.  And your native language is Spanish.  You write a letter in Spanish - you press the button and the translated text is replaced by Spanish.  It's very convenient.
  This feature is well implemented in iOS 15, where you can write text in any application and replace it with a translated one with a button.  Here's what it looks like:
  ![index](https://user-images.githubusercontent.com/17863616/184429036-61482614-f313-435a-83b9-97da9d6ed069.png)

**Comment by FilipePS** [comment]
This is what you want? because this is already implemented in the extension.
![image](https://user-images.githubusercontent.com/54990796/184432355-a73e250c-2f21-4d31-a37f-f3a094d82805.png)

**Comment by FilipePS** [comment]
I think now I understand what you meant.
The way to use this feature would be something like this:
1. Click on the site location to enter text.
2. Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel.
3. Type something in your language.
4. Press any shortcut key to insert the translated text on the website (where you type the message).
5. The extension panel will close automatically. (is this desired?)

**Comment by VladimirCo** [comment]
> I think now I understand what you meant.
> 
> The way to use this feature would be something like this:
> 
> 1. Click on the site location to enter text.
> 
> 2. Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel.
> 
> 3. Type something in your language.
> 
> 4. Press any shortcut key to insert the translated text on the website (where you type the message).
> 
> 5. The extension panel will close automatically. (is this desired?)

  Yes, it can be implemented as you say.

  You can also add a button as in the arrow screenshot to replace the translated text.

**Comment by VladimirCo** [comment]
> 
I thought a while and desire it would be more convenient to create by this steps:

1 -  Click on the site location to enter text. 
2 -  Type something in your language
3 -  Highlight this text
4 -  Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel.
5 -  Press hotkey for inserting translated text on the website (where you type the message)
6 -  The extension panel will close automatically.

Hotkey for inserting translated text put like on this screenshot
![143497174-8bb955e7-2eea-400c-92e3-b6988ee34c95](https://user-images.githubusercontent.com/17863616/184478977-62d3d87e-ce50-46c1-b626-8c011286b614.png)

**Comment by VladimirCo** [comment]
> I think now I understand what you meant. The way to use this feature would be something like this:
> 
>     1. Click on the site location to enter text.
> 
>     2. Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel.
> 
>     3. Type something in your language.
> 
>     4. Press any shortcut key to insert the translated text on the website (where you type the message).
> 
>     5. The extension panel will close automatically. (is this desired?)

 
 I thought a while and desire it would be more convenient to create by this steps:
 
1 - Click on the site location to enter text.
2 - Type something in your language
3 - Highlight this text
4 - Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel.
5 - Press hotkey for inserting translated text on the website (where you type the message)
6 - The extension panel will close automatically.

 Hotkey for inserting translated text put like on this screenshot ![143497174-8bb955e7-2eea-400c-92e3-b6988ee34c95](https://user-images.githubusercontent.com/17863616/184478977-62d3d87e-ce50-46c1-b626-8c011286b614.png)

**Comment by VladimirCo** [comment]
In order for it works as much conveniently as in the message above, necessary to implement and this: https://github.com/FilipePS/Traduzir-paginas-web/issues/455

**Comment by FilipePS** [comment]
Version 9.6-beta-0 was released with this feature.
Please test it.
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6-beta-0

**Comment by VladimirCo** [comment]
> Version 9.6-beta-0 was released with this feature. Please test it. https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6-beta-0 https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6-beta-1

Tested. 
  I don't see any difference from the previous version except new setting in the add-on menu "Replace selected text text with translated text when pressing CTRL twise".
  Bro Please read this post carefully https://github.com/FilipePS/Traduzir-paginas-web/issues/329#issuecomment-1214131894 and this https://github.com/FilipePS/Traduzir-paginas-web/issues/329#issuecomment-1214133844

**Comment by VladimirCo** [comment]
For clarity, take iPhone iOS 15 and higher - you will see the implementation of this idea by Apple. https://github.com/FilipePS/Traduzir-paginas-web/issues/329#issuecomment-1213444061

**Comment by VladimirCo** [comment]
хорошая жизнь

**Comment by FilipePS** [comment]
Maybe I don't explain how they work correctly.

After selecting the text, translate the selected text.
You will notice that instead of the button to copy the translated text, there is a button to replace the selected text with the translated one (for this you can also press Ctrl twice if you activated this option.)

Please note that it is currently not working on facebook. This is because facebook does not use input or textarea for text input.

**Comment by VladimirCo** [comment]
> Maybe I don't explain how they work correctly.
> 
> After selecting the text, translate the selected text. You will notice that instead of the button to copy the translated text, there is a button to replace the selected text with the translated one (for this you can also press Ctrl twice if you activated this option.)
> 
> Please note that it is currently not working on facebook. This is because facebook does not use input or textarea for text input.

ahh, now I understand!
 yes, I see how it works.  I see on some sites it really does not work, for example on reddit. 
  But I see one strange bug, for clarity, I recorded a video so that you can see the bug with your own eyes:
https://www.youtube.com/watch?v=D_Lk5fC_AHI
sites from the video:
1. https://www.ixbt.com/news/2022/09/13/apple-watch-ultra.html
2. https://dzen.ru/media/cyber_cab/kak-uskorit-staryi-iphone-631f97d1ec26cd63c1eab4c5?&
3. https://makler.md/

**Comment by VladimirCo** [comment]
Just in case I should repeat, In order this function works more conveniently - necessary to implement and this: https://github.com/FilipePS/Traduzir-paginas-web/issues/455

**Comment by VladimirCo** [comment]
> I thought a while and desire it would be more convenient to create by this steps:
> 
>
1 - Click on the site location to enter text. 
2 - Type something in your language
3 - Highlight this text
4 - Press "Ctrl+Alt+S" to open the "Translate Selected Text" panel. 
5 - Press hotkey for inserting translated text on the website (where you type the message) 
6 - The extension panel will close automatically.
> 
> Hotkey for inserting translated text put like on this screenshot

if you do (wish you did :) ) https://github.com/FilipePS/Traduzir-paginas-web/issues/455, it will be fantastically convenient to have a hot button for instant insertion of translated text, for example, using the keyboard shortcut: CTRL + ALT + X.
This combination of keys would replace points 4, 5 and 6

**Comment by FilipePS** [comment]
> if you do (wish you did :) ) #455, it will be fantastically convenient to have a hot button for instant insertion of translated text, for example, using the keyboard shortcut: CTRL + ALT + X. This combination of keys would replace points 4, 5 and 6 from this my message: [#329 (comment)](https://github.com/FilipePS/Traduzir-paginas-web/issues/329#issuecomment-1214131894)

So pressing `Ctrl+Alt+X` wouldn't show any popup? would the text already appear translated?

**Comment by VladimirCo** [comment]
> > if you do (wish you did :) ) #455, it will be fantastically convenient to have a hot button for instant insertion of translated text, for example, using the keyboard shortcut: CTRL + ALT + X. This combination of keys would replace points 4, 5 and 6 from this my message: [#329 (comment)](https://github.com/FilipePS/Traduzir-paginas-web/issues/329#issuecomment-1214131894)
> 
> So pressing `Ctrl+Alt+X` wouldn't show any popup? would the text already appear translated?

Yes, text should appear already translated without any popup by clicking CTRL + ALT + X (or any custom keyboard shortcut)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6-beta-2

**Comment by VladimirCo** [comment]
> https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6-beta-2

Yesterday I updated the add-on and I started testing it. Great update!
   BUT, it turned out that the hotkeys CTRL + ALT + X (or CTRL + ALT + S) don't work in the Russian layout - which is a flaw.  Because of what, all meaning from hot keys is lost
How it looks: https://www.youtube.com/watch?v=RcOFgBwYaUo
Fix this please🙏 Thanks in advance

**Comment by FilipePS** [comment]
These shortcut keys are managed by the browser. The only thing I could do is set another hotkey. But I've tried to do this in the past, it always doesn't work for someone.
Go to the extension's `Hotkeys` settings and configure a hotkey that works for you.
If successful, let me know.

**Comment by VladimirCo** [comment]
> These shortcut keys are managed by the browser. The only thing I could do is set another hotkey. But I've tried to do this in the past, it always doesn't work for someone. Go to the extension's `Hotkeys` settings and configure a hotkey that works for you. If successful, let me know.

I didn't find such a combination :(

**Comment by FilipePS** [comment]
Maybe you are trying do set a hotkey used by other extension. Open the extension manger `about:addons` and:
![image](https://user-images.githubusercontent.com/54990796/193264174-22053483-be4e-461e-8400-9818af6e003b.png)
And try setting your hotkey over there.

**Comment by VladimirCo** [comment]
> Maybe you are trying do set a hotkey used by other extension. Open the extension manger `about:addons` and: ![image](https://user-images.githubusercontent.com/54990796/193264174-22053483-be4e-461e-8400-9818af6e003b.png) And try setting your hotkey over there.

no - I know about it
just see that the Russian layout is impossible to put a hotkey of letters.

**Comment by FilipePS** [comment]
Enter using numbers then like: `Ctrl+Shift+7`
