### ISSUE TITLE
Issue: No translation visible at the bottom of the page

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#330]
Very often, if you want to make a translation at the bottom of the page, its translation is simply not visible. Especially when the translation is large! For illustration, I am attaching two screenshots. Make it higher by default, please.
![Screenshot_1](https://user-images.githubusercontent.com/17863616/143886427-18648fce-c3ce-4d60-b408-4635e18a2e72.png)
![Screenshot_2](https://user-images.githubusercontent.com/17863616/143886430-e51ec63e-0aa5-4a7e-a899-889b2aa83724.png)

**Comment by VladimirCo** [comment]
I would like to add that this bug is common on many sites

**Comment by CaganAgabey** [comment]
Thanks for reporting this problem.

**Comment by FilipePS** [comment]
Does this issue only occur when clicking the popup expand/collapse buttons?
If so, this issue has been fixed in this commit https://github.com/FilipePS/Traduzir-paginas-web/commit/49db76ef175c6cd16b7e2ee37dc727289469f579

**Comment by VladimirCo** [comment]
> Does this issue only occur when clicking the popup expand/collapse buttons? If so, this issue has been fixed in this commit [49db76e](https://github.com/FilipePS/Traduzir-paginas-web/commit/49db76ef175c6cd16b7e2ee37dc727289469f579)

 not only! 
  It happens everywhere when you make translation at the bottom of the page, EVEN if collapse buttons. Just zoom in and highlight the text at the bottom of the page and you get the same bug.  Make it higher by default, please. Look it once again
![Screenshot_1](https://user-images.githubusercontent.com/17863616/145710525-3f25f630-951a-4b98-9b56-424806af504f.png)

**Comment by CaganAgabey** [comment]
Calm down, it is fixed with a new commit.

12 Ara 2021 Paz 14:34 tarihinde VladimirCo ***@***.***> şunu
yazdı:
