### ISSUE TITLE
Suggestion: Make language detection automatic - not manual.

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#332]
When we highlight text, we have to manually press the button for choose translation language. Why not make language detection automatic? For example if there is a translation between EN and RU, and the text is highlighted in RU - it is logical what I want is translate to EN - and vice versa, if the text is highlighted in EN - then it is logical should translate into RU.
  I know that when I select DeepL everything works automatically. But in Google Translate and Yandex Translate we have to choose manually. 
  P.S. In general DeepL is very good as a translator, maybe - the best translator! But it always opens a new tab in the browser. It would be more convenient for DeepL not to open a new tab in the browser.

**Comment by FilipePS** [comment]
The extension does not always detect the language correctly.
There are users who like to translate into more languages, so it's hard to know which target language they want.
This feature will not be adding.

**Comment by VladimirCo** [comment]
In this case, see what happens. The add-on is only good for people who need to translate into more languages. But they are in the minority!
  And the majority of people who use only two languages - and for them, the automatic determination of the language would be more convenient and faster - because this saves time. And it's just more comfortable.
  In this case, you can make a setting (checkbox) - "enable automatic language detection" as it is already implemented in DeepL, and even if the extension is not always right language detection - you could specify (BETA) and users would be glad that you gave them the choice to use this function. Because now there is no choice at all
