### ISSUE TITLE
Russian to Spanish Translation Issue

### ISSUE THREAD

**Issue by pabloarod** [FilipePS/Traduzir-paginas-web#336]
There is a recurent issue when translating from Russian to Spanish (Castellano), it translate the corresponded term "Ship" to _Barco_ (spanish) that is ok for most cases but somehow inacurate for space subjects. Using the translate tool on [roscosmos.ru](https://www.roscosmos.ru/) the issue shows many times everytime a "Ship" -> _Nave (spanish)_. Altho ship is "barco" in a global sence is better to translate it as Nave since it could be ether one of the both types.
![Captura de pantalla 2021-12-10 a las 12 13 43](https://user-images.githubusercontent.com/47468335/145596692-abd5dee7-064a-4dfe-884e-9694152b17c1.png)

**Comment by CaganAgabey** [comment]
Translate Web Pages extension doesn't have its own translation engine, so it uses various translation services such as Google Translate, Yandex Translate etc. This is not an issue related to this extension, it's related to the used translation service. You can report this problem on their own websites. Also, you can switch between translation services on the extension popup.

**Comment by FilipePS** [comment]
I don't think I can do anything about it. I am closing this issue.
