### ISSUE TITLE
I get some errors when loading in Chrome or Vivaldi

### ISSUE THREAD

**Issue by Hayao0819** [FilipePS/Traduzir-paginas-web#34]
After editing the Manifact according to the README and reading the directory in Developer mode, the following error is displayed.
However, if you ignore the error, the extension will still work. (Not all features have been tested.)

![スクリーンショット_2020-09-05_11-01-46](https://user-images.githubusercontent.com/32128205/92294470-7dd4f600-ef67-11ea-88bd-d34d5b6817b8.png)
![スクリーンショット_2020-09-05_11-01-59](https://user-images.githubusercontent.com/32128205/92294472-7f062300-ef67-11ea-9d53-f0772a4139a7.png)

**Comment by FilipePS** [comment]
This error does not affect the operation of the extension.
