### ISSUE TITLE
Dark Icon in URL Bar

### ISSUE THREAD

**Issue by thunderstone135** [FilipePS/Traduzir-paginas-web#343]
Hi, is it possible to make the icon of this extension use the same color as the other icons?

![Untitled](https://user-images.githubusercontent.com/96173732/146157135-f3a0e214-b972-434f-aa11-591b921e08c1.png)

By the way, I'm using version 9.4.2.

**Comment by GrayRats** [comment]
+ same problem...

**Comment by thunderstone135** [comment]
After updating to 102 ESR along with the addon to version 9.5.5, it's now showing the right color.
This very much solves my issue, so I'm going ahead and close this thread. Au revoir.
