### ISSUE TITLE
Optional permissions not available on Android so affected features do not work

### ISSUE THREAD

**Issue by embeddedtofu** [FilipePS/Traduzir-paginas-web#345]
https://bugzilla.mozilla.org/show_bug.cgi?id=1601420

Fenix still does not support optional permissions so the 'keep translating on current domain' option is not available.

For a similar reason some developers have uploaded a secondary version of their addons with all permissions set on install. I hope this could be done here as well.

This addon does not offer the option to keep the bar visible for specific sites or per session, you can't rely on shorcuts on mobile, and display space is a lot more valuable, so this an a bit more important feature there than on a desktop.

**Comment by Guest126** [comment]
This bug has been fixed in GeckoView 102. However, additional permissions are still not available in TPW. Do we need to work on anything else?

**Comment by Bardock88** [comment]
Apparently it's something to fix, but the error comes back soon after a new version of the FF Android build. It will take rigorous study and keen observation to resolve this very recurring situation.

**Comment by FilipePS** [comment]
> This bug has been fixed in GeckoView 102. However, additional permissions are still not available in TPW. Do we need to work on anything else?

In some version of Firefox nightly did it work?

**Comment by Guest126** [comment]
> In some version of Firefox nightly did it work?

No, it will probably not work. [Bug 1601420](https://bugzilla.mozilla.org/show_bug.cgi?id=1601420) was closed, but mozilla-mobile/fenix/issues/16912 is still open. I tried the simple extension used to test bug 1601420 and concluded that the necessary change were not made to fenix or web-ext can not testing for permissions.

Instead I forked and hacked the TPW extension as [issuecomment-792756815](https://github.com/mozilla-mobile/fenix/issues/16912#issuecomment-792756815) says. The point is webNavigation additional permissions mandatory. In fact, [Bypass Paywalls Firefox Clean](https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean) uses a similar workaround.

> You can also install the custom add-on version (with host permissions for all sites): [Bypass Paywalls Clean (c)](https://addons.mozilla.org/firefox/addon/bypass-paywalls-clean-custom)

> Custom add-on version with default access to all sites (to enable custom sites on Firefox Android which has no optional permissions)

So...this works fine!

- https://addons.mozilla.org/firefox/addon/translate-web-pages-custom/
- https://github.com/Guest126/Traduzir-paginas-web-custom/commit/cb5ff655ef39e26d572a20a09e1c660e355344df

Would you consider this workaround?

**Comment by FilipePS** [comment]
To fix this problem you need to use another version of the extension, on your Firefox for Android, uninstall the current version of TWP and follow these steps.

To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
