### ISSUE TITLE
Resist fingerprinting compatibility

### ISSUE THREAD

**Issue by tirphana** [FilipePS/Traduzir-paginas-web#350]
Hello,

Popup translating doesn't seem to work with `privacy.resistFingerprinting` set to true in FF, the full-page translation however still works as usual.

**Comment by FilipePS** [comment]
I have tested it here and it seems to be working. Which site is not working for you?

**Comment by tirphana** [comment]
You're right, I rushed with reporting since I just tested it on a fresh profile and there doesn't seem to be an issue. On my main profile however, no site is working (until I toggle RFP off) and I have no clue what might be interfering or causing it to do that... Feel free to close this if you have no idea/solution for it off the top of your head, guess I'm in for some long-a*s troubleshooting.
