### ISSUE TITLE
Use SimplyTranslate as a private Translation Service

### ISSUE THREAD

**Issue by ManeraKai** [FilipePS/Traduzir-paginas-web#358]
[SimplyTranslate](https://simplytranslate.org/) is like [Invidious](https://invidious.io/), [Nitter](https://github.com/zedeus/nitter), [Bibliogram](https://bibliogram.art/). Worldwide instances fetch data from [GoogleTranslate](https://translate.google.com/), [LibreTranslate](https://libretranslate.com/) instances, [Deepl](https://www.deepl.com/translator), [ICIBA](https://www.iciba.com/fy), [Reverso](https://www.reverso.net/text-translation) for the users. This may help in making translations more private.
Using multiple random [instances](https://simple-web.org/instances/simplytranslate) for one **Page Translation** will help a lot with obfuscating what pages the user is viewing.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Hi, just dropping in to say this would be a really cool feature!

This extension works really well, and it would be nice to optionally use a more privacy respecting backend.

**Comment by ManeraKai** [comment]
Great! If you face any problem with the API. I'm here to help 👍️

**Comment by FilipePS** [comment]
> Great! If you face any problem with the API. I'm here to help 👍️

Is your repository only for mobile or also web?
How to build in an Ubuntu instance?

**Comment by ManeraKai** [comment]
My own repo (simplytranslate_mobile) is just a mobile client for SimplyTranslate instances.
For the normal SimplyTranslate (the server app), here's how to install it: https://codeberg.org/SimpleWeb/SimplyTranslate-Web#how-to-install-use
