### ISSUE TITLE
No translate option in the context menu

### ISSUE THREAD

**Issue by lnicola** [FilipePS/Traduzir-paginas-web#36]
![image](https://user-images.githubusercontent.com/308347/92568295-a458a100-f287-11ea-93df-30e0f083871f.png)

![image](https://user-images.githubusercontent.com/308347/92568504-f1d50e00-f287-11ea-82af-97f365bd4787.png)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/issues/36
