### ISSUE TITLE
Support for Simply Translate.

### ISSUE THREAD

**Issue by Loki-L1130** [FilipePS/Traduzir-paginas-web#366]
Please add support for Translation frontends such as SimplyTranslate and LibreTranslate or a way where I could use my Instance's API as the Translation service in the extension.

**Comment by ManeraKai** [comment]
related: #358

**Comment by FilipePS** [comment]
> Please add support for Translation frontends such as SimplyTranslate and LibreTranslate or a way where I could use my Instance's API as the Translation service in the extension.

I can implement right now a version that uses your instance, just for testing. But you may be disappointed with the speed of translation.
If you want to do this privately, send an email to: **_contact@translatewebpages.org_**

**Comment by Loki-L1130** [comment]
Okay, I will contact when I have my Instance fully running. Closing for now.

**Comment by schklom** [comment]
@FilipePS I have an instance running. I can send you an API key for testing if you are still up for it.

**Comment by FilipePS** [comment]
> @FilipePS I have an instance running. I can send you an API key for testing if you are still up for it.

An instance of LibreTranslate? because it doesn't make much sense to use "Simply Translate".

**Comment by schklom** [comment]
@FilipePS Yes, an instance of LibreTranslate.

**Comment by schklom** [comment]
@FilipePS Why was this closed? I was waiting for you to say you were still up for it :P

I have invited you to collaborate on a private repo in order to privately send you the LibreTranslate website and the API key.
