### ISSUE TITLE
Option to set some languages as never translate

### ISSUE THREAD

**Issue by AlbertoFabbri93** [FilipePS/Traduzir-paginas-web#37]
According to me it would be very useful if you could add an option to disable the translation for one or more languages apart from the target one.
In my case I speak english and italian and my target language is English so for every Italian website I'm being asked if I want it translated into English, and it is useless to me. Adding every Italian website to the "never translate list" is time consuming.

**Comment by FilipePS** [comment]
Do you use Firefox Mobile?

**Comment by AlbertoFabbri93** [comment]
No, I'm using this extension on the desktop version. This extension is not available for the beta channel of Firefox Mobile, which I'm currently using.

**Comment by FilipePS** [comment]
Unless you specify to always translate this site or language, the site will not be translated automatically. So what is the real meaning of this option?

**Comment by AlbertoFabbri93** [comment]
I seemed to remember that the extension automatically asked the user if he or she wanted to translate the webpage. This does not happen now so I think you are right, this option is not necessary.
