### ISSUE TITLE
Waterfox - Icon is white on white...

### ISSUE THREAD

**Issue by jburf** [FilipePS/Traduzir-paginas-web#383]
The latest version of Waterfox has a "Force Dark Mode" option, which is easier on the eyes on some websites. When in that mode, the Translate icon in the address bar is basically invisible (white on white). Since the blue icon IS visible on a translated page, perhaps you can offer a colored icon option?  Thanks!

**Comment by FilipePS** [comment]
This problem was resolved a while ago.
