### ISSUE TITLE
translate select box

### ISSUE THREAD

**Issue by saeedvaziry** [FilipePS/Traduzir-paginas-web#386]
The extension is not translating select boxes (`select` tags)

**Comment by lfoppiano** [comment]
It seems a regression as it was working a while ago (can't remember when) 

I add an example: 

![image](https://user-images.githubusercontent.com/15426/161878534-1b4cf230-276c-43c6-a918-7a0674efa04b.png)

**Comment by FilipePS** [comment]
Fixed in this commit: https://github.com/FilipePS/Traduzir-paginas-web/commit/bde4059a2dd7a71f17d639525e5c92ea65a3979c
