### ISSUE TITLE
[BUG] Ao selecionar 'Traduzir automaticamente ao clicar em um link que leva você para o mesmo domínio do site atual' para Sim

### ISSUE THREAD

**Issue by Bardock88** [FilipePS/Traduzir-paginas-web#392]
Aqui está um vídeo que fiz demonstrando a falha da escolha da opcão de **Não** para **Sim**:

https://user-images.githubusercontent.com/102046116/168611009-9cc93893-78a3-4983-b616-06e811ccf17c.mp4

**Comment by Guest126** [comment]
Selecting "Yes" requires additional permissions. This is a known limitation.

See also #345

**Comment by Bardock88** [comment]
> Selecionar "Sim" requer permissões adicionais. Esta é uma limitação conhecida.
> 
> Veja também [#345 ](https://github.com/FilipePS/Traduzir-paginas-web/issues/345)

Oh yes, thank you, for your help in showing me about this old reported 'issue'.
I'll take a look.

**Comment by Bardock88** [comment]
Apparently it's something to fix, but the error comes back soon after a new version of the FF Android build. It will take rigorous study and keen observation to resolve this very recurring situation.

**Comment by FilipePS** [comment]
> Apparently it's something to fix, but the error comes back soon after a new version of the FF Android build. It will take rigorous study and keen observation to resolve this very recurring situation.

Was there a specific version that worked?

**Comment by FilipePS** [comment]
To fix this problem you need to use another version of the extension, on your Firefox for Android, uninstall the current version of TWP and follow these steps.

To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
