### ISSUE TITLE
FF extension "Translate Web Pages": Google translater break HTML

### ISSUE THREAD

**Issue by WinterSilence** [FilipePS/Traduzir-paginas-web#398]
[Link to tests](https://docs.rubixml.com/2.0/neural-network/activation-functions/softmax.html)

## Before:
![изображение](https://user-images.githubusercontent.com/3521094/168421564-fd4177a6-cb29-4af0-ac98-a51cb7883f0b.png)

## After:
![изображение](https://user-images.githubusercontent.com/3521094/168421510-fc5eb5ed-3e5f-45f9-b5f0-08870c0bad1a.png)

**Comment by FilipePS** [comment]
I checked here and it's a problem with google translator itself, not my extension.

The request is made like this:
`<pre><a i=0>The Softmax function is a generalization of the </a><a i=1>Sigmoid</a><a i=2> function that squashes each activation between 0 and 1 with the addition that all activations add up to 1. Together, these properties allow the output of the Softmax function to be interpretable as a </a><a i=3>joint</a><a i=4> probability distribution.</a></pre>`

And the google translator response is like this:
`[ "<pre><a i=0>Функция Softmax является обобщением функции Sigmoid</a> <a i=1>,</a> <a i=2>которая сжимает каждую активацию между 0 и 1 с добавлением того, что все активации в сумме дают 1. Вместе эти свойства позволяют интерпретировать вывод функции Softmax как</a> <a i=3>совместное</a> <a i=4>распределение вероятностей.</a></pre>", "en" ]`

Basically `Sigmoid` turned into `,`.

I can't do anything.

**Comment by WinterSilence** [comment]
@
