### ISSUE TITLE
 FF extension "Translate Web Pages": change pages

### ISSUE THREAD

**Issue by WinterSilence** [FilipePS/Traduzir-paginas-web#399]
Your extension change page code without any reasons - extension ignores what's popup translation is disabled in self settings.

It change page's behavior/style, for example:

![изображение](https://user-images.githubusercontent.com/3521094/168423156-54cf4062-31a4-444a-ba34-a381160a1f36.png)

**Comment by FilipePS** [comment]
I need an example site with this problem to see if there is anything to be done.

**Comment by WinterSilence** [comment]
@FilipePS now it's fixed
