### ISSUE TITLE
mobile translate

### ISSUE THREAD

**Issue by reyis4402** [FilipePS/Traduzir-paginas-web#40]
Mobile translation was very easy in the previous version, now we will have to open a new tab.

And I can't return to the original page

I'm sorry 😔
![20200909_174333](https://user-images.githubusercontent.com/60405617/92613783-01724800-f2c4-11ea-8801-d01a80f15a8d.jpg)

**Comment by reyis4402** [comment]
Second flip button and get back to seeing original text.

**Comment by FilipePS** [comment]
It was an attempt to remove 1 of the buttons did not work.
In version 7.3 the 2 buttons appear again.

I think this Firefox Mobile has a bug.

**Comment by reyis4402** [comment]
When I deleted and reinstalled the add-on in iceaeawasel browser, it fixed 😂
![20200909_190513](https://user-images.githubusercontent.com/60405617/92623798-697a5b80-f2cf-11ea-802b-c39bb8ff2872.jpg)

It would also be nice if this part was a black background.

![20200909_190327](https://user-images.githubusercontent.com/60405617/92623716-4c458d00-f2cf-11ea-9b55-844b04198ca1.jpg)
