### ISSUE TITLE
Selected text on mobile

### ISSUE THREAD

**Issue by reyis4402** [FilipePS/Traduzir-paginas-web#41]
The button is too small to translate the selected text and when you click it, a surrounded word comes out only

![20200909_205751](https://user-images.githubusercontent.com/60405617/92635918-4192f400-f2df-11ea-8e9f-8ab5575149b4.jpg)
![20200909_205749](https://user-images.githubusercontent.com/60405617/92635942-48216b80-f2df-11ea-9043-905d982c9c86.jpg)

**Comment by FilipePS** [comment]
I already fixed this bug, please reinstall the extension.

Em qua, 9 de set de 2020 15:01, reyis4402 <notifications@github.com>
escreveu:

**Comment by reyis4402** [comment]
Fixed but the flip icon should get a little bigger for mobile
![20200909_225547](https://user-images.githubusercontent.com/60405617/92647016-e87f8c00-f2ef-11ea-9593-583724f7b5ed.jpg)
