### ISSUE TITLE
`Translate dynamically created content` cannot be enabled on Firefox Nightly for Android

### ISSUE THREAD

**Issue by mystiquewolf** [FilipePS/Traduzir-paginas-web#412]
The request permission doesn't show up when trying to change from `No` to `Yes`.

**Comment by FilipePS** [comment]
To fix this problem you need to use another version of the extension, on your Firefox for Android, uninstall the current version of TWP and follow these steps.

To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
