### ISSUE TITLE
Auto Translate doesn't work on Opera GX

### ISSUE THREAD

**Issue by Jester7777** [FilipePS/Traduzir-paginas-web#425]

**Comment by xion83x** [comment]
same.

**Comment by Azyrion** [comment]
did anyone find a solution to this? the only error codes that I get are these ones:

![image](https://user-images.githubusercontent.com/29234550/228225302-fe9dd2a3-dd60-4bc5-9dfd-70ab0ceba531.png)
![image](https://user-images.githubusercontent.com/29234550/228225330-16a97d8d-4c5f-4a42-88d6-70a7f8ffd691.png)
