### ISSUE TITLE
English to Turkish Deepl opening new tab on browser.

### ISSUE THREAD

**Issue by EmirLogas** [FilipePS/Traduzir-paginas-web#429]
Google, Yandex, Bing are working well on Popup but Deepl button opening new an tab on browser. Not updating popup text. 
Browser = Firefox 102 .
![image](https://user-images.githubusercontent.com/76751818/177013589-9736cbd5-dc20-4382-b090-aceb1c372754.png)

**Comment by CaganAgabey** [comment]
It is already supposed to open a new tab. DeepL doesn't provide a way to directly translate from the extension, so it opens a tab and gathers translations from it.
