### ISSUE TITLE
Translate the selected text

### ISSUE THREAD

**Issue by reyis4402** [FilipePS/Traduzir-paginas-web#43]
The new mobile selected text translate button is nice but I have some advice

The translation button may be on the far right or left of the copied text, not next to it. No confusion.
Let this be adjustable.

Another should be the option to turn this feature on or off.

Finally, when only foreign text is detected, the translation button should appear and the option to copy this text should be given.

**Comment by FilipePS** [comment]
There is already an option to hide the translate button for the selected text. And I didn't quite understand that "Finally, when only foreign text is detected, the translation button should appear and the option to copy this text should be given.".

**Comment by nnolex** [comment]
> 
> 
> There is already an option to hide the translate button for the selected text. And I didn't quite understand that "Finally, when only foreign text is detected, the translation button should appear and the option to copy this text should be given.".

Hi! I think reyis4402 meant that when you select text wrote on your system language, the button appears anyway. Ex. my system language ru and dont need translate ru text, but when I select ru text translation button appears.

**Comment by Vingolf** [comment]
reyis4402 commented on 11 Sep 2020
> The new mobile selected text translate button is nice but I have some advice
[...]
>  the option to turn this feature on or off.

 FilipePS commented on 13 Sep 2020
> There is already an option to hide the translate button for the selected text. 

This option is hidden in the preferences. I suggest to create a button which is more easily available. 
For example a button that is similar to the the button to change the search engine, where this feature can be turned on or off.

**Comment by FilipePS** [comment]
> This option is hidden in the preferences. I suggest to create a button which is more easily available.
> For example a button that is similar to the the button to change the search engine, where this feature can be turned on or off.

In the popup now has a checkbox to do this
