### ISSUE TITLE
Перекидывает на сайт перевода с переводом

### ISSUE THREAD

**Issue by Sova7007** [FilipePS/Traduzir-paginas-web#433]
Когда я нажимаю на иконку перевода выделенного текста, перевод выдаётся мне не как обычно в маленьком окне появляющегося у выделенного текста, а на сайте перевода. Это очень неудобно, я пытался найти что-то в настройках по этому поводу, но мои поиски увенчались не успешно. Подскажите пожалуйста, что может помочь моей проблеме?

**Comment by FilipePS** [comment]
This is happening because you have set the text translation language to DeepL.  To resolve change to another text translation service.  Note that the text translation service is different from the page translation service.
