### ISSUE TITLE
The Translate button is appearing   while copying the text 

### ISSUE THREAD

**Issue by knk040919** [FilipePS/Traduzir-paginas-web#44]
HI Filipe  Nice Day  !!

I have notice that,  this option is not working  while it is  disabled  on Firefox  " Show the button to translate the selected text"   --  " No  "  still it is appearing every time while copying the text  such as  website, emails, . It is very difficult to copy a text  as well as it is disturbing on all sites  even not able to view the text while copying .

Again noticed  after choose of  " Never Translate this site " option  also  the translate button is appearing  every text.

Kindly fix this issue

**Comment by FilipePS** [comment]
After changing the settings it is recommended that the page be reloaded.
And in the next version the button will not appear on the page when you select to never translate this site.
