### ISSUE TITLE
CRX support for new version

### ISSUE THREAD

**Issue by Request-timed-out** [FilipePS/Traduzir-paginas-web#446]
Hey bro, this extension is amazing and I've been using it for years. It used to work fine, but since version 9.5 where the .crx version has not been provided, and I install it via the .zip file, an issue appeared: it will be gone every few weeks, so I have to reinstall it every time. What's worse, the config is gone too, even if I backup it to a .txt file, it still fails to work after restoration. I am using ungoogled chromium 104.0.5112.81 64bit, as I know only extensions installed via .zip type of file gone every few weeks, the .crx ones work just fine. So please fix the config problem and append the .crx version to every release, like #170 ! Thanks : )

**Comment by Request-timed-out** [comment]
@FilipePS

**Comment by FilipePS** [comment]
What is your operating system?

When you install the extension in the manual way (by selecting the folder). In which directory do you leave the extension folder?

You said you had a problem with the option to export/import extension settings.
What is the problem exactly? is any error message shown? Are your previous settings not restored? or are they only partially restored?

**Comment by Request-timed-out** [comment]
> 1. What is your operating system?
> 2. When you install the extension in the manual way (by selecting the folder). 
> 3. In which directory do you leave the extension folder?
> 4. You said you had a problem with the option to export/import extension settings. What is the problem exactly? 
> 5. is any error message shown? 
> 6. Are your previous settings not restored? or are they only partially restored?

1. Windows 8.1 (64bit)
2. Soon after version 9.5.1 released (about Jun 30). 
I installed 9.4.1 months ago via .crx file. On Jun 30 I tried to update it but only .zip file was provided, so I downloaded the .zip file, go to chrome://extensions, and opened the develop mode, then I dragged the .zip file into chrome window to install it. Strangely, chrome recognized it as a new extension rather than overwrite the old one, so I deleted the old one.
4. simply under the Downloads folder
5. I exported the settings to a text file in its options (ver 9.5.1). After several weeks it's gone unexpectedly. I reinstalled it (ver 9.5.1) and tried to restore the config. After I had selected the file and clicked 'open' button, the window vanished. Nor success nor failure notice shown. Then I found everything unchanged. I did it again and refreshed, same result.
6. No, but there's errors about extension itself (manifest version warning, shown on chrome://extensions)
7. No, Nothing had changed after restoration

**Comment by FilipePS** [comment]
I've tested it on ungoogled chromium and the settings are successfully exported/imported.
Could you share your configuration file?
If you want you can send it to this email: contact@translatewebpages.org
Also feel free to remove some sites from the list "alwaysTranslateSites" and "alwaysTranslateSites" for example.

**Comment by Request-timed-out** [comment]
> When extension disappears from your browser does it also disappear from your downloads folder?
> 
> If this is the case, probably some software is deleting the files from the Download folder. Try moving the extension to another directory.

Absolutely not. On the contrary, everytime when it's gone unexpectedly, I reinstall it using the same zip file in Download folder.

**Comment by Request-timed-out** [comment]
> I've tested it on ungoogled chromium and the settings are successfully exported/imported. Could you share your configuration file? If you want you can send it to this email: [contact@translatewebpages.org](mailto:contact@translatewebpages.org) Also feel free to remove some sites from the list "alwaysTranslateSites" and "alwaysTranslateSites" for example.

Ok I will try it in my spare time. Thanks for your help.
(Now I rollback to ver9.4.1 installed via crx file, it's now as stable as before. For me, if the new version had worked fine I would definitely not notice the problem of backup/restore settings. I'm also thinking about that maybe something is wrong with ungoogled chromium so that it deletes extension installed via zip file every few weeks, in that case everything installed via zip file will face this problem.)

**Comment by Request-timed-out** [comment]
> I've tested it on ungoogled chromium and the settings are successfully exported/imported. Could you share your configuration file? If you want you can send it to this email: [contact@translatewebpages.org](mailto:contact@translatewebpages.org) Also feel free to remove some sites from the list "alwaysTranslateSites" and "alwaysTranslateSites" for example.

@FilipePS I just finished the test. For version 9.4.1, if I install it via crx file, the settings are successfully exported/imported,  everything works just fine. But if I I install it via zip file. when importing, the window vanishes after selecting files. Nor success nor failure notice shown. That's it, hope it helps.

**Comment by FilipePS** [comment]
Do you extract the zip file?

**Comment by Request-timed-out** [comment]
![Untitled1](https://user-images.githubusercontent.com/51283388/184152478-43d3ec43-d32d-4719-a332-847366753e6f.png)
@FilipePS It's this type of installation

**Comment by FilipePS** [comment]
When importing the settings, it is normal for the tab to close.
This happens because the extension has been reloaded.
But the extension is still installed in your browser.

**Comment by Request-timed-out** [comment]
> When importing the settings, it is normal for the tab to close. This happens because the extension has been reloaded. But the extension is still installed in your browser.

Yes I know it. When using the crx-based extension I successfully did that once. However the zip-based extension fails to perform it.

**Comment by FilipePS** [comment]
Are you sure you're not clicking on `Reset settings to default` instead of `Restore from file`.
And that you are selecting the right backup file, with your settings, not the default settings.

**Comment by Request-timed-out** [comment]
> Are you sure you're not clicking on `Reset settings to default` instead of `Restore from file`. And that you are selecting the right backup file, with your settings, not the default settings.

@FilipePS Of course not. If I accidentaly clicked `Reset settings to default` it won't pop up a window to let me select files.

**Comment by Guest126** [comment]
I too have encountered the restore problem with Firefox on Windows. Somehow it succeeds sometimes. I can't even Reset settings to default.

**Comment by FilipePS** [comment]
Version 9.5.5 has just been released. CRX file added again.
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.5.5

**Comment by Request-timed-out** [comment]
@FilipePS Thank you for all your effort and support! I've reported many bugs to many developers, none of them has such great patience and persistence like you, thanks!

**Comment by FilipePS** [comment]
When installing the extension via the zip file, the zip file is extracted into a temporary system folder, and then loaded in the browser.
After a while the system itself deletes the temporary files, which makes the extension disappear.

**Comment by Request-timed-out** [comment]
> When installing the extension via the zip file, the zip file is extracted into a temporary system folder, and then loaded in the browser. After a while the system itself deletes the temporary files, which makes the extension disappear.

I see. Thanks for telling me it. Now I'm using the latest version installed via crx file, it's quite stable and I'm happy with that.
