### ISSUE TITLE
Doesn't translate sub-items

### ISSUE THREAD

**Issue by a1987zz** [FilipePS/Traduzir-paginas-web#447]
Poor translated or not translated at all sub-items on the sites. For example here: romhacking.net/utilities  google chrome.

**Comment by FilipePS** [comment]
I did some tests and for me everything translated correctly. What language are you trying to translate to?

**Comment by a1987zz** [comment]
On any. Translated only through the open item in Google Translator.

**Comment by FilipePS** [comment]
Try reinstalling the extension

**Comment by a1987zz** [comment]
Same thing. I must be doing something wrong.

**Comment by eros1ca** [comment]
It doesn't work for me either. Everything is translated except for drop down menus. In my case the Russian language to English.

**Comment by FilipePS** [comment]
Now I understand what is not being translated.
It's exactly this other [issue](https://github.com/FilipePS/Traduzir-paginas-web/issues/386).
I'm closing this issue because it's a duplicate.
