### ISSUE TITLE
moz-extension:// is unsupported.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [FilipePS/Traduzir-paginas-web#457]
I am unable to translate the pages served by "`moz-extension://`" URIs.

**Comment by FilipePS** [comment]
An extension only has access to `moz-extension:// ` if this URI belongs to the extension itself. There is no way to access pages with this URI from other extensions.

**Comment by beedell-roke** [comment]
@FilipePS, do you know whether a relevant issue exists at Mozilla Bugzilla?

**Comment by FilipePS** [comment]
I don't know of any relevant issues in bugzilla.
This behavior of Firefox is deliberate and the same with all other browsers.
This is probably for security reasons.

But you can still translate the selected text via a button in the context menu.


> An extension only has access to `moz-extension:// ` if this URI belongs to the extension itself. There is no way to access pages with this URI from other extensions.

I think this information is not accurate.
An extension's content script is not injected into any `moz-extension://` URL, not even if it belongs to the extension itself.

**Comment by beedell-roke** [comment]
[`GoogleChromeLabs/link-to-text-fragment/issues/72#issuecomment-1206511453`](https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/72#issuecomment-1206511453) appears to be relevant, as does [`bugzilla.mozilla.org/show_bug.cgi?id=1269456#c59`](http://bugzilla.mozilla.org/show_bug.cgi?id=1269456#c59). @FilipePS, mind re-closing as unplanned?
