### ISSUE TITLE
Translation of the extension's popup (e.g. Gmail™ Notifier) - does not work

### ISSUE THREAD

**Issue by lukaszpolowczyk** [FilipePS/Traduzir-paginas-web#458]
It doesn't work, as in the video:

https://user-images.githubusercontent.com/16800535/184803079-ad24a248-119d-438b-8bdc-a564d4d73dfd.mp4

Gmail™ Notifier extension popup - https://add0n.com/gmail-notifier.html

It would be nice to introduce translator support for extension popups.

**Comment by FilipePS** [comment]
Unfortunately this is not possible.

**Comment by lukaszpolowczyk** [comment]
@FilipePS not plannet or completed?
![Screenshots_2023-05-13-09-48-01](https://github.com/FilipePS/Traduzir-paginas-web/assets/16800535/3abf2f45-417a-492a-880b-d4aab800772e)

**Comment by FilipePS** [comment]
The **Gmail™ Notifier** extension shows the emails in its own frame, internal to the extension, so there's no way to translate it, it would only translate if it was an IFRAME that loads the gmail website.
The only thing that is possible to implement is to translate the selected text using the context menu button.

**Comment by lukaszpolowczyk** [comment]
I have set up a topic:
https://github.com/inbasic/ignotifier/issues/614

**Comment by FilipePS** [comment]
I don't know if the question is clear, but for **Gmail™ Notifier** to have email translation they will have to implement something that is independent of my extension.

**Comment by FilipePS** [comment]
Added a commit that allows text translation of the text using the button in the context menu.
On-page email translation only if **Gmail™ Notifier** add support, same as gmail itself supports.

![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/0e29e6e8-22fa-45ca-a54f-7e3aa6760a78)
