### ISSUE TITLE
About click translate

### ISSUE THREAD

**Issue by lsh1215225** [FilipePS/Traduzir-paginas-web#459]
When I click mouse or keyboard to translate the selected text, the translation box is fixed on the left side of the screen
How to change where it appears

**Comment by FilipePS** [comment]
What is your browser?
What is your extension version?

**Comment by lsh1215225** [comment]
> What is your browser? What is your extension version?

Cent Browser
版本 5.0.1002.182（正式版本） （64 位） (Chromium 102.0.5005.167)
latest version

**Comment by FilipePS** [comment]
This problem has been fixed.
Check [version 9.5.5.](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.5.5)
