### ISSUE TITLE
Source map error. Extension does not work

### ISSUE THREAD

**Issue by clive-misquith** [FilipePS/Traduzir-paginas-web#460]
I am not a developer.
Using Firefox browser. the translate option just stopped working ( maybe it is due to the fact that its a work laptop)
But faced no issues before this week.
Extension works fine at my home laptop. 

![Picture1](https://user-images.githubusercontent.com/86720958/185362406-c6cd1fb1-4f8d-4669-ac3a-c3db2a73ef7b.png)
![Picture2](https://user-images.githubusercontent.com/86720958/185362434-2f1cbf03-88dd-49ba-bc13-73f41fc50b41.PNG)

**Comment by FilipePS** [comment]
Follow these steps:
1. Clear the translation cache.
      1. Access the extension's settings page.
      2. On the `Storage` tab.
      3. Click on `Delete translation cache`.
2. Open this link in a new browser tab `about:debugging`.
3. Click on `This Firefox`.
4. Look for the `Translate Web Pages` extension.
5. Click on `Inspect`.
6. Click on the `Network` tab.
7. Now go to some website and try to translate something.
8. Go back to the `about:debugging` tab and show me what appears.

**Comment by clive-misquith** [comment]
![Picture3](https://user-images.githubusercontent.com/86720958/185589167-945699bd-a04b-4ca7-bbc7-b4e2f4e82e69.PNG)

**Comment by FilipePS** [comment]
I hadn't seen this request give http error 503 (Service Unavailable).
Maybe Google has blocked your ip address. It may come back in a while, try using a vpn.

Do you remember trying to translate a specific site and after that it started to give problems?

**Comment by clive-misquith** [comment]
It could be the company IT blocking something?
I don't remember anything specific, no.

It works fine at home.

Best Regards,
Clive

**Comment by clive-misquith** [comment]
I will try using a VPN.
But I doubt my company allows it, they might block it.
I don't get internet access via WiFi if VPN is switched ON in my cellphone
Best Regards,
Clive
