### ISSUE TITLE
Parts of a Russian text remain untranslated

### ISSUE THREAD

**Issue by rado84-github** [FilipePS/Traduzir-paginas-web#477]
As you can see in the screenshot below, some parts of a Russian text remain untranslated. To me personally that's not a problem because I'm Bulgarian and both countries (Bulgaria and Russia) use a very similar alphabet, so I understand both of the untranslated texts. However, someone who has never seen Cyrillic in their life could be confused of what these two are saying.

![Picture_created_16-09-2022_05-21-50](https://user-images.githubusercontent.com/41172201/190543552-3da49fa4-98e9-44c6-bc02-5f31663d639e.png)

**Comment by FilipePS** [comment]
It seems to be the same problem as this other issue https://github.com/FilipePS/Traduzir-paginas-web/issues/386.
In this case it has already been fixed, wait for the next version to be released.
