### ISSUE TITLE
Some fragments are not translated

### ISSUE THREAD

**Issue by kesc11** [FilipePS/Traduzir-paginas-web#484]
打开这个网站   https://docs.temporal.io/java/workflows/

![屏幕截图 2022-09-21 155520](https://user-images.githubusercontent.com/51351113/191447861-073743f2-3c5f-402c-a2a2-7d6100938e23.png)

This sentence is not translated

sourceArray3d :  ` ['What is a Workflow?', '​']`

send to Google :   `"<pre><a i=0>What is a Workflow?</a><a i=1>​</a></pre>"`

translation result :   `"<pre><a i=0>什么是工作流程<a i=1>？</a></a></pre>"`

---

<h2 class="anchor anchorWithStickyNavbar_LWe7" id="what-is-a-workflow">What is a Workflow?<a class="hash-link" href="#what-is-a-workflow" title="Direct link to heading">​</a></h2>

**Comment by FilipePS** [comment]
In the latest version, the translated text appears instead of `?`.
But the `i=0` is blank. Curiously this happens because of the invisible character `U+200b` that is sent to the translation.
