### ISSUE TITLE
Option to prevent release notes from showing

### ISSUE THREAD

**Issue by perry-mitchell** [FilipePS/Traduzir-paginas-web#491]
Thanks for this extension.

I'd like an option to prevent release notes from showing. They're not useful to me personally, and find it frustrating that they open somewhat at random (probably after an automatic update). Having some setting in the preferences to disable them showing at all would be ideal.

**Comment by FilipePS** [comment]
There is already a way to disable it.
1. Open the extension settings page.
2. Click on the `others` tab.
3. Disable the `Show release notes when updating` option

**Comment by perry-mitchell** [comment]
Ah, ok, I missed this. Thanks for the help @FilipePS !
