### ISSUE TITLE
Donations...

### ISSUE THREAD

**Issue by rafikiphoto** [FilipePS/Traduzir-paginas-web#492]
I would like to donate but as a one-off payment. The only option I see is a Patreon monthly contribution. Is there another way?

**Comment by rafikiphoto** [comment]
Ah yes. Found it. Having trouble with PayPal making a payment at the moment so I'll try again later.

Great extension (Google based browser). Thank you.

B.

------- Original Message -------

**Comment by FilipePS** [comment]
Do you still use the extension? Is the option to donate via Paypal still not working for you?
