### ISSUE TITLE
Pop-up window bug

### ISSUE THREAD

**Issue by JRHille** [FilipePS/Traduzir-paginas-web#494]
Hey man, thank you for the extension, its awesome.

i just wanted to report a visual bug i found, a window flashes on the screen when selecting texts for translation.

From what I've noticed it happens only in chromium browsers.

![chrome_xOPqtSfkUA](https://user-images.githubusercontent.com/114708288/193424228-58ae4ea3-f5f2-41e4-bfb7-ca1dfdb30a54.png)

I recorded a video and took a screenshot, you can see it here: imgur.com/a/MjP4BOq

I'm using the latest version 9.6

**Comment by FilipePS** [comment]
Although I can't reproduce this issue. I've made a change to the code that could potentially fix this issue.
Test version 9.6.1 and let me know if everything is resolved.
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.6.1

**Comment by JRHille** [comment]
Yes, I can confirm, it's fixed in the new version.
Thank you so much!
