### ISSUE TITLE
The "replace selected text with translated text" function doesn't work.

### ISSUE THREAD

**Issue by pqnhan** [FilipePS/Traduzir-paginas-web#495]
Instead, it is selecting all the existing text on the web page.

I tried changing some other shortcut for this fuction from TWP's option page, but it seems the error is not on Firefox's side.

![Peek 2022-09-30](https://user-images.githubusercontent.com/24197589/193187934-b82cacff-e3c5-4681-84ca-52aa1f166f80.gif)

My Firefox version: 104.0 (64-bit)
Ubuntu: 20.04.

**Comment by FilipePS** [comment]
This option is intended to translate the text selected in `input`, `textarea` and other editable elements.

For example: If you are chatting with a friend who speaks another language on facebook. After you finish typing just select the text and use this new feature.

**Comment by pqnhan** [comment]
@FilipePS Um, so I've misunderstood how it works.
I will close this issue.
Anyway, thank you very much, the extension is really great, it helps me a lot in reading comprehension.
