### ISSUE TITLE
Be careful.

### ISSUE THREAD

**Issue by Libidine** [FilipePS/Traduzir-paginas-web#5]
You have a great extension, but it might get blocked due to Firefox policy:
_Add-ons must be self-contained and not load remote code for execution_

Many other developers of similar extensions were forced to leave: https://www.jeremiahlee.com/posts/page-translator-is-dead/
https://github.com/andreicristianpetcu/google_translate_this/issues/19

I hope that this will bypass you, but if it happens, at least you will be mentally prepared for it.

**Comment by FilipePS** [comment]
My extension translates in 2 ways.  Inserting Google or yandex widgets.  Or using my own algorithm.  In the second option, no external code is loaded.  But you raised a good question, I don't know if there is anything wrong with my translating algorithm without using these widgets.  To translate with Google for free you have to pass a hash called tk in the URL, and my algorithm generates this hash, I don't know if there is anything illegal about it.

**Comment by Libidine** [comment]
I don't know the correct answer, I just advise you to study the code of those extensions that were closed, maybe your approach is really different and then everything is fine. Hope so.
