### ISSUE TITLE
Translation URL selection in Simplified Chinese environment

### ISSUE THREAD

**Issue by wangquanlikun** [FilipePS/Traduzir-paginas-web#503]
In the issue #498 ,someone has reported the fact that Google Translate quits mainland China. As a result, translate.google.cn may can't be used even in use of proxy. 
When I use the function in the right click menu to translate some words or the website page(something just like the issue #497 ), it may jump to a website which reports error message 404. 
It's because the use of translation URL is translate.google.cn. So I hope you can kindly change the translation URL in Simplified Chinese environment to translate.google.com.  
Thanks again for the author's fantastic work!
<img width="992" alt="SCREENSHOT" src="https://user-images.githubusercontent.com/75524809/193592679-6c2a0050-69f2-4f6f-a7ea-45fe11e8efa4.png">
The website can't be reached.
<img width="992" alt="SCREENSHOT 02" src="https://user-images.githubusercontent.com/75524809/193593378-5554d189-38c6-48d9-976e-7ca76854dac9.png">
It shows that translate.google.cn has left mainland China.

**Comment by linjialiang** [comment]
谷歌翻译已经退出中国了，是不是应该换成百度的了，百度API也不错

**Comment by FilipePS** [comment]
Do either of these two links work in China?

1. [link](https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit)
2. [link](https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.DQh_Kmqon4I.O/d=1/exm=el_conf/ed=1/rs=AN8SPfp-VgeNXvvY8CLHQ-U2T92RGDchtg/m=el_main)

**Comment by sunnyday666** [comment]
> Do either of these two links work in China?
> 
>     1. [link](https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit)
> 
>     2. [link](https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.DQh_Kmqon4I.O/d=1/exm=el_conf/ed=1/rs=AN8SPfp-VgeNXvvY8CLHQ-U2T92RGDchtg/m=el_main)



> Do either of these two links work in China?
> 
>     1. [link](https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit)
> 
>     2. [link](https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.DQh_Kmqon4I.O/d=1/exm=el_conf/ed=1/rs=AN8SPfp-VgeNXvvY8CLHQ-U2T92RGDchtg/m=el_main)

I tried. Neither link is available in China,

**Comment by sunnyday666** [comment]
> Do either of these two links work in China?
> 
>     1. [link](https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit)
> 
>     2. [link](https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.DQh_Kmqon4I.O/d=1/exm=el_conf/ed=1/rs=AN8SPfp-VgeNXvvY8CLHQ-U2T92RGDchtg/m=el_main)

I tried. Neither link is available in China,

**Comment by qchen-roger** [comment]
https://bookfere.com/post/1020.html
The first method works. Add the following characters into the "hosts" file. Good luck
180.163.151.34 translate.googleapis.com

**Comment by passenger666** [comment]
Suggest adding DeepL service.

**Comment by Ives0721** [comment]
DeepL service actually a good choice to use, especially when reading thesis on webpage.

**Comment by YohoYang** [comment]
I suggest to switch the api url for google translate directly to .com . Chinese users only need to set up a VPN to continue using Google Translate normally. 
At the same time, as mentioned in other replies, adding more translation APIs such as DeepL is also another way. 
Perhaps it is also possible to directly allow users to input and modify the url of the translation interface, just like the browser's search interface settings.

**Comment by FilipePS** [comment]
In the last version, Bing was added as a page translation service.
