### ISSUE TITLE
增加网页翻译接口

### ISSUE THREAD

**Issue by 514293676** [FilipePS/Traduzir-paginas-web#513]
谷歌网页翻译接口用不了了；
Yandex网页翻译接口准确性又低；
可以增加：DeepL网页翻译接口或bing网翻译接口

**Comment by Lurito** [comment]
Same issue

**Comment by chengs2035** [comment]
deepl 整页翻译似乎需要收费的

**Comment by lsh1215225** [comment]
bing google都要挂全局

**Comment by XHXIAIEIN** [comment]
建议添加"腾讯翻译" "有道翻译" "彩云小译" 的翻译接口。参考此脚本的部分；
https://greasyfork.org/zh-CN/scripts/378277-%E7%BF%BB%E8%AF%91%E6%9C%BA

**Comment by FilipePS** [comment]
Can the extension translate using Google in China nowadays?

**Comment by FilipePS** [comment]
Please test version 9.7 here: https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7
After testing tell me if everything worked as expected.

**Comment by FilipePS** [comment]
In the last version, Bing was added as a page translation service.
