### ISSUE TITLE
Add DeepL translator to Firefox search engines

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#518]
Hi Filipe!
 Add please DeepL translator to Firefox search engines for not to install other add-ons like this: https://addons.mozilla.org/ru/firefox/addon/deepl-translate-search/
![Screenshot_1](https://user-images.githubusercontent.com/17863616/196438311-caba95ae-cfc7-4fb1-a5d4-c7a2bb83081a.png)
  On Reddit actively discussing how to do this, so this functionality would be very relevant: https://www.reddit.com/r/firefox/comments/n8ohie/add_deepl_translator_to_firefox_search_engines/

**Comment by FilipePS** [comment]
Something like that is beyond the scope of this extension.

**Comment by FilipePS** [comment]
Just out of curiosity, would the goal be to do exactly what that extension does? without anything being different?
