### ISSUE TITLE
Select and translate doesn't work, unless open deepl.com web page in another tab

### ISSUE THREAD

**Issue by 0x391F** [FilipePS/Traduzir-paginas-web#519]

**Comment by FilipePS** [comment]
To translate the selected text using the DeepL translation service unfortunately you need to keep the tab open.

If you don't want to use DeepL, in the extension's translation settings you can select another text translation service.

In the popup that opens when translating selected text, there are 4 buttons to select the translation service ("g", "y", "b" and "d"), which mean respectively: Google, Yandex, Bind, DeppL. Click on one of these buttons to use another translation service.
