### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rosabis** [FilipePS/Traduzir-paginas-web#52]
1.Always translate this sites function not work sometimes in iceraven(based on firefox android 80),I can only click translate button to translate page.
2.Will show translate bar when When visiting a website in the same language as the user’s browser

**Comment by FilipePS** [comment]
1. The feature of always translating a website is designed to work only on the computer.
2. Does this happen often? what language is your browser?

**Comment by mini536** [comment]
>     1. The feature of always translating a website is designed to work only on the computer.
> 
>     2. Does this happen often? what language is your browser?

I am using iceraven(a fork of fenix),it have your extension in their extension list,and my system language is Chinese Traditional.

**Comment by FilipePS** [comment]
If you still use the extension, I suggest that in the "Show the mobile popup" setting, select "When I touch three fingers on the screen"
