### ISSUE TITLE
When I use this plugin inside Firefox, it rarely goes wrong. But when I use this plugin inside Google Chrome, it becomes unstable and has various problems after a while, I hope you can fix these problems, thank you!

### ISSUE THREAD

**Issue by tutuxys** [FilipePS/Traduzir-paginas-web#521]
<img width="992" alt="截屏2022-10-25 03 47 24" src="https://user-images.githubusercontent.com/62400524/197617829-0df2bf46-27b9-4ae0-8aaf-00158db5fc7f.png">
<img width="886" alt="截屏2022-10-25 03 54 32" src="https://user-images.githubusercontent.com/62400524/197617834-324ac8d4-97cc-4c0e-96b7-ac23ad089647.png">
<img width="886" alt="截屏2022-10-25 03 54 48" src="https://user-images.githubusercontent.com/62400524/197617837-502d8bbf-9248-4637-b511-64f5354f2d62.png">
<img width="886" alt="截屏2022-10-25 03 54 57" src="https://user-images.githubusercontent.com/62400524/197617841-7f3dc517-8314-4df0-aa7e-d7dd610ae2a9.png">

**Comment by FilipePS** [comment]
Are you from Mainland China?
Do you use any proxy/vpn?

**Comment by tutuxys** [comment]
Yes, I am from mainland China. I am using Clash as a proxy tool to access Google and YouTube. these days I am continuing to use this plugin you developed, no problem for now, it works fine.

**Comment by tutuxys** [comment]
Thank you very much for developing this plugin, it can switch between English and Chinese by shortcut keys, it really saves me a lot of time. Thanks again for your genius work. You are so amazing.

**Comment by FilipePS** [comment]
> Yes, I am from mainland China. I am using Clash as a proxy tool to access Google and YouTube. these days I am continuing to use this plugin you developed, no problem for now, it works fine.

So I think I can close this issue.
