### ISSUE TITLE
Black icon with dark theme

### ISSUE THREAD

**Issue by Dominiquini** [FilipePS/Traduzir-paginas-web#524]
If Firefox is using some dark theme, the black icon appears almost invisible on the url toolbar!
Would be cool if we could change the color of the icon. Or change automatically depending on the selected theme.

Thanks

**Comment by FilipePS** [comment]
I have tried to reproduce this problem before but without success.

1 - What is your operating system?
2 - What is your system's configured color scheme?
3 - What is your browser? what version of it?
4 - What theme are you using? name, theme link...

**Comment by Dominiquini** [comment]
1 - Windows 10 x64
2 - Light theme for apps and dark for Windows
3 - Firefox 106.0.1
4 - Default theme (light), but in private mode, the browser automatically change to dark!

Thanks.

**Comment by Dominiquini** [comment]
Any update on this issue? The address bar appears broken and the icon is very difficult to see:

![Firefox](https://user-images.githubusercontent.com/1180808/205116552-beb4945e-72e4-4d39-8278-5cbe38fe7c09.png)

Thanks.

**Comment by Dominiquini** [comment]
Tem alguma previsão de quando você publicará uma nova versão?

Obrigado.

**Comment by FilipePS** [comment]
> Tem alguma previsão de quando você publicará uma nova versão?
> 
> Obrigado.

Se quiser pode testar a versão beta. Lembre-se de dar um feedback depois de testar.
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7-beta-1
