### ISSUE TITLE
"Always translate specific language functions." Only historical records can be reserved for use

### ISSUE THREAD

**Issue by Aram-Lin** [FilipePS/Traduzir-paginas-web#529]
Hello, author, or development team. As I said in the headline. Uniform translation of a specific language will only be initiated if any history is preserved.

**Including Firefox does not save any history. And the privacy model.**

You must also use the translation function every time you close the browser to clean up your browsing data. Then we will officially start translating all languages.)

Whether the author. Can translate the functions of other languages uniformly. Make THE RESPONSE WITHOUT USING HISTORY (AS A DIRECT TRANSLATION TO DETECT SPECIFIC LANGUAGE?)

**Comment by Aram-Lin** [comment]
I want to start by saying I'm sorry. The author. Currently autoclean records when the browser is closed. Translation of specific language features is effective. It works, but it was not available in my last test in reply. So please ignore this part)

The more important thing to note is that. The option not to save any history, and the privacy mode will have no effect in uniform translation of a specific language

**Comment by FilipePS** [comment]
### Extension Cache Types
1. in-memory cache, which is cleared when you close the browser or disable the extension by the extension manager.
2. disk cache, which is only cleared when the extension is updated.
You can also clear this cache manually through the extension's settings.

### About Privacy
Although enabling the option to not log any history can bring more privacy. This is not valid for the extension's translation cache.

First, it is not so simple for someone who has access to your computer to know what is in your translation cache.

And with translation caching, fewer requests are made to third-party servers, which potentially decreases their ability to track you (if they do).

### Conclusion
Then explain better what you want and why.

**Comment by Aram-Lin** [comment]
> 
Without any history, or in private mode.(Can the SSD service life be extended?)
I've heard something like this.If set in firefox without any cache.Prolong the service life of SSDS.(If it is closed through the browser, after clearing the history.They are not the same.

(I don't quite understand the details.Please correct me)

**Comment by FilipePS** [comment]
In the next version I intend to remove the persistent cache.
