### ISSUE TITLE
Translate Web Pages has begun changing my address

### ISSUE THREAD

**Issue by ronmorgan1** [FilipePS/Traduzir-paginas-web#53]
Translate Web Pages has begun changing my address when I enter it in an online form on a website or type it in an email. Instead of saving or leaving unchanged my address as entered, it alters it to a Spanish to English language translation. For example, if I enter my address as "1234 Camino Las Roblas" it changes it to "1234 The Roblas Road".  Has recently caused issues with mail delivery.

**Comment by FilipePS** [comment]
Could you tell us on which sites this problem is happening?

**Comment by ronmorgan1** [comment]
Hello, FilipePS.  It happens on any website having a form which calls for entry of my address, e.g. any eCommerce website where you wish to purchase something and it asks for your mailing and shipping addresses.  Issue disappears when I turn off Translate Web Pages.

**Comment by ronmorgan1** [comment]
Sorry, I accidentally closed this.  I'd like it to still be open.

**Comment by FilipePS** [comment]
Please provide a link to a website with this problem

**Comment by FilipePS** [comment]
Could you check if version 7.7 released today fixed this problem?

**Comment by fumantsu** [comment]
This issue happens also with google's translation on Chrome. It is not necessary issue with the addon rather with the page.
