### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by WaGGstoun** [FilipePS/Traduzir-paginas-web#54]
You can add the function of customizing the font: type, size, etc. If I understood correctly there is no such function yet?

**Comment by FilipePS** [comment]
function to customize the font for the pop up that shows the original text of the page?

**Comment by WaGGstoun** [comment]
Yes customize popup: text and window size. And also setting up fonts on some selected sites. Since on some sites after translation, their font is not suitable, small or unreadable.
