### ISSUE TITLE
Popup icon color doesn't match with some themes

### ISSUE THREAD

**Issue by FilipePS** [FilipePS/Traduzir-paginas-web#548]
Some themes like this: https://addons.mozilla.org/firefox/addon/firefox-alpenglow/
There are two color definitions in `manifest.json` for **light** and **dark** theme preference.
The `browser.theme.getCurrrent` function always seems to return **light** colors even if the browser is using the **dark** colors from the theme.
This causes the extension icon color to be wrong.

**Comment by mystrdat** [comment]
Also having this issue on Alpenglow, Firefox native icons are white but this extension's icon is black, making it barely visible.

**Comment by FilipePS** [comment]
The extension [Dark Reader](https://addons.mozilla.org/firefox/addon/darkreader/) appears to change the browser theme and causes the extension icon to not match other browser icons.
