### ISSUE TITLE
The Google Transalte API in China Mainland is dropped

### ISSUE THREAD

**Issue by greenhat616** [FilipePS/Traduzir-paginas-web#553]
## What Problem you have faced?

https://github.com/FilipePS/Traduzir-paginas-web/blob/40602f85be9d7f253c33abad59e4fcad1ad830d4/src/popup/popup.js#L606

![图片](https://user-images.githubusercontent.com/41122242/206643720-c1a26e17-2014-4e7b-aaef-394054eef5ea.png)
 As is the image illustrated, the Google Translate API(`https://translate.google.cn`) in China mainland is closed, and not process any translation request. In a short word, this plugin is not work while user is using `zh-CN` as their preferred language.

## What is your excepted?

Maybe we should use `translate.google.com` at all to fix this problem

**Comment by FilipePS** [comment]
I fixed the link to always use `translate.google.com`. However, it is good to clarify that this only affects the option `Open in google translator`. It does not affect the translation of websites and text done directly by the extension.

Is the extension currently able to translate websites using Google's translation service?

**Comment by greenhat616** [comment]
Thanks for your clarify, and this extension is work now(After I updated to v9.7.3 manually). 
Finally, thank you very much for your work in spite of your busy schedule!
![image](https://user-images.githubusercontent.com/41122242/234575395-cda48a0d-9785-49bd-9491-f2578aa3991e.png)
