### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Jfmblinux** [FilipePS/Traduzir-paginas-web#559]
Translation error
Why does the extension place "Google" where others (Bing, DeePl...) put the right translation?
And in otpions (Page Translation Service):
There is really no other possibility of having choice than Google and - or Yandex?
Exmeple: Bing, LibreTranslate...

I confess I do not understand for Google 🤔

![Traducteur 4 1 1](https://user-images.githubusercontent.com/54814723/207886476-64a17b91-de96-449b-8471-7f4a0180cf46.png)

![Traducteur Deepl](https://user-images.githubusercontent.com/54814723/207887852-1a4ace53-1182-4033-9a9d-ec54e704e0eb.png)

**Comment by FilipePS** [comment]
There is an app called Google Calendar. Google translate must be thinking that Calendar is referring to its application.

I recommend that you open the Google Translate website (translate.google.com) translate the text there and if it is wrong use the option to correct the translation. Your correction should help to prevent this from happening again in the future.

**Comment by Jfmblinux** [comment]
Hi,

Google likes to put itself forward with its applications 🤣  
Anyway, thanks 🙏 
I will do that.
