### ISSUE TITLE
I have some suggestions.

### ISSUE THREAD

**Issue by black7375** [FilipePS/Traduzir-paginas-web#56]
First, I want to say thank you.
It's the most stylish and easy-to-use translator available on Firefox.

### 1. When button click
How about making a translation immediately by pressing the `Toolbar` or `Address bar` button?

Pressing the button means that the user will use the translation in the future.
So, I think it's a good idea to first translate the site when you press the button and then display a pop-up that returns to the original.

### 2. Selected Text
- Dark mode doesn't seem to be applied to the text selection popup. (Is it Bug?)
- When selecting multiple lines, can you show the translation result in multiple lines?
- In the case of `Textarea`, the button does not appear even if you drag.

Thanks again for developing a good addon. :+1:

**Comment by FilipePS** [comment]
> How about making a translation immediately by pressing the `Toolbar` or `Address bar` button?

The popup that opens when you press this button has several functions, and it may be that the user's goal is not to translate the entire page now. So I don't intend to add this

All other features have already been implemented.

**Comment by black7375** [comment]
It is the best translation plugin in Firefox!!
Thanks👍
