### ISSUE TITLE
Pop up icon turns blue

### ISSUE THREAD

**Issue by udontkn0wme** [FilipePS/Traduzir-paginas-web#562]
Firefox uses new shade of blue as highlight for some time instead of #45a1ff it's the more cyanish #00ddff. Could the icon be updated please? It looks kinda distracting.

**Comment by FilipePS** [comment]
I fixed the problem in this commit: 
https://github.com/FilipePS/Traduzir-paginas-web/commit/56152f2e3b2150a819902f0f12a9091e43270a25

Wait for the release of the next version.
