### ISSUE TITLE
bug: causes problem with WordPress visual editor

### ISSUE THREAD

**Issue by atomGit** [FilipePS/Traduzir-paginas-web#57]
when creating a post in the WordPress visual editor TinyMCE (i don't use the block editor) TWP is adding empty DIV tag pairs at the very end of the post - to reproduce:

1. create a new post (no title needed)
2. enter something in the post content area
3. switch to the code editor and an empty DIV tag pair is added

**Comment by FilipePS** [comment]
What language is your wordpress in?
Translate Web Pages is configured to translate to which language?
Are you using Yandex or Google to translate?
Could you make a video? I was unable to reproduce this problem.

**Comment by FilipePS** [comment]
Could you check if version 7.7 released today fixed this problem?

**Comment by atomGit** [comment]
sorry for not getting back earlier - 7.7 seems to fix the problem
