### ISSUE TITLE
Bing doesnt work

### ISSUE THREAD

**Issue by Hossam225** [FilipePS/Traduzir-paginas-web#573]
The translation using Bing shows nothing, It has been like this for months now.
I use english, arabic and russian, It doesnt work for any of them.

**Comment by LeetHaxor** [comment]
Still an issue. Google and Yandex work, but Bing is blank.

**Comment by FilipePS** [comment]
This issue has been fixed, please wait for the next version release.

You can also download and test the beta version here: https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7-beta-2
