### ISSUE TITLE
hitting ctrl twice on popup window translates the whole page but...

### ISSUE THREAD

**Issue by Hossam225** [FilipePS/Traduzir-paginas-web#577]
but I usually select a single word or expression from the popup itself and hit ctrl twice again to show the translation of that seleted word or expression in a new popup. Now that doesn't work, instead it selects and translates the entire page.  This is useless as there is already a shortcut to translate the entire page.  On the other hand, it eliminates the feature of reusing a selected text from the translation panel itself.

**Comment by FilipePS** [comment]
This is strange behavior.
Is your keyboard not pressing keys by itself?

**Comment by Hossam225** [comment]
> Is your keyboard not pressing keys by itself?

Can't really understand what you mean but if you mean: Does the keyboard have a malfunction? So, no, it works normally.

https://user-images.githubusercontent.com/87137432/232982007-868e69a9-4de8-430c-9a62-1834b882831f.mp4
