### ISSUE TITLE
not work in Kiwi Browser ☹️

### ISSUE THREAD

**Issue by zpcol** [FilipePS/Traduzir-paginas-web#58]

**Comment by irwan-batra** [comment]
same here tested on latest build kiwi 🥝😐, followed all manifest instructions

**Comment by FilipePS** [comment]
An issue that prevented it from working has now been fixed

**Comment by FilipePS** [comment]
And those instructions just tell you what to change in the extension to work, they don't teach you how to load them into the browser of your choice.

**Comment by mycal123** [comment]
yep working fine in kiwi browser , no issues regarding above questions
https://www.youtube.com/watch?v=nL4qqNS6Gy0&t=30s
