### ISSUE TITLE
Color scheme breaking

### ISSUE THREAD

**Issue by wis3f1sh** [FilipePS/Traduzir-paginas-web#581]
When I turn on the built-in dark theme of firefox alpenglow, the color scheme of the icon in the address bar breaks. For example, displaying the icon with the system dark theme and displaying the built-in dark theme firefox alpenglow.
![1](https://user-images.githubusercontent.com/97912016/218267691-5921bb40-7801-40e2-aebd-b7b48161a136.PNG)
![2](https://user-images.githubusercontent.com/97912016/218267694-2ec8eb03-b51c-414f-a922-1ee0db859708.PNG)

**Comment by Simon-ster** [comment]
<img width="118" alt="image" src="https://user-images.githubusercontent.com/33040932/227348220-8549f290-1ac8-4506-b519-e54446bdf967.png">
When using firefox alpenglow on MacOS, after switching to system light theme, alpenglow color seems to be correct

**Comment by refereexx** [comment]
it happens on windows

**Comment by presentformyfriends** [comment]
Same issue here with Firefox Alpenglow on Linux Mint Vera.
