### ISSUE TITLE
Certain parts of a page not translated

### ISSUE THREAD

**Issue by colu-odoo** [FilipePS/Traduzir-paginas-web#582]
When using this extension certain parts of web pages do not translate.

https://drive.google.com/file/d/16TwCR1xTYoq2wgZVmxP9bbPPbNAS33dz/view?usp=sharing

**Comment by FilipePS** [comment]
Text fields are not translated. This is to prevent information such as passwords from being sent to the translation service.
Also when writing a text it would be annoying if the extension kept translating/changing the text you are typing.
