### ISSUE TITLE
使用OK，但有错误提示：Manifest version 2 is deprecated, and support will be removed in 2023. 

### ISSUE THREAD

**Issue by xyz12810** [FilipePS/Traduzir-paginas-web#584]
使用OK，但有错误提示：Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details. 
注意到有这个提示，所以是不是应该推出到 Manifest version 3 的版本了？

**Comment by scorpion421** [comment]
Or simply get a better browser, like Firefox?

**Comment by FilipePS** [comment]
No need to worry, if Google removes support for Manifest V2 I will update to Manifest V3.
