### ISSUE TITLE
使用插件后network会出现多余的东西

### ISSUE THREAD

**Issue by NoodlesGentleman** [FilipePS/Traduzir-paginas-web#585]
![image](https://user-images.githubusercontent.com/32062284/221083538-2d9af080-0d3a-4ece-b70b-79a58444ed73.png)
请教，怎么去除图中的请求

**Comment by bxb100** [comment]
It is plugin usage

**Comment by FilipePS** [comment]
Just don't use the options: `Show original text when hovering`, `Show the button to translate the selected text`, `Show translated text when hovering`, etc... And these requests will not be made.

Anyway, no need to worry, these requests are for internal files of the extension, not for any server.
