### ISSUE TITLE
DeepL dosen't work

### ISSUE THREAD

**Issue by EdwardNorthwind** [FilipePS/Traduzir-paginas-web#588]
When I choose a DeepL translator and try to translate some selected text, it just opens the DeepL site without selected text, and no appears translation widget.

**Comment by LeetHaxor** [comment]
Same issue here. Looks to be an issue with the redirect path. Seems likely that DeepL changed the format of translate URLs at some point.

Currently, it attempts to redirect to: https://www.deepl.com/#!lg!#input

lg = output lang 
input = text input to be translated

Current URL _after_ a translation:
https://www.deepl.com/translator#lg1/lg2/input

lg1 = input lang
lg2 = output lang
input = text input to be translated

After some messing around (I am not well-versed in web stuff), I found a url that works for translating via detected language. Test with:

https://www.deepl.com/translator//lg/input 

lg= output lang (2-letter code; en, fr, ru, etc.)
input = text input to be translated

I'm sure there's a "neater" way to write the URL, but the text between the 2 // is used for specifying a language, so leaving it completely blank seems to force a detection.

**Comment by 0x391F** [comment]
Hey, guys, I find a common URL to translate: https://www.deepl.com/translator#auto/`language,such as zh`/`string`
e.g: https://www.deepl.com/translator#auto/zh/L'Opéra chez soi

**Comment by FilipePS** [comment]
DeepL has been fixed. Wait for the next version.

**Comment by ekibastus** [comment]
UP!
