### ISSUE TITLE
If there is a link in the paragraph, the translation result is not accurate

### ISSUE THREAD

**Issue by lindongbin** [FilipePS/Traduzir-paginas-web#59]
e.g. https://blog.mozilla.org/blog/2020/09/17/update-on-firefox-send-and-firefox-notes/

**Comment by FilipePS** [comment]
I am aware of this problem, the reason it has not yet been fixed is the difficulty of implementing it, and that the solution can break the layout of the site or even make parts of the site not work.

**Comment by FilipePS** [comment]
In the next version will have a feature that partially solves this problem.
You will need to enable the "Do not sort the google translate results" feature in the translation settings.
