### ISSUE TITLE
Doesn't translate automatically, options don't populate language lists

### ISSUE THREAD

**Issue by lameventanas** [FilipePS/Traduzir-paginas-web#6]
If I visit a website in another language, it won't translate automatically.
If I check the checkbox "Always translate from XXX", close the tab and visit the same site again, it doesn't translate automatically.

I tried to configure in the options: "Automatically translate these languages", but if I click there, it doesn't show anything, I'm guessing I should get a list of some kind.
The "Never translate these sites" also doesn't show anything. The rest of the select boxes are populated.

Besides these issues, it works.

**Comment by FilipePS** [comment]
After checking the box "always translate from [lang]". You must click on the "Translate" button for the configuration to be saved.
When you click "Never translate this site", basically this site will not be translated automatically. However, if you manually translate the site, this configuration will be deleted.

**Comment by lameventanas** [comment]
> After checking the box "always translate from [lang]". You must click on the "Translate" button for the configuration to be saved.

If I do this, it will automatically translate **this website** future visits. Other websites in the same language are not translated and I have to repeat this for every website (domain).

**Comment by FilipePS** [comment]
What language are you translating into?
And what is the language of these sites? (the links would be even better)

**Comment by lameventanas** [comment]
Sorry, it does work, it just takes some time to translate.
The only thing that doesn't work is populating the selects in the options page.
And maybe it should automatically save the setting after clicking "Always translate from X".
Thanks!

**Comment by FilipePS** [comment]
Automatic translations are only activated after clicking "Translate" because I understand that you accidentally checked the box, as you did not click to translate the site.
And what exactly is not working in the extension options?

**Comment by DuckOfDuckness** [comment]
I don't even see the option for "Always translate" on this site: http://cafe.daum.net/Dreamcatcher7
![image](https://user-images.githubusercontent.com/1951003/89709067-f4340780-d96b-11ea-9c0b-cf32d6bcbb39.png)
Not sure if it's related to this. If it isn't I can make a new issue.

**Comment by FilipePS** [comment]
> I don't even see the option for "Always translate" on this site: http://cafe.daum.net/Dreamcatcher7
> ![image](https://user-images.githubusercontent.com/1951003/89709067-f4340780-d96b-11ea-9c0b-cf32d6bcbb39.png)
> Not sure if it's related to this. If it isn't I can make a new issue.

It is better to create a new issue for this problem

**Comment by lameventanas** [comment]
> Automatic translations are only activated after clicking "Translate" because I understand that you accidentally checked the box, as you did not click to translate the site.
> And what exactly is not working in the extension options?

The last 2 options: "Never translate these sites" and "Automatically translate these sites" are empty select boxes, so I thought something was wrong there, but the problem was I hadn't clicked on "automatically translate" or "never translate" before.

I think using a widget that looks like a select box is confusing, it made me think that there should be something to select.  It would be better to make it look like a list (like a disabled textarea), if the list is empty then show an empty list.
