### ISSUE TITLE
You can't donate via Paypal from Japan

### ISSUE THREAD

**Issue by kojix2** [FilipePS/Traduzir-paginas-web#60]
I tried to donate but was unable to do.

![image](https://user-images.githubusercontent.com/5798442/96606103-dbfc4380-1331-11eb-8ff7-d64157ffca87.png)

Thank you for your work!

**Comment by FilipePS** [comment]
Sorry for not answering, do you still use the extension? Is the option to donate via Paypal still not working for you?

**Comment by kojix2** [comment]
I don't know. I use Patreon instead.

**Comment by FilipePS** [comment]
Could you click on the option to donate via Paypal just to confirm if this error message still appears? no need to donate.

**Comment by kojix2** [comment]
No, now the display no longer appears and the donation is successfully made. This tool is very useful for FireFox users.
Please continue to develop it. Thank you very much.
