### ISSUE TITLE
Cannot detect translation exclusion languages.

### ISSUE THREAD

**Issue by Githubmaniak** [FilipePS/Traduzir-paginas-web#605]
I'm using Firefox Nightly for Android (113.0a1), but TWP doesn't detect the language added to the exception settings.

The device and OS version used are SM-G960N/Android 10.

**Comment by FilipePS** [comment]
Firefox for Android does not support language detection. So that kind of functionality is limited.

**Comment by Githubmaniak** [comment]
@FilipePS Thank you for answer.  Why doesn't the auto-translate feature work when I go to the same domain as my current website?  Are these features not supported by Firefox for Android?
![Screenshot_20230414-222151_Firefox Nightly](https://user-images.githubusercontent.com/103377449/232057275-1018264e-1848-45b1-9b0a-95cdad1763b0.jpg)
Even if I click the select box to change it to Yes, it is fixed to No.

**Comment by FilipePS** [comment]
> @FilipePS Thank you for answer. Why doesn't the auto-translate feature work when I go to the same domain as my current website? Are these features not supported by Firefox for Android? 
> Even if I click the select box to change it to Yes, it is fixed to No.

To fix this problem you need to use another version of the extension, on your Firefox for Android, uninstall the current version of TWP and follow these steps.

To use the extension on Firefox for Android/iOS, follow these steps:

1. Install the latest version of Firefox (v120+).
2. Open the extension manager.
3. Scroll down and click Find more extensions.
4. On the add-ons website, search for TWP.
5. Install the TWP - Translate For Mobile extension.

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b
