### ISSUE TITLE
Cannot translate local files after setting ignore translation <pre> tag

### ISSUE THREAD

**Issue by qinxs** [FilipePS/Traduzir-paginas-web#609]
The contents of the local file (file protocol) are included in the \<pre\> tag

![1](https://user-images.githubusercontent.com/13647698/230630249-0024671b-6cc3-4935-8406-744c47f8edd8.png)

```js
if (twpConfig.get("translateTag_pre") !== "yes") {
  htmlTagsInlineIgnore.push("pre");
}
```

Should be excluded: the URL is a file protocol and there is only one \<pre\> sub-element under body

**Comment by qinxs** [comment]
Addendum:

Only one \<pre\> child element under the body is judged to work

Such pages should also support translation
https://raw.githubusercontent.com/FilipePS/Traduzir-paginas-web/master/LICENSE

**Comment by FilipePS** [comment]
> Addendum:
> 
> Only one \<pre\> child element under the body is judged to work
> 
> Such pages should also support translation https://raw.githubusercontent.com/FilipePS/Traduzir-paginas-web/master/LICENSE

Unfortunately the site `raw.githubusercontent.com` defines the value `sandbox` for the `content-security-policy` **header**. This prevents the extension's **contentScript** from being injected into that site.
