### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by lameventanas** [FilipePS/Traduzir-paginas-web#61]
I wish this was available for Thunderbird too.
Is this something planned for the future?

**Comment by anishmittal2020** [comment]
Please add this to Thunderbird too,

**Comment by KorayUlusan** [comment]
I also agree with this idea

**Comment by FilipePS** [comment]
I managed to load the extension in Thunderbird, but the page was not translated. I have my doubts whether extensions can really manipulate the texts of the messages.
Do you know of any Thunderbird extensions that create buttons in messages or change the content of messages?

**Comment by dtantono** [comment]
@FilipePS I voted for thunderbird as well and for the extensions you looking for. Are these (https://addons.thunderbird.net/en-US/thunderbird/addon/msghdr-toolbar-customize/), (https://addons.thunderbird.net/en-US/thunderbird/addon/phoenity-buttons/), and (https://addons.thunderbird.net/en-US/thunderbird/addon/toolbar-buttons/) relevant to you?

**Comment by FilipePS** [comment]
It doesn't seem to be possible to translate the emails as well as the website.
And since there is already an extension that translates the selected text, I see no reason to launch an extension that does just that too.

**Comment by anishmittal2020** [comment]
@FilipePS There is [[Web Translate :: Add-ons for Thunderbird](https://addons.thunderbird.net/en-US/thunderbird/addon/web_translate/)](https://addons.thunderbird.net/en-US/thunderbird/addon/web_translate/), but it is not open source. It would be great if we have an open source app.
