### ISSUE TITLE
translate.google.cn has been deprecated. It's time to remove it in popup/{popup.js,old-popup.js}.

### ISSUE THREAD

**Issue by yiqifengba** [FilipePS/Traduzir-paginas-web#610]
![image](https://user-images.githubusercontent.com/53386055/230637583-d44b413a-06a8-4ca0-a57d-027af1f7bf48.png)

**Comment by FilipePS** [comment]
There is already an issue related to this.
https://github.com/FilipePS/Traduzir-paginas-web/issues/553
