### ISSUE TITLE
有的页面翻译的话是失效的，就比如火狐扩展插件下面的评论翻译就会不起作用。还有一些图片里的文字也不起作用的

### ISSUE THREAD

**Issue by carryyourself** [FilipePS/Traduzir-paginas-web#615]

**Comment by FilipePS** [comment]
Unfortunately there is a list of sites that Firefox blocks access to by extensions and the site `addons.mozilla.org` is one of them.

About the images. This extension does not translate images themselves, however in cases where the text in the image is an HTML overlay it should be translated. If that's the case, could you send me a link to a sample site that has this problem?

**Comment by FilipePS** [comment]
Extension internal pages `(moz-extension://)` cannot be accessed by any extension either. So there's no way to translate either.
