### ISSUE TITLE
Website not translating

### ISSUE THREAD

**Issue by eclipsek20** [FilipePS/Traduzir-paginas-web#619]
I am reporting a bug, I am unable to translate the site sberbank.com/ru using either yandex or google translate. I do not know what it is causing, I have tried turning off all other extensions.

**Comment by FilipePS** [comment]
Sites can define parts that should not be translated. This site has defined everything as not to be translated. So nothing but the title has been translated.

**Comment by eclipsek20** [comment]
> Sites can define parts that should not be translated. This site has defined everything as not to be translated. So nothing but the title has been translated.

Is it possible to bypass to make it able to translate?

**Comment by FilipePS** [comment]
I added a commit to force the translation on that site. For some reason the creators of that site didn't want it to be translated, so I disabled the `Always translate from [...]` function for that site.
