### ISSUE TITLE
The color of the icon when focused

### ISSUE THREAD

**Issue by haiwx** [FilipePS/Traduzir-paginas-web#62]
![ICO](https://user-images.githubusercontent.com/13563349/97084957-e6c61980-164c-11eb-8263-d6b4b7829393.png)

Please fix it, thanks.

**Comment by FilipePS** [comment]
What theme are you using in Firefox?

**Comment by haiwx** [comment]
@FilipePS 

This one : https://addons.mozilla.org/en-US/firefox/addon/rainbow-blur-1/

**Comment by FilipePS** [comment]
It's normal for me
![Capturar](https://user-images.githubusercontent.com/54990796/100827467-88eed380-343b-11eb-9d50-70a446e6ed81.PNG)

**Comment by haiwx** [comment]
@FilipePS   Press F6 / Click address bar

**Comment by haiwx** [comment]
@FilipePS  This add-on is normal for me →  https://addons.mozilla.org/en-US/firefox/addon/side-view/

Maybe we should use SVG  directly in manifest.json . It is adaptive

![col](https://user-images.githubusercontent.com/13563349/101278892-5c4f0900-37f9-11eb-958f-f07002a49849.png)

![or](https://user-images.githubusercontent.com/13563349/101279025-3b3ae800-37fa-11eb-8f74-90847eca15d6.png)

**Comment by FilipePS** [comment]
I did several tests and for the extension to have this behavior you need to have gecko id @ mozilla.org
I don't know if I can use this gecko id in my extension.
