### ISSUE TITLE
When will the plugin be updated on the Firefox expansion store?

### ISSUE THREAD

**Issue by TimeToGone** [FilipePS/Traduzir-paginas-web#625]
I would like to ask when the 9.7.0.3 plugin can be updated to the Firefox extension store? I installed the plugin, but Firefox did not pass and prompted that there was no signature.

**Comment by FilipePS** [comment]
I uploaded it to **addons.mozilla.org** four days ago. However, there is no prediction of when the new version will be approved. It never took so long for a new version to be approved.

**Comment by TimeToGone** [comment]
> I uploaded it to **addons.mozilla.org ** four days ago. However, there is no prediction of when the new version will be approved. It never took so long for a new version to be approved.

Thanks for your reply. If I don't change the version of Firefox, is there any other way to install the new version of the plugin?

**Comment by FilipePS** [comment]
The new version can be installed via XPI file.
https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7.2
