### ISSUE TITLE
Not functioning when using reader mode

### ISSUE THREAD

**Issue by SakanaBook** [FilipePS/Traduzir-paginas-web#626]
The extension will not work when using Firefox reader mode.

**Comment by FilipePS** [comment]
Unfortunately, Firefox's native read mode blocks all site scripts and extensions, so there's no way to translate.
Alternatively you can install the [Tranquility Reader](https://addons.mozilla.org/firefox/addon/tranquility-1/) extension. It has a reading mode that does not block extensions from working.
