### ISSUE TITLE
Override settings locale

### ISSUE THREAD

**Issue by TheFireRed** [FilipePS/Traduzir-paginas-web#63]
Would it be possible to add a setting that changes the settings' language? My locale is Spanish but I'd very much prefer to have English settings.

**Comment by FilipePS** [comment]
Do you want the extension interface to be in English?

**Comment by TheFireRed** [comment]
Yes

**Comment by FilipePS** [comment]
What is the problem of putting the browser in English?
The search results will still be in Spanish.
