### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by acrazing** [FilipePS/Traduzir-paginas-web#630]
Are there plans to publish as a npm package? Instead of using as an extension.

For example, I hope we can do this:

```ts
import { translate } from 'some-package';

// translate the page from English to Spanish
const dispose = await translate('es', document.body, 'en');

// revert to English
await dispose();
```

**Comment by FilipePS** [comment]
There is no plan for that.
What's the point of that, adding translation to your site without needing an extension?
