### ISSUE TITLE
Extension not updating in Firefox

### ISSUE THREAD

**Issue by MInessota** [FilipePS/Traduzir-paginas-web#631]

**Comment by FilipePS** [comment]
Unfortunately the new version has not yet been approved by Mozilla. For now you can install the [new version](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7.2) by clicking Download and install this file [TWP_9.7.2.10_Firefox.xpi](https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v9.7.2/TWP_9.7.2.10_Firefox.xpi).

**Comment by MInessota** [comment]
Thank you very much, it worked perfectly, great job it's my favorite extension!

**Comment by Glassertje** [comment]
Thank you for the update. Use your plugin every day.
