### ISSUE TITLE
Add pronunciation buttons to both the original text and translation.

### ISSUE THREAD

**Issue by MW1Z** [FilipePS/Traduzir-paginas-web#635]

**Comment by FilipePS** [comment]
What is the selected text translated? There is already a button to listen to the pronunciation of the original and translated text.

So clarify better what you are suggesting.

**Comment by FilipePS** [comment]
When translating the selected text there is already a button to listen to the pronunciation of the original and translated text.

So clarify better what you are suggesting.

**Comment by MW1Z** [comment]
Sorry, I didn't see the "display original text" button before

**Comment by MW1Z** [comment]
can't see original text when reading pdf file in browser,other website is fine,I just started using it and didn't express it clearly
