### ISSUE TITLE
Why can't interfaces like this website's comment section be translated?

### ISSUE THREAD

**Issue by yangchen158158** [FilipePS/Traduzir-paginas-web#637]
https://www.foxnews.com/tech/flashback-stephen-hawking-warned-ai-end-human-race-years-leading-death

Why can't interfaces like this website's comment section be translated?

**Comment by FilipePS** [comment]
For me the comments section is not appearing on this site. Do I need to do anything for the comments section to appear?

**Comment by yangchen158158** [comment]
Scroll down to the bottom, and you will be able to see the comments section. However, these cannot be translated.

**Comment by yangchen158158** [comment]
> For me the comments section is not appearing on this site. Do I need to do anything for the comments section to appear?

https://www.yahoo.com/news/belarus-president-putin-ally-alexander-020028172.html
Are there similar URLs where the comment section cannot be translated?

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/issues/654
