### ISSUE TITLE
TWP Mobile, refresh, Reddit.

### ISSUE THREAD

**Issue by opqriu** [FilipePS/Traduzir-paginas-web#641]
When I click on a post on Reddit, I get a blank page.
I have to refresh (F5).

If I turn off TWP, I don't get a blank page and don't need to refresh.

**Comment by FilipePS** [comment]
I opened reddit and this problem occurred.
I reloaded the page and it stopped happening even with the extension active and working.
Does it always happen to you? it stopped happening to me.
