### ISSUE TITLE
The update shows release note when that option is set to NO

### ISSUE THREAD

**Issue by TeddAndersen** [FilipePS/Traduzir-paginas-web#642]
When the plugin updated today... to version 9.7.2,  the Release notes page poped up.
The option to view this is set to NO in the other settings.

"Show release notes when updating"
No

Miner thing but its is a BUG to not honor the settings you have set.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/issues/640
