### ISSUE TITLE
Release notes missing from AMO and from about:addons

### ISSUE THREAD

**Issue by grahamperrin** [FilipePS/Traduzir-paginas-web#645]
* https://addons.mozilla.org/en-GB/firefox/addon/traduzir-paginas-web/versions/9.6.1/updateinfo/ is OK
* https://addons.mozilla.org/en-GB/firefox/addon/traduzir-paginas-web/versions/9.7.2/updateinfo/ is empty, and so: 

![image](https://user-images.githubusercontent.com/192271/236707214-da221a42-7ea2-4c4a-bdc4-a2dd6adf7cf4.png)

* the tab is blank.

Can anyone summarise <https://github.com/FilipePS/Traduzir-paginas-web/compare/v9.6.1...v9.7.2>? 

Thanks

**Comment by FilipePS** [comment]
I added the release notes in [AMO](https://addons.mozilla.org/firefox/addon/traduzir-paginas-web/versions/).

You can also view the release notes here:
`moz-extension://095c8bd1-037c-4032-a265-0526fedaea99/options/options.html#release_notes`
https://github.com/FilipePS/Traduzir-paginas-web/releases

**Comment by grahamperrin** [comment]
So quick! Big thanks.
