### ISSUE TITLE
Update Croatian tanslation from Crowdin

### ISSUE THREAD

**Issue by milotype** [FilipePS/Traduzir-paginas-web#648]

**Comment by FilipePS** [comment]
Are you sure this translation is correct?
https://crowdin.com/translate/translate-web-pages/334/en-hr#14838

Assuming the language of the page is **German**, the text will be **Always translate from German**.
By checking the checkbox, whenever a site in German is opened, the translation will start automatically.

**Comment by FilipePS** [comment]
I have uploaded the new version **9.7.2.1** with the new crowdin translations.
I was only going to upload a new version of the extension when I finished version **9.8**, but I decided to go ahead and see if the Mozilla team is still slow to approve new versions.
