### ISSUE TITLE
How to install on Firefox on Android?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [FilipePS/Traduzir-paginas-web#655]
How to install on Firefox on Android?

@FilipePS

**Comment by FilipePS** [comment]
The best way is to use the Iceraven browser.
Iceraven is an improved version of Firefox Android, it allows you to install any extension, not just the recommended ones.

To install Iceraven download and install the APK of the latest version available here: https://github.com/fork-maintainers/iceraven-browser/releases

**Comment by FilipePS** [comment]
If you want to develop/improve **TWP** on android:
1. Install [Firefox Nightly](https://www.mozilla.org/firefox/channel/desktop/) on the computer.
2. Install [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) on android.
3. Install [web-ext](https://github.com/mozilla/web-ext).
4. Enable USB debugging on your android.
5. Enable debug menu in **Firefox Nightly** for android.
6. Enable remote USB debugging in **Firefox Nightly** for android.
7. Connect your android phone to PC via USB.
8. In the `src` folder of the extension run the command `web-ext run --target=firefox-android`. This command will fail, and you will be shown additional instructions to add to the command, follow the instructions.
9. At this moment the extension will already be installed in **Firefox Nightly** for android.
9. To debug the extension, open **Firefox Nightly** on your computer, on the `about:debugging` website click on the `Enable USB Devices` button, and connect to the device that appears.

**Comment by FilipePS** [comment]
To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
