### ISSUE TITLE
Assign translation services for websites

### ISSUE THREAD

**Issue by DeepTulip** [FilipePS/Traduzir-paginas-web#662]
Can we assign a translation service for a website?
bing translations are fast but not accurate. google is more accurate but slower and often doesn't work.
I would like to use bing for sites that are not looking for accurate translations and google for sites that are looking for accuracy.

**Comment by FilipePS** [comment]
There is no such option in the extension yet, and maybe it could be added in the future.

Interesting that for me Google is faster than Bing. What language are you translating to?

> google is more accurate but slower and often doesn't work.

When you say it doesn't work, is it just parts of the translation, or is the entire site not translated?

**Comment by DeepTulip** [comment]
Thanks for the reply. You can understand that my country is afraid of my access to google, or I am not qualified to access google as a slave.
