### ISSUE TITLE
Firefox for Android?

### ISSUE THREAD

**Issue by dm17** [FilipePS/Traduzir-paginas-web#67]
Any idea what is required to make this plugin work on Firefox for Android? I'm on Fennec from F-DROID and when I go to install it, add-ons says, "Not available on Firefox for Android" (only Firefox for Desktop).
Thanks!

**Comment by haiwx** [comment]
↓

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by dm17** [comment]
> ↓
> 
> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Thanks! It isn't in F-DROID, so I'll checkout how installing & upgrading works without Google Play Store.

**Comment by FilipePS** [comment]
You can also use this browser that is identical to Firefox.
[Iceraven Releases](https://github.com/fork-maintainers/iceraven-browser/releases)
Direct links:
[arm64 v8a](https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-1.4.0/iceraven-1.4.0-browser-arm64-v8a-forkRelease.apk)
[armeabi v7a](https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-1.4.0/iceraven-1.4.0-browser-armeabi-v7a-forkRelease.apk)

**Comment by festum** [comment]
Target languages doesn't work in Iceraven
