### ISSUE TITLE
There is no "Copy" button when needed)

### ISSUE THREAD

**Issue by vitalii2011** [FilipePS/Traduzir-paginas-web#670]
![0011](https://github.com/FilipePS/Traduzir-paginas-web/assets/41552153/99f3cfa2-899e-4bd6-9fc9-9b4d1a82fc52)

**Comment by FilipePS** [comment]
When the **Replace** button is available it replaces the **copy** button.
It is worth remembering that you can copy by selecting the text manually as well.

**Comment by vitalii2011** [comment]
"When the Replace button is available it replaces the copy button.", - Understood. Thanks for clarifying.
Then it's more of a site (Crowdin) issue, not an addon issue. The translation text replaces the text under "SOURCE STRING", which is wrong.

**Comment by FilipePS** [comment]
I think it was not clear what I wrote earlier, the problem was not related to the site.

I added a commit, so the button always appears even when translating selected text from inputs.
