### ISSUE TITLE
Portuguese (Portugal and Brazil)

### ISSUE THREAD

**Issue by DrRichLangford** [FilipePS/Traduzir-paginas-web#672]
The default that cannot be changed is to see pages in Portuguese from Brazil, not from Portugal.

translate.google.pt should be the default for pages in Portugal.

Most people think google translate only works for Brazil, but the address above solves that problem.

**Comment by FilipePS** [comment]
Can you show me an example text where the Portuguese translation on the website `translate.google.pt` is different from the website `translate.google.com`?

**Comment by FilipePS** [comment]
Due to inactivity I am closing this issue.
If necessary, create a new issue.
