### ISSUE TITLE
invisible translate icon in incognito

### ISSUE THREAD

**Issue by motfis** [FilipePS/Traduzir-paginas-web#678]
Hi, i have problem on the latest release. if i use incognito, the translate icon is white, while my url background is also white, so it is invisible. I need to use dark mode to be able to see the icon.
![Screenshot (7)](https://github.com/FilipePS/Traduzir-paginas-web/assets/8572695/5995920a-7a75-44e8-8a36-7a525137a075)

on normal mode, the icon is black.
![Screenshot (8)](https://github.com/FilipePS/Traduzir-paginas-web/assets/8572695/5c5f0331-692f-44eb-88dd-a161ef797ce1)

Can it be fixed?

**Comment by FilipePS** [comment]
What theme are you using in Firefox?

**Comment by motfis** [comment]
i use many different theme from store, like pastel gradient, lolipop road.
