### ISSUE TITLE
"Never translate this language" does not work as expected after a page refresh on some sites

### ISSUE THREAD

**Issue by bradenhilton** [FilipePS/Traduzir-paginas-web#68]
On Facebook and YouTube for example, if I highlight English text and set the extension to never translate this language, the extension performs as expected. If I refresh the page and highlight English text, the button appears offering to translate the selected text. The extension has English listed under "Never translate these languages" throughout all of this.

**Comment by FilipePS** [comment]
Are you using Firefox computer version?

**Comment by bradenhilton** [comment]
Yes. Is there a known issue I am unaware of?

**Comment by FilipePS** [comment]
Sometimes the language of the selected text is in a different language than the detected language of the website. And to show or not the button to translate selected text, the extension uses the detected language of the site.

**Comment by bradenhilton** [comment]
But if I select "Never translate this language" and English is added to the list, wouldn't that mean English was the detected language of the site? And it does work as I would expect it to work after that, right up until I refresh or leave the page as I explained earlier. After refreshing I can then select English text (on a site I can only assume was detected as English) and the button appears.

The button to translate the selected text even shows up when pausing/playing a YouTube video, or when clicking some of the UI elements of the player such as Captions and Options.

My YouTube language is set to British English and my YouTube location is set to United Kingdom. I can reproduce this easily by:

1. Go to the Trending page on YouTube GB
2. Highlight English text (video title, navigation etc) -> Translate button appears
3. Open extension options and select "Never translate this language" -> English is added to the list of languages to never translate
4. Highlight English text (video title, navigation etc) -> Translate button does not appear
5. Refresh the page
6. Highlight English text (video title, navigation etc) -> Translate button appears

If this is impossible to fix then that's fine, but it's definitely odd behaviour.

**Comment by FilipePS** [comment]
This bug that the button appears even when selecting to never translate this site has already been fixed. And about detecting the language of the selected text to show or not the button, it is not very viable because when selecting a few characters the native language detection of the browsers is not very accurate. And for those who need to translate the selected text, it may be a nuisance that this button does not appear sometimes.

**Comment by FilipePS** [comment]
The new version has settings for when this button should appear. What should solve this problem
