### ISSUE TITLE
Shortcut key cannot be set

### ISSUE THREAD

**Issue by Suuuuuummer-Day** [FilipePS/Traduzir-paginas-web#686]
The shortcut key "Input Shortcut" input box in the settings has not responded and cannot input a custom shortcut key. I don't know what the reason is.

![微信图片_20230710163218](https://github.com/FilipePS/Traduzir-paginas-web/assets/139114431/6d287e19-4136-4751-a3aa-ce6c3dcbd6db)

**Comment by FilipePS** [comment]
Unfortunately on Chromium-based browsers an extension cannot define these hotkeys. Instead, click that big button that says **Open native shortcut key manager**, there you can manage hotkeys for any extension.

**Comment by FilipePS** [comment]
Due to inactivity I am closing this issue.
If necessary, create a new issue.
