### ISSUE TITLE
browser_style issue

### ISSUE THREAD

**Issue by andika207** [FilipePS/Traduzir-paginas-web#689]
this extension seems to work well but it reports a bug on the extensions manager.

<a href='https://postimg.cc/zbLNQ1dh' target='_blank'><img src='https://i.postimg.cc/sXm2vj7T/screenshot-1.png' border='0' alt='screenshot-1'/></a>

**Comment by FilipePS** [comment]
Which browser are you using?

**Comment by FilipePS** [comment]
Due to inactivity I am closing this issue.
If necessary, create a new issue.
