### ISSUE TITLE
Google Translate option doesn't work anymore

### ISSUE THREAD

**Issue by msrn** [FilipePS/Traduzir-paginas-web#69]
As of today the translation stopped working. When user presses translate button nothing happens.

**Google Translate** option doesn't work to be exact. Yandex works normally.

**Comment by farag2** [comment]
Can confirm too.

**Comment by tonioriol** [comment]
For me it still works as normal.

**Comment by tonioriol** [comment]
Well it's weird, it works in pages i already entered and translated before. But if i go to pages i never visited/translated it doesn't work.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/feddec3ee9b4e6b9cc38e040649ba2c52cc55918
