### ISSUE TITLE
The extension stopped translating from Lithuanian

### ISSUE THREAD

**Issue by vzabawski** [FilipePS/Traduzir-paginas-web#693]
Several weeks ago, the extension stopped detecting Lithuanian (now it displays "Unknown" language) and the translation from Lithuanian stopped working.

<img width="615" alt="image" src="https://github.com/FilipePS/Traduzir-paginas-web/assets/17778043/5b98c77b-d38f-4965-9bd1-d75df24fc634">

Extension version: 9.8.1.0
Translation engine: Google (but doesn't seem to be relevant)

**Comment by FilipePS** [comment]
Please provide a link to a website that has this issue.

**Comment by FilipePS** [comment]
I tested some websites in Lithuanian and it worked.
If you have any more bugs please create a new issue.
