### ISSUE TITLE
not fully translate

### ISSUE THREAD

**Issue by 14okt** [FilipePS/Traduzir-paginas-web#697]
on the site https://www.php.net/ this app does not fully translate

**Comment by FilipePS** [comment]
I tested it and managed to translate the entire page.

1. What language are you translating into?
2. What translation service are you using?
3. Is the problem happening on the **php.net** homepage or is it on another page of that site?

**Comment by 14okt** [comment]
![Screenshot_420](https://github.com/FilipePS/Traduzir-paginas-web/assets/134655028/a4c44f8a-698b-4121-be0a-555c691674bc)

```
<div class="phpcode">
<code>
<span class="html">
```

**Comment by FilipePS** [comment]
The `<code>` tag is normally used for code and should not be translated. In this case I recommend using the option to translate selected text.
