### ISSUE TITLE
Feature request - Possible in chromium?

### ISSUE THREAD

**Issue by EvilSpark** [FilipePS/Traduzir-paginas-web#7]
Hey dev, is it possible to port this extension to chromium based browsers since both use web extension api?

**Comment by FilipePS** [comment]
It's possible, you just need to change a few things.

Em qui, 6 de ago de 2020 07:10, Kamran Tahir <notifications@github.com>
escreveu:

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/2781a9d0585df52e4dcc0dee5d5227550a66b1c5
