### ISSUE TITLE
Support for Firefox for Android

### ISSUE THREAD

**Issue by kil0ba** [FilipePS/Traduzir-paginas-web#701]
Hi!

Is support for Firefox on Android being planned?

**Comment by FilipePS** [comment]
Firefox for Android has been supported for years, the problem is that Mozilla only lists recommended extensions.
What you can do is install an alternative version of Firefox, [Iceraven](https://github.com/fork-maintainers/iceraven-browser/releases).

**Comment by gaul** [comment]
I can confirm that this extension now works in Firefox 120 nightly.  Context: https://blog.mozilla.org/addons/2023/09/27/test-firefox-android-extensions-and-help-developers-prepare-for-an-open-mobile-ecosystem-in-december/

**Comment by joshcangit** [comment]
Still, Firefox Nightly can't install this extension from AMO.

**Comment by 0x391F** [comment]
Now you can install it now https://addons.mozilla.org/zh-CN/android/addon/traduzir-paginas-web/, this bug could close now.

**Comment by FilipePS** [comment]
To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
