### ISSUE TITLE
Request: Add <tex-math> ignore feature

### ISSUE THREAD

**Issue by moonyoulove** [FilipePS/Traduzir-paginas-web#704]

**Comment by FilipePS** [comment]
Could you give me more info about `<tex-math>`?
Is this a part of some framework?

**Comment by moonyoulove** [comment]
Yes, it should be [MathJax](https://www.mathjax.org/), but it doesn’t seem to have a unified form? My wish is to not translate those mathematical formulas when translating web pages, big thanks.

**Comment by FilipePS** [comment]
I looked at this [demo](https://www.mathjax.org/#demo) and **MathJax** seems to use tags that start with `mjx-`.
What site did you see this `tex-math` tag on?

**Comment by moonyoulove** [comment]
In the IEEE Xplore website
![](https://i.imgur.com/H4mdADb.png)

**Comment by moriyan0116** [comment]
In ar5iv, <math> tag is used.
How do you feel about adding any specific tag ignore option?

**Comment by moonyoulove** [comment]
I'm using the code below in a userscript, the math formula doesn't seem to have a specific tag in other paper sites (ScienceDirect, Springer), it's the class name `MathJax`. I wrap it with `<code>` to avoid translation, but I have to use `setInterval` to keep running because the content of the page loads according to the scrollbar
```js
setInterval(() => {
    const texes = document.getElementsByClassName("MathJax");
    for (const tex of texes) {
        if (tex.parentElement.tagName !== "CODE") {
            const code = document.createElement("code");
            tex.parentElement.insertBefore(code, tex.nextSibling);
            code.appendChild(tex);
        }
    };
}, 200);
```

**Comment by moriyan0116** [comment]
ar5iv may use wrapped class for MathJax and the class name is  `ltx_Math`.

**Comment by FilipePS** [comment]
> ar5iv may use wrapped class for MathJax and the class name is `ltx_Math`,`ltx_equation`.

@moriyan0116  Please provide an example link on the **IEEE Xplore** and **ar5iv** sites.

@moonyoulove Please provide an example link on the **ScienceDirect** and **Springer** sites.
