### ISSUE TITLE
Issue in Ukrainian translation

### ISSUE THREAD

**Issue by e2t** [FilipePS/Traduzir-paginas-web#710]
One option should be about page translation, the second - about selected text. The same thing is written in Ukrainian, about translating the page.
![зображення](https://github.com/FilipePS/Traduzir-paginas-web/assets/28775275/5039e9b8-bd4f-441b-85f6-088c46f2ddd6)

**Comment by FilipePS** [comment]
I identified that this also occurs with some other languages, problem fixed.
If you want better translation quality in the extension's interface, you can use **Crowdin**.
https://crowdin.com/project/translate-web-pages/uk
