### ISSUE TITLE
Button does not work on Firefox mobile nightly

### ISSUE THREAD

**Issue by Papitas30** [FilipePS/Traduzir-paginas-web#713]
The button _"Automatically translate when clicking on a link that takes you to the same domain as the current site"_ is always on _No_ even when I click on it and select _Yes_. It's always stuck on _No_ and it doesn't switch. This bug has been around for some time and I'm surprised it hasn't been fixed yet.

**Comment by Sparxcode** [comment]
Can anything be done about it?

**Comment by FilipePS** [comment]
To fix this problem you need to use another version of the extension, on your Firefox for Android, uninstall the current version of TWP and follow these steps.

To use the extension on _Firefox_ for _Android/iOS_, follow these steps:
1. Install the latest version of _Firefox (v120+)_.
2. Open the extension manager.
3. Scroll down and click **Find more extensions**.
4. On the add-ons website, search for **TWP**.
5. Install the **TWP - Translate For Mobile** extension.
