### ISSUE TITLE
BUG- auto translation not working in firefox android

### ISSUE THREAD

**Issue by Gamefire238** [FilipePS/Traduzir-paginas-web#738]
The button to check automatic translation in settings won't click, and the automatic translation option is also missing from the translation popup bar

**Comment by JordanPh15** [comment]
Comigo está o mesmo problema!

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
