### ISSUE TITLE
Suggesting: DeepL API Support

### ISSUE THREAD

**Issue by JaydenMcEncroe** [FilipePS/Traduzir-paginas-web#75]
DeepL Translator is a neural machine translation service, it is wildly considered to be more accurate and nuanced than Google Translate.

It is not a free service, however, the API access key can be as cheap as HK$20 (US$2.5) per month from some [provider](https://a-translator.royli.dev/).

May I suggest to add DeepL API support in your add-on, allow the user to fill in API keys they purchased by themselves?

API Document can be found here: https://www.deepl.com/docs-api/introduction/

Many thanks for your great work on this add-on!

**Comment by joaoasrosa** [comment]
I'm more than happy to pay for this service; in the end, give us options to select the translation provider.

**Comment by FilipePS** [comment]
DeepL does not support translation in HTML format, so the extension could only be used to translate the selected text.
And this site a-translator.royli.dev, the price of HK $20.00 is for 80 thousand characters only, only 1 article from wikipedia already has this size.
