### ISSUE TITLE
Add options on Firefox Android to translate directly with two, three or four fingers without displaying the bottom bar

### ISSUE THREAD

**Issue by lindongbin** [FilipePS/Traduzir-paginas-web#751]
Currently, the translation operation on Android Firefox is a bit cumbersome. I hope this function can be added.

**Comment by lindongbin** [comment]
The effect hope to achieve: touch the screen with two fingers to directly translate the web page, and touch the screen with two fingers again to restore the original text, without displaying the translation bar at the bottom.

**Comment by FilipePS** [comment]
This option will not be added.

I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
