### ISSUE TITLE
Unable to translate comments on this page

### ISSUE THREAD

**Issue by lindongbin** [FilipePS/Traduzir-paginas-web#76]
https://www.rt.com/usa/511996-mozilla-firefox-deplatform-trump-internet/

**Comment by lindongbin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1209390

**Comment by FilipePS** [comment]
For me it's translating normally

**Comment by lindongbin** [comment]
> For me it's translating normally

![Screenshot_2021-02-18-08-21-27-267_org mozilla firefox](https://user-images.githubusercontent.com/3154109/108285585-5d6dc080-71c2-11eb-8598-931994a2fc26.jpg)

**Comment by FilipePS** [comment]
I fixed the bug in this commit https://github.com/FilipePS/Traduzir-paginas-web/commit/e6e71cd8f85c428226870eb06c12c9f104483271, it is necessary to translate the page again for new comments
