### ISSUE TITLE
We really need a "always translate this language/website" button.

### ISSUE THREAD

**Issue by randomgermandude** [FilipePS/Traduzir-paginas-web#761]
Hi, first of all, really cool addon 👍🏼😊. Because of this addon and general addon support, I have now switched from Kiwi Browser back to Firefox on mobile, which is much more practical because of the synchronization with other devices. 

But unfortunately it's a bit annoying to have to click on the translate every time you open a new page or link on a site.

A function like the original would be really good here, so that you can either specify in the three-point menu at the bottom that you would like all pages on this website to be automatically translated, or with languages, for example Spanish or Polish websites are automatically translated. 

EDIT: In the translation settings I now found the option to automatically translate links with the same domain. Which should actually do almost the same thing. 

But unfortunately the option cannot be activated, I can select Yes as often as I want, the setting remains at No 😟

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md
