### ISSUE TITLE
`Always translate from` options not working on Chrome

### ISSUE THREAD

**Issue by quivenda** [FilipePS/Traduzir-paginas-web#767]
The option `Always translate from` is grayed out on Chrome. Are there any settings that can enable these settings?

![quivenda 2024-01-29 00 08 13-shadow](https://github.com/FilipePS/Traduzir-paginas-web/assets/125377517/25d97981-9d99-4d88-afb1-c61ca1aaef62)

**Comment by FilipePS** [comment]
From the image, you could see that the extension did not identify the website's language, so that option would not be available in these cases.

**Comment by FilipePS** [comment]
This second error was actually happening in Chrome, and prevented the selected text translate panel from being localized in the language selected for the interface.
I already fixed it.
