### ISSUE TITLE
translate bug

### ISSUE THREAD

**Issue by uvicorn** [FilipePS/Traduzir-paginas-web#77]
![изображение](https://user-images.githubusercontent.com/59787538/105490108-e2120f80-5ce6-11eb-9908-1bddf7e03c6a.png)

**Comment by FilipePS** [comment]
Apparently there is no way to solve this problem. If you can provide the page link I can analyze it better.

**Comment by peach-lasagna** [comment]
https://neovim.io/doc/user/insert.html#i_ALT
