### ISSUE TITLE
Issue: Auto-Translation failure in private windows, no translation on Yandex.xxx, Firefox: No options in the "More Options Window"

### ISSUE THREAD

**Issue by Klipperken** [FilipePS/Traduzir-paginas-web#774]
Hail:

I use the latest version of TWP on SMEdge and Firefox.
The issues I encounter:
1) No Auto-Translation at all in Private Windows (Both browsers).
2) In normal Windows (each browser): No translation for Yandex Search Engines, nor when selecting "Translation", nor when in the "Always Translate These Sites.".

Firefox:
In both Normal and Private Windows:
No options in the "Options Window", and the  "More Options Window", when clicking whichever setting, I get nothing in the drop-down box, though all permissions are checked.
I can't select the slightest, which is quite annoying.

Please advice?

Kindest regards:
Klip.

**Comment by FilipePS** [comment]
1. For privacy reasons, the translation will not start automatically when using incognito windows.
2. In the Yandex search engine, translation does not occur due to a preference of the search engine itself.

>  No options in the "Options Window", and the "More Options Window", when clicking whichever setting, I get nothing in the drop-down box, though all permissions are checked.
I can't select the slightest, which is quite annoying.

Please show screenshots or videos of these problems.

**Comment by Klipperken** [comment]
Sure, sir:
![TWP 1](https://github.com/FilipePS/Traduzir-paginas-web/assets/65045523/78f87b7f-4ec9-4440-a10a-29e797e6a41e)
![TWP 2](https://github.com/FilipePS/Traduzir-paginas-web/assets/65045523/8e0db1f0-a275-4de1-a73c-bc4643860555)
![TWP 3](https://github.com/FilipePS/Traduzir-paginas-web/assets/65045523/f9165d69-3234-4a2d-9f6c-73439398d6e9)

Will this do?

**Comment by FilipePS** [comment]
When you open the configuration page, press F12 to open the Development Tool, take a screenshot and send it to me.

**Comment by Klipperken** [comment]
F12 opens not Development Tool, but Inspector on Firefox, sir?
Is that what you need?

**Comment by FilipePS** [comment]
I need to see if any errors appear
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/c2abdb75-d096-4d94-bb89-016127214a83)

**Comment by Klipperken** [comment]
Ah good, sir.
Apologies, it's very, very hectic here.
![Console](https://github.com/FilipePS/Traduzir-paginas-web/assets/65045523/63476ed4-fdf0-4738-a148-b7e1333ec5f1)
This is what you need, correct, sir?

**Comment by FilipePS** [comment]
Yes, that's what I need to see. It's an uncommon error.

Did you take this screenshot in Firefox? Is it the official Mozilla version? Which version?

And send me the SMEdge download link.

**Comment by Klipperken** [comment]
![Firefox](https://github.com/FilipePS/Traduzir-paginas-web/assets/65045523/d78a567d-ced6-4d92-b30e-06478e592ea3)
Official.
FF is auto-updated, no link.
MSEdge gets auto-updated, sir, no DL link here either, good sir.

**Comment by FilipePS** [comment]
Do you use any extensions related to privacy, cookies, ads, etc? which?

**Comment by Klipperken** [comment]
Cookie editor and Tampermonkey, but the Tampermonkey is inactive, sir.

**Comment by FilipePS** [comment]
You or some extension must have disabled the _sessionStorage_ and _localStorage_ API.
To activate again, follow the steps below:

### Firefox
Type `about:config` in the address bar, and click the **Accept the Risk and Continue** button.
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/84c62efb-7264-4f30-aad7-dedbf0d93f17)

Type `dom.storage.enabled` in the search box, and make sure the option is enabled (**true**).
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/daf63cb8-bd4c-437d-ad40-181331c20139)

### Chrome
Type `chrome://settings/content/siteData` in the address bar, and make sure this option is selected.
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/1d67c78c-9899-42bb-b9c3-f2dd460b777a)

### Edge
Type `edge://settings/content/cookies` in the address bar, and make sure this option is enabled.
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/ab2a7f3b-6522-41de-b15b-1af2b7041021)

**Comment by Klipperken** [comment]
I flipped it to False, quit FF, restarted FF, put it back to True ... no
change, sir.

**Comment by FilipePS** [comment]
Install Firefox Beta, do not log into your mozilla account, nor try to import data from other browsers and install **TWP** and check if it works.
https://www.mozilla.org/firefox/channel/desktop/

If it doesn't work, let me know what your operating system and version is.

**Comment by Klipperken** [comment]
W11Ent_x64 22H2 build 22621.3085, sir.

**Comment by FilipePS** [comment]
Can you confirm if you tested Firefox Beta and it didn't work either?

**Comment by Klipperken** [comment]
"Can you confirm if you tested Firefox Beta and it didn't work either?"
I do not have FF Beta, sir?

"In Firefox, type about:policies in the address bar and send me what appears."
Will do:
"The Enterprise Policies service is active."

**Comment by FilipePS** [comment]
Is this computer for work or school? They probably changed browser policies that caused this problem.
In the next version I will fix it so that the extension works, despite these policies.

**Comment by FilipePS** [comment]
Did the latest version fix the problem on MS Edge?
