### ISSUE TITLE
manifest_version error message

### ISSUE THREAD

**Issue by yong313** [FilipePS/Traduzir-paginas-web#777]
help

<img width="416" alt="스크린샷 2024-02-14 11 06 46" src="https://github.com/FilipePS/Traduzir-paginas-web/assets/85574104/9cff5f96-f1b4-4eea-8b91-f1b2733e69f7">
<img width="669" alt="스크린샷 2024-02-14 11 06 50" src="https://github.com/FilipePS/Traduzir-paginas-web/assets/85574104/ec8102f5-62c8-460f-bc8a-d14a5718eb4c">

**Comment by FilipePS** [comment]
This error does not affect the extension at all.
