### ISSUE TITLE
Do not pop up when the page language is unknown

### ISSUE THREAD

**Issue by lindongbin** [FilipePS/Traduzir-paginas-web#780]
eg. https://tieba.baidu.com/f?kw=google

**Comment by FilipePS** [comment]
Which browser are you using?

**Comment by lindongbin** [comment]
> Which browser are you using?

firefox android 123.0

**Comment by FilipePS** [comment]
Are you already using version 10.0 of the extension or is it still version 9.9.0.3?

**Comment by lindongbin** [comment]
twp 10.0
![Screenshot_20240221-130416](https://github.com/FilipePS/Traduzir-paginas-web/assets/3154109/5dd1e6d3-87ba-40b5-aa1b-832ceb9e8604)


> Are you already using version 10.0 of the extension or is it still version 9.9.0.3?

**Comment by FilipePS** [comment]
How did you install version 10 on Firefox Android?

**Comment by lindongbin** [comment]
> How did you install version 10 on Firefox Android?

signed on addons.mozilla.org
about firefox click 5 time logo
install xpi from file
![Screenshot_20240221-135134](https://github.com/FilipePS/Traduzir-paginas-web/assets/3154109/2c18159d-13f4-44d6-ad57-0570d7090aaf)
![Screenshot_20240221-135243](https://github.com/FilipePS/Traduzir-paginas-web/assets/3154109/ae31f1ad-5f10-41c1-960c-640a69a165cb)

**Comment by lindongbin** [comment]
![Screenshot_20240221-135538](https://github.com/FilipePS/Traduzir-paginas-web/assets/3154109/9f6640d3-eb19-40e4-be0b-2e3fd2bbbd9d)
some code shown when pop up
