### ISSUE TITLE
Support edit the google translation server

### ISSUE THREAD

**Issue by lindongbin** [FilipePS/Traduzir-paginas-web#781]
Google Translate cannot be used in China, I reverse proxy the google api, I hope to edit the translation server and google tts server

**Comment by lindongbin** [comment]
![Screenshot_20240222-105803](https://github.com/FilipePS/Traduzir-paginas-web/assets/3154109/db76e2f4-399d-49c2-8258-7b308c69dd18)
just like this addon

**Comment by FilipePS** [comment]
If you change `translate.googleapis.com` to your proxy domain, will the request work?

`https://translate.googleapis.com/translate_a/t?anno=3&client=te&v=1.0&format=html&sl=auto&tl=en&tk=573676.923403&q=%3Cpre%3E%20Willkommen%20bei%20Wikipedia%3C%2Fpre%3E`

**Comment by lindongbin** [comment]
> If you change `translate.googleapis.com` to your proxy domain, will the request work?
> 
> `https://translate.googleapis.com/translate_a/t?anno=3&client=te&v=1.0&format=html&sl=auto&tl=en&tk=573676.923403&q=%3Cpre%3E%20Willkommen%20bei%20Wikipedia%3C%2Fpre%3E`

It worked, you can try https://gt.006750.xyz/translate_a/t?anno=3&client=te&v=1.0&format=html&sl=auto&tl=en&tk=573676.923403&q=%3Cpre%3E%20Willkommen%20bei%20Wikipedia%3C%2Fpre%3E

**Comment by lindongbin** [comment]
and I change the tts server to gt.006750.xyz it also worked
https://github.com/FilipePS/Traduzir-paginas-web/blob/2f81fad0b005b69791daa729a20aedda77eccad2/src/background/textToSpeech.js#L515
