### ISSUE TITLE
关于一个重大bug，一个影响体验的bug以及一些建议

### ISSUE THREAD

**Issue by wnbh** [FilipePS/Traduzir-paginas-web#782]
系统:安卓
应用场景:Kiwi Browser
扩展版本:10.0.0.0

重大bug:
只要界面上方存在翻译悬浮窗(且悬浮窗无法拖动关闭)，网页下方便会弹出一段代码，见下图
![1](https://github.com/FilipePS/Traduzir-paginas-web/assets/30308165/3150b085-d126-4069-b5ec-da3b6c105c15)

影响体验的bug:
1.我设置了中文显示，可新的翻译悬浮窗有些地方还是英文，见下图
![2](https://github.com/FilipePS/Traduzir-paginas-web/assets/30308165/01bfe629-165c-4e33-8129-346fe7d5c626)

![3](https://github.com/FilipePS/Traduzir-paginas-web/assets/30308165/dd68bff3-e677-426d-8a9d-7584a95a7db4)

建议:
1.希望增加一个开关，让用户选择悬浮窗弹出的位置，现在悬浮窗固定在上方，单手不方便操作。
2.现在是默认页面打开就会弹出翻译悬浮窗，希望添加一个开关，因为有的时候我并不需要它每次都弹出，就像安卓三指操作一样，让用户自己选择，而不是强制主动弹出，那样我就不需要每次等待几秒或者三指操作关闭翻译悬浮窗。

**Comment by FilipePS** [comment]
The first error I fixed in a commit.
And about the interface localization, you can locate the interface for Simplified Chinese on crowdin.
https://crowdin.com/editor/translate-web-pages/334/en-zhcn

**Comment by FilipePS** [comment]
> The translation floating window that pops up in the latest version still cannot be dragged and closed. Please solve it as soon as possible. There are also some suggestions. For the convenience of one-handed operation, I hope that the pop-up floating window will allow users to choose to appear at the top or bottom.

For now you can close/open the popup by touching three fingers on the screen.

**Comment by wnbh** [comment]
The three-finger operation is relatively cumbersome. I checked the update record of version 10.0.0.0, and it mentioned that the pop-up window can be hidden by dragging it. When I actually operated it, the floating window only shook and was not hidden.

**Comment by FilipePS** [comment]
> The three-finger operation is relatively cumbersome. I checked the update record of version 10.0.0.0, and it mentioned that the pop-up window can be hidden by dragging it. When I actually operated it, the floating window only shook and was not hidden.

Currently this feature is only working on Firefox Mobile.

**Comment by wnbh** [comment]
> > The three-finger operation is relatively cumbersome. I checked the update record of version 10.0.0.0, and it mentioned that the pop-up window can be hidden by dragging it. When I actually operated it, the floating window only shook and was not hidden.
> 
> Currently this feature is only working on Firefox Mobile.

Will you consider supporting Kiwi Browser in the future? Can Kiwi Browser implement this operation? If not, my suggestion is to double-click the pop-up window to hide it or add a button to hide the pop-up window. I hope you will consider it.
