### ISSUE TITLE
TWP -Vivaldi Browser

### ISSUE THREAD

**Issue by merlin555** [FilipePS/Traduzir-paginas-web#783]
Hello everyone,

The TWP extension (TWP_10.0.0.0_Chromium.zip, also version 9.x) shows the symbol in Vivaldi,
unfortunately, it doesn't say whether the page has been translated.

The TWP symbol is always colored and does not change to black/white if the page is not translated.

Greetings,

 Merlin

**Comment by FilipePS** [comment]
I tested it and it seems to be working in Vivaldi.
Provide screenshots of this issue.

**Comment by merlin555** [comment]
@FilipePS 
The extension already works with Vivaldi.
Only the color of the symbol always remains colored.
On Firefox, the TWP icon is only colored when the page has been translated.
Otherwise, the symbol is gray.
Here's a video:
[Video](https://mega.nz/file/I8AVTC4Q#UHEMXp3ymx9mxpN_Y0oE1a8W67t0lefUQ9uHicbjX74)
