### ISSUE TITLE
Add the reverse translation language.

### ISSUE THREAD

**Issue by dascratch** [FilipePS/Traduzir-paginas-web#79]
The language into which to translate my native language (which I chose as the target language).

**Comment by FilipePS** [comment]
I didn't quite understand what I meant. But you to change the target language in the settings.

**Comment by dascratch** [comment]
I'm Russian. Target language is my native language. What is your native language? How to translate native language in language that i trying to learn? I need to change settings every time i need to translate conversely?

**Comment by VladimirCo** [comment]
Indeed, it would be very convenient if the function of translating the selected text had the ability not only to translate a foreign language into the native language - BUT also translate the native language into a foreign one simply by highlighting the text

**Comment by FilipePS** [comment]
These features have already been implemented.
