### ISSUE TITLE
Slower Update Release [Suggestion] 

### ISSUE THREAD

**Issue by xenstar** [FilipePS/Traduzir-paginas-web#796]
### Is your feature request related to a problem? Please describe

Not applicable.

### Describe the solution you'd like

I think instead of releasing updates frequently, you can push updates every week and sort it out like major updates or pre-releases like that. 

Because in Brave Browser, we have to update it manually, and it's only possible to update some of the time manually. 

### Did you fill in all the fields correctly?

- [X] Yes, everything is fine!

**Comment by FilipePS** [comment]
When version 10.0 was released, I really thought there would be no significant problems that would require urgent updates, I was wrong...
I will release pre-releases again in the next versions.
