### ISSUE TITLE
[Bug] Language selector is empty

### ISSUE THREAD

**Issue by feiercrack** [FilipePS/Traduzir-paginas-web#797]
### Steps To Reproduce

its not working anymore with current Brave Browser 
Version 1.63.162 Chromium: 122.0.6261.69 
Windows 11 Pro x64 23H2
[https://i.gyazo.com/f84795a1f0feac6fcc23fb13b20f46da.png](https://i.gyazo.com/f84795a1f0feac6fcc23fb13b20f46da.png)
[https://i.gyazo.com/6456d64f4823e5961008a4b22640190f.png](https://i.gyazo.com/6456d64f4823e5961008a4b22640190f.png)

no pulldown menus for the languages
nothing in context menu
nothing happens when i left-click and mark an text...

what to do?

### Expected Result

look above

### Actual Result

look above

### Screenshots or Videos

look above

### Operating System

Windows

### Web Browser

Brave

### Extension Version

current

### What are you doing?

- [X] I am reporting a bug

**Comment by FilipePS** [comment]
Are you a new user or did this problem start to happen after an extension update?

On the extension configuration page, press **F12** or **Ctrl + Shift + i** to open Developer Tools, then click on the **Console** tab. Then take a screenshot and send it to me.
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/ea64d4c2-ccdd-44ca-8987-1118fa3cd31d)

In the Brave extension manager, check if this **Errors** button appears, if it appears then click on it and take a screenshot.
`brave://extensions/`
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/9187d889-11f9-4c73-b58c-49b2016a4991)

**Comment by FilipePS** [comment]
Related issue: https://github.com/FilipePS/Traduzir-paginas-web/issues/774#issuecomment-1937866066

**Comment by feiercrack** [comment]
[https://i.gyazo.com/051996ed9b59376c38f1fb14130a2e29.png](url)
[https://i.gyazo.com/7a4b1eeb79e37881b37afce6bc315629.png](url)

it came somehow when i added the v10.0.0.4   
i had the v9.61 installed previously, but didnt disabled it in the browser. so i had 2 versions at once -.-

thats because i have 2 different folders. 
Auto-translate-extension
and
TWP 

so i didnt saw that -.-

**Comment by FilipePS** [comment]
If you uploaded the image to a third-party website, you can place the image here like this: `![image](IMAGE-URL)`, for example: 
`![image](https://i.gyazo.com/051996ed9b59376c38f1fb14130a2e29.png)`.

If you copied the image (if the image is in your clipboard), just press `Ctrl + V` or drag the image to the comment editor.

Or click this button and select your image.
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/e586c72f-ddb0-4693-ae22-d5970d0d0177)

**Comment by FilipePS** [comment]
When removing the old version did the problem persist?

On the extension configuration page, press **F12** or **Ctrl + Shift + i** to open Developer Tools,
Type this code and press enter, take a screenshot of the result.
`chrome.i18n.getAcceptLanguages(a => console.log(a))`

**Comment by feiercrack** [comment]
![image](https://i.gyazo.com/eb5c74d75e4370cabf646b51632c881f.png)

after removing old .ver problem still persists... even removing both, restart browser doesnt help -.-

**Comment by FilipePS** [comment]
Do you remember installing any extensions or changing any browser settings that could lead to this problem?

Reinstall the old version of the extension to see if it works.

**Comment by feiercrack** [comment]
> Do you remember installing any extensions or changing any browser settings that could lead to this problem?
> 
> Reinstall the old version of the extension to see if it works.

tried that already, no chance.. i didnt change anything, except brave update and your extension...

**Comment by FilipePS** [comment]
Access this link `brave://settings/languages` and take a screenshot.

**Comment by feiercrack** [comment]
![image](https://i.gyazo.com/37dff2fda56ffbe10e83e34c3b4910ca.png)

**Comment by FilipePS** [comment]
Click on **Add languagues** and add your native language.

**Comment by feiercrack** [comment]
> Access this link `brave://settings/languages` and take a screenshot.

...holy... i added german to UI and english as second....

how tha heck could this be resetted???

thanks alot, it works flawless now again, same as before.

thnak you^^

cheers :-)
