### ISSUE TITLE
Remove widget translation algorithm?

### ISSUE THREAD

**Issue by ArypTi** [FilipePS/Traduzir-paginas-web#8]
I'm worried that this add-on could be removed from AMO because of a remote script injection policy violation.
If there is no significant reason to keep the translation algorithm that uses widgets, I suggest remove it for safety.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/8192ddd8a059b8fde9288ac3a5b1fbaf63635bf7
