### ISSUE TITLE
Stop forcibly opening Release Notes

### ISSUE THREAD

**Issue by PantheonOfSol** [FilipePS/Traduzir-paginas-web#800]
### Body

Not sure why so many devs choose to do this, but having the Release Notes automatically open, with no way to change the setting is hella invasive, especially when I'm actually trying to work on something. I'm a big girl, I can open the release notes if I really want to (which I almost never do).

### What did you just do?

- [X] I wrote an objective issue, easy to understand.

**Comment by FilipePS** [comment]
Extensions settings -> Others -> Show release notes when updating -> No
