### ISSUE TITLE
Audio mumbles and jumps when TWP add-on is enabled

### ISSUE THREAD

**Issue by ryo-0509503** [FilipePS/Traduzir-paginas-web#804]
### Body

Dear TWP Support

I use TWP everyday because it is a powerful tool.
The other day I was translating with TWP while listening to music, but the music was mumbling.
My environment is as follows.

[Environment at the time the symptom occurred]
OS : Debian GNU/Linux 12 (bookworm) 64-bit
Xfce version : 4.18
GTK version : 3.24.38
Kernel version : 6.1.0-18-amd64
CPU : AMD Athlon 3000g with radeon vega graphics x 4
Memory : 15.3GiB
GPU : llvmpipe(LLVM 15.0.6, 256bits)(15.3GiB)
Motherboard : B550 Steel Legend
Firefox Browser Extended Support Release version : 115.8.0esr(64bit)
VideoLAN Version : 3.0.20 Vetinari
TWP - Translate Web Pages version : 10.0.0.4

[Symptom]
Audio mumbles and skips.
The audio is output by plugging an earphone jack into the front speaker jack (green) on the motherboard.

[Assumptions for investigation]
(a). With Firefox not running (TWP add-on enabled), start VideoLAN and output any audio. (I downloaded the following song and played it on VideoLAN)
https://drive.google.com/file/d/1VBMBVObzGRXUabrP9lU4apBVgIn5uUMx/view?usp=sharing

With the preconditions for the research satisfied, I tried the following [Investigation 1] to [Investigation 4].
[Survey 1] with Firefox running (TWP add-on enabled)
　(1). After performing [Investigation 1] with [Prerequisites for Investigation], [Symptom] occurs.
　　(1)-1. After (1), [Symptom] occurs even if the focus is moved to an application other than Firefox (e.g. Terminal).
　　(1)-2. When [Symptom] occurs, closing Firefox will resolve [Symptom].

[Investigation 2] While Firefox is running (TWP add-on disabled)
　(1). When [Investigation 2] is performed with [Prerequisite for Investigation] satisfied, [Symptom] does not occur.

[Investigation 3] Firefox not started (TWP add-on enabled)
　(1). When [Investigation 3] was performed with [Prerequisite for Investigation] satisfied, [Symptom] did not occur.

[Investigation 4] Firefox not started (TWP add-on disabled)
　(1). After performing [Investigation 4] with [Prerequisites for Investigation], [Symptom] did not occur.

[Occurrence in previous version]
I have never used TWP while listening to music before, so I can't confirm if similar problems occurred in the past.

We cannot discard the problem on the Firefox side, but we have contacted TWP first.
TWP is a great tool and I am supporting it behind the scenes.
Thank you for reading to the end, even though it has been a long time.

Thank you.

### What did you just do?

- [X] I wrote an objective issue, easy to understand.

**Comment by FilipePS** [comment]
I was unable to reproduce this problem, but it is probably related to https://github.com/FilipePS/Traduzir-paginas-web/issues/802.

**Comment by FilipePS** [comment]
As Mozilla always takes time to evaluate new versions of extensions publicly available on [AMO](https://addons.mozilla.org) I used an option to self-host the new version.
You can install it in Firefox through the file [TWP_10.0.1.0_Firefox.xpi](https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.0.1.0/TWP_10.0.1.0_Firefox.xpi) available in the release [Version 10.0.1.0](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v10.0.1.0).

**Comment by ryo-0509503** [comment]
Thank you Filipe.
I installed TWP v10.0.1.0. The audio mumbles and jumps issues have been resolved.

**Comment by FilipePS** [comment]
Please translate any selected text and then click the button to listen to the text and check if there are any problems with the audio while the text is spoken.

**Comment by ryo-0509503** [comment]
I translated the selected text while the audio of the music was playing, then clicked the button to listen to the text.
I confirmed that there was no problem with the sound of the music and the sound while the text was being read out loud. The problem was resolved.
