### ISSUE TITLE
Extension translation different from Google Translate

### ISSUE THREAD

**Issue by ThiagoRangel7** [FilipePS/Traduzir-paginas-web#81]
I'm using Google as the translation engine. Even though, there are some minor differences between the translated page within the extension and Google Translate's website.

Check rutracker.org as an example:

**Extension translation:**
![image](https://user-images.githubusercontent.com/39643122/106678624-dbfb1900-6599-11eb-8093-30cb5784e646.png)

**Google Translate translation:**
![image](https://user-images.githubusercontent.com/39643122/106678712-0351e600-659a-11eb-8d8a-483dcc4d6a71.png)

**Comment by FilipePS** [comment]
It is normal to have small differences.
I believe this was due to the difference between the "portion of text" that my extension and chrome sends to translate.
