### ISSUE TITLE
[Feature] Guide for installing TPW on Brave (With CRX and auto update) and Linux.

### ISSUE THREAD

**Issue by fabcard** [FilipePS/Traduzir-paginas-web#855]
### Is your feature request related to a problem? Please describe

Not applicable.

### Describe the solution you'd like

Hello.
How to allow the TPW extension to update itself on Brave browser and Linux, please?
The guide shows to install on Windows using a .reg file, but not on Linux. Some people are moving from Windows lately, including me, and would be much appreciated if you guys could also make an installation guide for Linux.
Thanks in advance.

### Did you fill in all the fields correctly?

- [X] Yes, everything is fine!

**Comment by FilipePS** [comment]
1. Download this CRX file [TWP_Chromium.crx](https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.0.1.0/TWP_10.0.1.0_Chromium.crx)
2. Open your browser's extension manager, you can find it at this link: `chrome://extensions`
3. Activate developer mode
4. Reload the extension manager page to avoid errors
5. Drag and drop the **TWP_Chromium.crx** file into the extension manager

**Comment by fabcard** [comment]
Hello @FilipePS 
Thank you for the reply. Doing what you said, the extension will self update when a new version is available?

**Comment by fabcard** [comment]
Obrigado :+1:
