### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by 3DZHio** [FilipePS/Traduzir-paginas-web#858]
### Body

Linux ( Ubuntu 24.04 ); FireFox;
Is it possible to automate the process of initializing the configuration, so that I don't have to do it every time through “Options”? For example by moving the configuration file to a specific folder or is this already implemented but I don't know about it. 

### What did you just do?

- [X] I wrote an objective issue, easy to understand.

**Comment by FilipePS** [comment]
On the extension's settings page, there is a storage settings tab, and there you can backup/restore your settings.
