### ISSUE TITLE
Translation suggestion issue when excluding a language from the translation list

### ISSUE THREAD

**Issue by VladimirCo** [FilipePS/Traduzir-paginas-web#86]
I am a Russian-speaking user, and therefore when I visit Russian-speaking sites, I do not need a translation offer from Russian to appear when selecting a text - after all, I am Russian, my native language.
 That is why I added the Russian language to the list of languages not for translation in the settings. 
  BUT, even after that, in any case, there is a proposal to translate from Russian, which means this is the issue.
 For clarity, I decided to record a video for you: https://www.dropbox.com/s/eezdrea9aviyczh/Translation%20suggestion%20issue%20when%20excluding%20a%20language%20from%20the%20translation%20list%20%E2%80%94%20Mozilla%20Firefox%202021-02-05%2016-29-31.mp4?dl=0
 When user visit foreign sites, I find it very convenient to translate into native language when highlighting text. But when I ALREADY on a Russian site, I don't need to offer to translate from a Russian site when selecting text, if it's my native language. 
  Therefore, it would be convenient for translation sentences to appear IN ALL LANGUAGES - except for the native one. All that I have voiced above is also true for any other language, so the Russian language has nothing to do with it.

**Comment by FilipePS** [comment]
This feature was added
