### ISSUE TITLE
Indicate (through the icon) when the extension is active

### ISSUE THREAD

**Issue by AndreiMiculita** [FilipePS/Traduzir-paginas-web#88]
Hello,

I often find myself not knowing if the page I'm looking at is translated, or if it's actually the original.  It's possible to click on the icon to tell (if it says "show original" it means it's translated) but I think it would be much more straightforward if the icon also showed it.

So I think the icon should change color, or indicate somehow, when the page being displayed is translated.

Examples:
RES:
![Screenshot from 2021-02-11 18-19-22](https://user-images.githubusercontent.com/6352172/107672967-ca023000-6c95-11eb-8c8e-464345da50eb.png)
![Screenshot from 2021-02-11 18-19-30](https://user-images.githubusercontent.com/6352172/107672969-ca9ac680-6c95-11eb-95c9-e38f3333422b.png)
Firefox reader mode:
![Screenshot from 2021-02-11 18-19-54](https://user-images.githubusercontent.com/6352172/107672977-cd95b700-6c95-11eb-85f5-bee57a669669.png)
![Screenshot from 2021-02-11 18-20-01](https://user-images.githubusercontent.com/6352172/107672979-cd95b700-6c95-11eb-8a34-1b31972e2ed1.png)

**Comment by mikhoul** [comment]
I agree it would be really useful.    :octocat:

**Comment by FilipePS** [comment]
Added feature https://github.com/FilipePS/Traduzir-paginas-web/commit/0032d519f9b8cc8e5651a6ac1b6ea92413916fec

**Comment by AndreiMiculita** [comment]
Thanks! Not sure if you've encountered this, but at the moment, it only works when the Firefox theme is set to Default. The setting doesn't take effect in the Dark & Light themes.
