### ISSUE TITLE
No ability to 'always translate this language'

### ISSUE THREAD

**Issue by kylebakerio** [FilipePS/Traduzir-paginas-web#89]
In the main settings page for the extension, click 'always translate this language' just shows an empty box

In the context menu from the translate button, there is only 'never translate this language', not 'always translate this language'.

**Comment by FilipePS** [comment]
> 
> 
> In the main settings page for the extension, click 'always translate this language' just shows an empty box
There is currently a button to add a language
> 
> In the context menu from the translate button, there is only 'never translate this language', not 'always translate this language'.
And this checkbox will only appear if the language of the page is detected
