### ISSUE TITLE
[Feature request] Target lang option for each translate lang.

### ISSUE THREAD

**Issue by quroe** [FilipePS/Traduzir-paginas-web#90]
Could you add additional "Target language" option for each translate languages"?
I usually select English, but I want to select Japanese in some languages.

image:
![ex](https://user-images.githubusercontent.com/2657891/108090086-996b2d80-70bd-11eb-9e90-8193ebf960dd.png)

Thanks.

**Comment by FilipePS** [comment]
Implementing this should make some users more difficult, the new interface already complicates ...
And as the new interface already suggests 3 languages to translate, I think this feature is not needed.
