### ISSUE TITLE
(1694699) extensions conflict: loss of tabs with Translate Web Pages and Simple Tab Groups added to Firefox 86.0

### ISSUE THREAD

**Issue by grahamperrin** [FilipePS/Traduzir-paginas-web#92]
Spun off from https://github.com/Drive4ik/simple-tab-groups/issues/779#issuecomment-782650906

If a group with more than one tab is opened into a new window whilst Translate Web Pages  is enabled: 

* tabs that are not loaded are lost when the window closes. 

https://user-images.githubusercontent.com/192271/108603579-b004d380-73a0-11eb-905a-976ac7fec7a3.mp4

**Comment by grahamperrin** [comment]
### Regression in Firefox

▶ Mozilla bug [1694699 - Investigate tabs API regression in Firefox 86](https://bugzilla.mozilla.org/show_bug.cgi?id=1694699)

I'll leave this issue #92 open until it's known whether developers of extensions can do anything to mitigate the regression.

**Comment by FilipePS** [comment]
In the video even with my extension disabled this error occurred. So I can only say that the problem is not my extent.

In the video I noticed the delay in loading the extension popup and the tabs. Perhaps your computer is using too many resources and the contents of these tabs are being lost.

**Comment by grahamperrin** [comment]
Thanks for engaging, I appreciate you taking the time. 

The conflict is reproducible with a clean profile and fewer than ten tabs on a computer with 16 GB memory, so I doubt that it's a resource issue. 

> … with my extension disabled this error occurred. …

For your test, did you have Simple Tab Groups and Translate Web Pages _alone_ enabled – just the two extensions?

With that scenario, I could consistently avoid the issue by disabling Translate Web Pages. 

(Please note, this is not to point the finger of blame at any one extension. It's simply an extensions conflict in the context of a regression in Firefox.)

We have an amazingly fast response from Mozilla: 

* [⚙ D106317 Bug 1694699 - Avoid unnecessary string->URI conversions](https://phabricator.services.mozilla.com/D106317)

– needs review …

**Comment by FilipePS** [comment]
I installed the 3 tab extensions that you talked about. And I kept using all the extensions that you use and can't reproduce the problem.
If you can, install water fox (much like Firefox), and try to reproduce the problem. Do not import any configuration for it, configure the browser and the extensions from the beginning.
If you can reproduce the problem show me the settings made.

**Comment by grahamperrin** [comment]
I have great respect for Waterfox (for a long time, I was deeply involved with testing and support to end users) however it's no longer ported to FreeBSD, so I can't easily use it for steps to reproduce. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1694699#c10 seeks clearer STR; I'll add a screen recording somewhere under there.

**Comment by FilipePS** [comment]
On this side panel with the flaps. How did you open it? It doesn't show the tabs to me like that.

**Comment by FilipePS** [comment]
On this side panel with the list of tabs. How did you open it? It doesn't show the tabs to me like that.

**Comment by grahamperrin** [comment]
> … side panel … doesn't show the tabs to me like that.

The sidebar in the screen recording at https://github.com/FilipePS/Traduzir-paginas-web/issues/92#issue-812667545 is probably [Sidebar Tabs](https://addons.mozilla.org/addon/sidebartabs/), which I sometimes find convenient to use in my _test_ profile. 

Experiment with it if you like, but Sidebar Tabs is not in conflict. 

A made a detailed screen recording that should help you to visualise the conflicts. As soon as it's online, I'll let you know. 

Thanks again for your interest.

**Comment by grahamperrin** [comment]
Screen recording at https://bugzilla.mozilla.org/show_bug.cgi?id=1694699#c12

**Comment by FilipePS** [comment]
I managed to reproduce the bug.
And I noticed that if I disable the call to the function [chrome.tabs.onUpdated.addListener](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated) the bug does not happen.

**Comment by FilipePS** [comment]
I finished analyzing this bug and came to the following conclusion.

It is not an incompatibility between extensions, it is a Firefox bug.
For this bug to happen an extension needs 3 things:
1 - You need the permission **<all_urls>**, just **tabs** is not enough.
2 - A **background.js** file.
2 - Call the function [chrome.tabs.onUpdated.addListener](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated) in the background file.


Here, download a basic extension that generates this bug.
[STG_BUG.zip](https://github.com/FilipePS/Traduzir-paginas-web/files/6044960/STG_BUG.zip)

Note that in Firefox 86 Host permissions now grant access to privileged parts of the tabs API.

**Comment by grahamperrin** [comment]
Confirmed, I can reproduce the bug whilst your `STG_BUG.zip` is temporarily loaded alongside Simple Tab Groups.

**Comment by grahamperrin** [comment]
For your consideration, from today's <https://bugzilla.mozilla.org/show_bug.cgi?id=1694699#c29>:

> …Extensions in the second group can request the `tabs` permission to not trigger this bug. …

In any case: Firefox `87` is fixed, so if any other user of `86.⋯` does encounter the bug, it should be not too long to wait.

**Comment by grahamperrin** [comment]
Fixed in Firefox `86.0.1`: 

https://www.mozilla.org/en-US/firefox/86.0.1/releasenotes/#note-788600
