### ISSUE TITLE
Right to Left languages are still aligned right to left after translating.

### ISSUE THREAD

**Issue by maartenhunink** [FilipePS/Traduzir-paginas-web#94]
It would be great if the text of Right to Left languages would be aligned the left after being translated into a Left to Right language. I noticed when translating Arabic and Israeli websites into English the text is still aligned to the right, which is confusing with long text blocks.

Thank you for the awesome plugin!

**Comment by FilipePS** [comment]
This feature can potentially break the layout of some sites

**Comment by maartenhunink** [comment]
True, not sure the whole site should change alignment, but the texts itself could change alignment. Google Chrome does this by default, but I am not sure how they've choosen to implement it.

**Comment by FilipePS** [comment]
The discussion of this issue should continue here https://github.com/FilipePS/Traduzir-paginas-web/issues/93
