### ISSUE TITLE
Settings not available in the extensions menu

### ISSUE THREAD

**Issue by Systemcluster** [FilipePS/Traduzir-paginas-web#96]
Inside the browser extension menu, the sidebar where the settings category is selected is not visible and only some of the settings are available.

![options in extension menu](https://user-images.githubusercontent.com/2847328/110228167-47206e00-7eff-11eb-8bf4-587b40005259.png)

This seems to happen because the settings page hides the sidebar when the view area is too narrow.

The simplest workaround for this would be to disable the "inline" options page, so the full settings page always opens in a new tab. But there should also be a way to open the sidebar in a narrow window as well, instead of invariably hiding it.

**Comment by FilipePS** [comment]
I add a button to show the sidebar
https://github.com/FilipePS/Traduzir-paginas-web/commit/c286227793447cbb6b7d4b07e7f9cacedc2b3b03
